project_id = "bwhdazbotpblihdxcmho"

[functions.create-checkout]
verify_jwt = false

[functions.analyze-resume]
verify_jwt = false

[functions.parse-pdf]
verify_jwt = false

[functions.parse-docx]
verify_jwt = false

[functions.send-analysis-email]
verify_jwt = false
