export const EMPLOYER_ALIASES: Readonly<Record<string, { name: string; tokens: string[] }>> = {
  albertsonscompanies: { name: "Albertsons Companies", tokens: ["eofd~us6~CX_1"] },
  dominos: { name: "Domino's", tokens: ["dominos"] },
  aecom: { name: "AECOM", tokens: ["AECOM2"] },
  hilton: { name: "Hilton", tokens: ["efet~us2~CX_1"] },
  boschgroup: { name: "Bosch Group", tokens: ["BoschGroup"] },
  pwc: { name: "PwC", tokens: ["pwc~wd3~Global_Experienced_Careers", "pwc~wd3~US_Experienced_Careers", "pwc~wd3~crm_experienced_careers_site", "pwc~wd3~global_campus_careers"] },
  bayadahomehealthcare: { name: "BAYADA Home Health Care", tokens: ["bayada"] },
  jysk: { name: "JYSK", tokens: ["JYSK"] },
  sherwinwilliams: { name: "Sherwin-Williams", tokens: ["ejhp~us6~CX_1"] },
  northwesternmemorialhealthcare: { name: "Northwestern Memorial Healthcare", tokens: ["NorthwesternMedicine"] },
  hmgroup: { name: "H&M Group", tokens: ["HMGroup"] },
  turnertownsend: { name: "Turner & Townsend", tokens: ["TurnerTownsend"] },
  lifestancehealth: { name: "LifeStance Health", tokens: ["lifestance"] },
  pilotcompany: { name: "Pilot Company", tokens: ["PilotCompany"] },
  jcpenney: { name: "JCPenney", tokens: ["jobs.jcp.com"] },
  genesisadministrativeservices: { name: "Genesis Administrative Services", tokens: ["www.genesiscareers.jobs"] },
  bjak: { name: "BJAK", tokens: ["bjakcareer"] },
  abbvie: { name: "AbbVie", tokens: ["AbbVie"] },
  oracle: { name: "Oracle", tokens: ["eeho~us2~CX_1"] },
  boeing: { name: "Boeing", tokens: ["boeing~wd1~EXTERNAL_CAREERS", "boeing~wd1~external_subsidiary"] },
  accentcare: { name: "AccentCare", tokens: ["careers.accentcare.com"] },
  sgs: { name: "SGS", tokens: ["SGS"] },
  abbott: { name: "Abbott", tokens: ["abbott~wd5~abbottcareers", "abbott~wd5~abbottcareers2"] },
  hpe: { name: "HPE", tokens: ["hpe~wd5~Jobsathpe", "hpe~wd5~acjobsite"] },
  veoliaenvironnementsa: { name: "Veolia Environnement SA", tokens: ["VeoliaEnvironnementSA"] },
  eurofins: { name: "Eurofins", tokens: ["Eurofins"] },
  meijer: { name: "Meijer", tokens: ["meijer~wd5~Fresh_Thyme_Stores_External_Career_Site", "meijer~wd5~Meijer", "meijer~wd5~Meijer_Stores_Hourly", "meijer~wd5~Meijer_Stores_Leadership"] },
  brighthorizons: { name: "Bright Horizons", tokens: ["brighthorizons~wd5~External-NorthAmerica", "brighthorizons~wd5~External-UnitedKingdom"] },
  carvana: { name: "Carvana", tokens: ["carvana"] },
  tysonfoods: { name: "Tyson Foods", tokens: ["tysonfoods~wd5~TSN", "tysonfoods~wd5~TSN5"] },
  trilongroup: { name: "Trilon Group", tokens: ["trilongroup"] },
  next: { name: "Next", tokens: ["ekeq~em2~CX_1"] },
  spacex: { name: "SpaceX", tokens: ["spacex"] },
  centriaautism: { name: "Centria Autism", tokens: ["centriaautism"] },
  equipmentshare: { name: "EquipmentShare", tokens: ["equipmentsharecom"] },
  maersk: { name: "Maersk", tokens: ["maersk~wd3~Maersk_Careers", "maersk~wd3~Maersk_Manual"] },
  relx: { name: "RELX", tokens: ["relx~wd3~ElsevierJobs", "relx~wd3~LexisNexisLegal", "relx~wd3~RiskSolutions", "relx~wd3~relx"] },
  easyservice: { name: "Easyservice", tokens: ["easyservice~wd5~MercyHealthCareers", "easyservice~wd5~bonsecoursmercyhealthcareers", "easyservice~wd5~roperstfrancishealthcare"] },
  alten: { name: "ALTEN", tokens: ["ALTEN"] },
  jci: { name: "JCI", tokens: ["jci~wd5~JCI", "jci~wd5~JCI_Confidential"] },
  airliquide: { name: "Air Liquide", tokens: ["airliquidehr~wd3~AirLiquideExternalCareer", "airliquidehr~wd3~AirgasExternalCareer"] },
  hiltongrandvacations: { name: "Hilton Grand Vacations", tokens: ["efuq~us6~CX_1"] },
  orlandohealth: { name: "Orlando Health", tokens: ["careers.orlandohealth.com"] },
  belron: { name: "Belron", tokens: ["belron~wd3~Carglass_Deutschland", "belron~wd3~Safelite_Careers"] },
  busybees: { name: "Busy Bees", tokens: ["careers.giraffe.ie"] },
  andurilindustries: { name: "Anduril Industries", tokens: ["andurilindustries"] },
  rtx: { name: "RTX", tokens: ["globalhr~wd5~REC_RTX_Ext_Gateway", "globalhr~wd5~private_posting_no_tmp"] },
  mmc: { name: "Mmc", tokens: ["mmc~wd1~MMC", "mmc~wd1~careers"] },
  publicstorage: { name: "Public Storage", tokens: ["publicstorage"] },
  roche: { name: "Roche", tokens: ["roche~wd3~ROG-A2O-GENE", "roche~wd3~roche-ext"] },
  egisgroup: { name: "Egis Group", tokens: ["EgisGroup"] },
  metromakro: { name: "METRO/MAKRO", tokens: ["METROMAKRO"] },
  cvshealth: { name: "CVS Health", tokens: ["cvshealth~wd1~CVS_Health_Careers"] },
  disney: { name: "Disney", tokens: ["disney~wd5~disneycareer", "disney~wd5~disneycareerdc"] },
  soprasteria: { name: "Sopra Steria", tokens: ["SopraSteria1"] },
  mbda: { name: "Mbda", tokens: ["mbda~wd3~MBDA-DE", "mbda~wd3~MBDA-Italy", "mbda~wd3~MBDA-UK"] },
  uasys: { name: "Uasys", tokens: ["uasys~wd5~UAMS_All_Careers", "uasys~wd5~UASYS"] },
  mastec: { name: "MasTec", tokens: ["careers.mastec.com"] },
  mastecutilityservices: { name: "MasTec Utility Services", tokens: ["jobs.mastec.com"] },
  adventisthealth: { name: "Adventist Health", tokens: ["ecvz~us2~CX_1"] },
  ouihelp: { name: "Ouihelp", tokens: ["ouihelp"] },
  atuautoteileunger: { name: "A.T.U Auto-Teile-Unger", tokens: ["ATUAuto-Teile-Unger"] },
  caterpillar: { name: "Caterpillar", tokens: ["cat~wd5~SolarTurbines", "cat~wd5~caterpillarcareers"] },
  wellsfargo: { name: "Wells Fargo", tokens: ["wf~wd1~wellsfargojobs", "wf~wd1~wellsfargojobstargeted"] },
  synnex: { name: "Synnex", tokens: ["synnex~wd5~hyvecareers", "synnex~wd5~tdsynnexcareers"] },
  axa: { name: "AXA", tokens: ["careers.axa.com"] },
  ochsner: { name: "Ochsner", tokens: ["ochsner~wd1~Ochsner", "ochsner~wd1~OchsnerLSUHealthSystemNL"] },
  rvallgemeineversicherungag: { name: "R+V Allgemeine Versicherung AG", tokens: ["RVAllgemeineVersicherungenAG"] },
  bankofamerica: { name: "Bank of America", tokens: ["ghr~wd1~Lateral-US", "ghr~wd1~lateral-emea"] },
  usc: { name: "Usc", tokens: ["usc~wd5~ExternalKeckUSCCareers", "usc~wd5~ExternalUSCCareers"] },
  advancedmicrodevicesinc: { name: "Advanced Micro Devices, Inc", tokens: ["careers.amd.com"] },
  privateequityinsights: { name: "Private Equity Insights", tokens: ["privateequityinsights"] },
  vfcorporation: { name: "VF Corporation", tokens: ["vfc~wd5~vans_careers", "vfc~wd5~vfc_careers"] },
  mouvrh: { name: "Mouvrh", tokens: ["mouvrh~wd103~External_Career_Site_FRESH", "mouvrh~wd103~External_Career_Site_grand_frais"] },
  ing: { name: "ING", tokens: ["ing~wd3~ICSGBLCOR", "ing~wd3~jvsgblcor"] },
  myview: { name: "Myview", tokens: ["myview~wd3~paradox_careers"] },
  essentiahealth: { name: "Essentiahealth", tokens: ["essentiahealth~wd1~Essentia_Health", "essentiahealth~wd1~essentia_health_credentialed"] },
  uhs: { name: "UHS", tokens: ["jobs.uhsinc.com"] },
  circlek: { name: "Circlek", tokens: ["circlek~wd3~CircleKStoreJobs"] },
  advocatehealth: { name: "Advocate Health", tokens: ["aah~wd5~External"] },
  jcrew: { name: "Jcrew", tokens: ["jcrew~wd1~JCrewCareers", "jcrew~wd1~MadewellCareers"] },
  bjswholesaleclub: { name: "BJ's Wholesale Club", tokens: ["bjswholesaleclub~wd1~BJsCareers"] },
  oreillyautoparts: { name: "O'Reilly Auto Parts", tokens: ["oreillyauto~wd1~oreilly"] },
  ramsayhealthcare: { name: "Ramsay Health Care", tokens: ["RamsayHealthCare1", "ramsayhealthcare~wd3~Ramsay_Careers"] },
  labcorp: { name: "Labcorp", tokens: ["labcorp~wd1~External"] },
  dollartree: { name: "Dollar Tree", tokens: ["dollartree~wd5~dollartreeus"] },
  northropgrumman: { name: "Northrop Grumman", tokens: ["ngc~wd1~Northrop_Grumman_External_Site"] },
  att: { name: "AT&T", tokens: ["att~wd1~ATTGeneral"] },
  fivebelow: { name: "Fivebelow", tokens: ["fivebelow~wd1~fivebelowcareers"] },
  clevelandclinic: { name: "Cleveland Clinic", tokens: ["ccf~wd1~ClevelandClinicCareers"] },
  trinityhealth: { name: "Trinity Health", tokens: ["trinityhealth~wd1~Jobs"] },
  medtronic: { name: "Medtronic", tokens: ["medtronic~wd1~MedtronicCareers"] },
  bridgestone: { name: "Bridgestone", tokens: ["bridgestone~wd5~External"] },
  thriveworks: { name: "Thriveworks", tokens: ["thriveworks~wd5~Thriveworks"] },
  hyvee: { name: "Hy-Vee", tokens: ["hyvee~wd1~HyVeeCareers"] },
  intermountainhealth: { name: "Intermountain Health", tokens: ["imh~wd108~IntermountainCareers"] },
  bayonetplumbingheatingairconditioning: { name: "Bayonet Plumbing, Heating & Air-Conditioning", tokens: ["joinus.ies-co.com"] },
  caci: { name: "CACI", tokens: ["caci~wd1~External"] },
  mastercard: { name: "Mastercard", tokens: ["mastercard~wd1~CorporateCareers"] },
  usbank: { name: "U.S. Bank", tokens: ["usbank~wd1~US_Bank_Careers"] },
  calibercollision: { name: "Caliber Collision", tokens: ["calibercollision~wd1~Caliber"] },
  davita: { name: "DaVita", tokens: ["davita~wd1~DKC_External"] },
  iqvia: { name: "IQVIA", tokens: ["iqvia~wd1~IQVIA"] },
  target: { name: "Target", tokens: ["target~wd5~targetcareers"] },
  bmo: { name: "BMO", tokens: ["bmo~wd3~External"] },
  firststudent: { name: "First Student", tokens: ["firststudent~wd1~firststudent"] },
  medicaluniversityofsouthcarolina: { name: "Medical University of South Carolina", tokens: ["musc~wd1~MUSC"] },
  memorialhealthcaresystem: { name: "Memorial Healthcare System", tokens: ["memorialhealthcare~wd1~MHS_Careers"] },
  centerwellhumana: { name: "CenterWell (Humana)", tokens: ["humana~wd5~CenterWell_External_Career_Site"] },
  freseniusmedicalcare: { name: "Fresenius Medical Care", tokens: ["freseniusmedicalcare~wd3~fme"] },
  tmobile: { name: "Tmobile", tokens: ["tmobile~wd1~External"] },
  bannerhealth: { name: "Banner Health", tokens: ["bannerhealth~wd108~Careers"] },
  basspro: { name: "Basspro", tokens: ["basspro~wd1~careers"] },
  genuinepartscompany: { name: "Genuine Parts Company", tokens: ["genpt~wd1~Careers"] },
  republic: { name: "Republic", tokens: ["republic~wd5~Republic"] },
  sanford: { name: "Sanford", tokens: ["sanford~wd5~SanfordHealth"] },
  sysco: { name: "Sysco", tokens: ["sysco~wd5~syscocareers"] },
  dickssportinggoods: { name: "Dick's Sporting Goods", tokens: ["dickssportinggoods~wd1~DSG"] },
  hitachi: { name: "Hitachi", tokens: ["hitachi~wd1~hitachi"] },
  kohls: { name: "Kohl's", tokens: ["kohls~wd504~kohlscareers"] },
  nshs: { name: "Nshs", tokens: ["nshs~wd1~ns-eeh"] },
  amentum: { name: "Amentum", tokens: ["pae~wd1~Amentum_Careers"] },
  cardinalhealth: { name: "Cardinal Health", tokens: ["cardinalhealth~wd1~EXT"] },
  flex: { name: "Flex", tokens: ["flextronics~wd1~Careers"] },
  guidehouse: { name: "Guidehouse", tokens: ["guidehouse~wd1~External"] },
  highmarkhealth: { name: "Highmark Health", tokens: ["highmarkhealth~wd1~highmark"] },
  michaels: { name: "Michaels", tokens: ["michaels~wd5~External"] },
  ohiohealth: { name: "OhioHealth", tokens: ["ohiohealth~wd5~OhioHealthJobs"] },
  ssmhealth: { name: "SSM Health", tokens: ["ssmh~wd5~ssmhealth"] },
  boydgroup: { name: "Boydgroup", tokens: ["boydgroup~wd1~boydcareers"] },
  homedepot: { name: "Homedepot", tokens: ["homedepot~wd5~careerdepot"] },
  jll: { name: "JLL", tokens: ["jll~wd1~jllcareers"] },
  spectrumhealth: { name: "Spectrum Health", tokens: ["spectrumhealth~wd5~CorewellHealthCareers"] },
  tapestry: { name: "Tapestry", tokens: ["tapestry~wd108~Tapestry_Careers"] },
  wegmans: { name: "Wegmans", tokens: ["wegmans~wd1~Wegmans"] },
  airbus: { name: "Airbus", tokens: ["ag~wd3~Airbus"] },
  bristolmyerssquibb: { name: "Bristol Myers Squibb", tokens: ["bristolmyerssquibb~wd5~BMS"] },
  cox: { name: "Cox", tokens: ["cox~wd1~Cox_External_Career_Site_1"] },
  jabil: { name: "Jabil", tokens: ["jabil~wd5~Jabil_Careers"] },
  johnsonjohnson: { name: "Johnson & Johnson", tokens: ["jj~wd5~JJ"] },
  knitwellgroup: { name: "KnitWell Group", tokens: ["knitwellgroup~wd1~US_Retail_Jobs"] },
  stlukesuniversityhealthnetwork: { name: "St. Luke's University Health Network", tokens: ["sluhn~wd1~SLUHN"] },
  stryker: { name: "Stryker", tokens: ["stryker~wd1~StrykerCareers"] },
  universityofrochester: { name: "University of Rochester", tokens: ["ur~wd1~URcareers"] },
  vanderbiltuniversitymedicalcenter: { name: "Vanderbilt University Medical Center", tokens: ["vumc~wd1~vumccareers"] },
  wynd: { name: "Wynd", tokens: ["wynd~wd5~External"] },
  astrazeneca: { name: "AstraZeneca", tokens: ["astrazeneca~wd3~Careers"] },
  carmax: { name: "CarMax", tokens: ["carmax~wd1~External"] },
  cibc: { name: "CIBC", tokens: ["cibc~wd3~search"] },
  rrhs: { name: "Rrhs", tokens: ["rrhs~wd5~RRH"] },
  thermofisherscientific: { name: "Thermo Fisher Scientific", tokens: ["thermofisher~wd5~ThermoFisherCareers"] },
  aspendental: { name: "Aspen Dental", tokens: ["aspendental~wd1~careers_aspen_dental"] },
  belk: { name: "Belk", tokens: ["belk~wd1~Jobs-Stores"] },
  benchmark: { name: "Benchmark", tokens: ["benchmark~wd1~PGH_Careers"] },
  capitalone: { name: "Capital One", tokens: ["capitalone~wd12~Capital_One"] },
  carters: { name: "Carters", tokens: ["carters~wd1~CartersCareers"] },
  comcast: { name: "Comcast", tokens: ["comcast~wd5~Comcast_Careers"] },
  fifththirdbank: { name: "Fifth Third Bank", tokens: ["fifththird~wd5~53careers"] },
  gevernova: { name: "GE Vernova", tokens: ["gevernova~wd5~Vernova_ExternalSite"] },
  generalmotors: { name: "General Motors", tokens: ["generalmotors~wd5~Careers_GM"] },
  hcmportal: { name: "Hcmportal", tokens: ["hcmportal~wd5~Search"] },
  lehighvalleyhealthnetwork: { name: "Lehigh Valley Health Network", tokens: ["lvhn~wd1~lvhn"] },
  levistraussandco: { name: "Levistraussandco", tokens: ["levistraussandco~wd5~External"] },
  mtbank: { name: "M&T Bank", tokens: ["mtb~wd5~mtb"] },
  micron: { name: "Micron", tokens: ["micron~wd1~external"] },
  msd: { name: "MSD", tokens: ["msd~wd5~SearchJobs"] },
  paloaltonetworks: { name: "Palo Alto Networks", tokens: ["paloaltonetworks~wd5~panwexternalcareers"] },
  sanofi: { name: "Sanofi", tokens: ["sanofi~wd3~SanofiCareers"] },
  spartannash: { name: "SpartanNash", tokens: ["spartannash~wd1~SpartanNash_Careers"] },
  umassmemorialhealth: { name: "UMass Memorial Health", tokens: ["ummh~wd1~Careers"] },
  analogdevices: { name: "Analog Devices", tokens: ["analogdevices~wd1~External"] },
  avera: { name: "Avera", tokens: ["avera~wd5~avera-careers"] },
  dentsu: { name: "Dentsu", tokens: ["dentsuaegis~wd3~DAN_GLOBAL"] },
  gehealthcare: { name: "GE HealthCare", tokens: ["gehc~wd5~GEHC_ExternalSite"] },
  genpact: { name: "Genpact", tokens: ["genpact~wd108~External_Careers"] },
  greystar: { name: "Greystar", tokens: ["greystar~wd1~External"] },
  mango: { name: "Mango", tokens: ["mango~wd3~Mango_Work_Your_Passion"] },
  novartis: { name: "Novartis", tokens: ["novartis~wd3~Novartis_Careers"] },
  nvidia: { name: "NVIDIA", tokens: ["nvidia~wd5~NVIDIAExternalCareerSite"] },
  ohiostateuniversity: { name: "Ohio State University", tokens: ["osu~wd1~OSUCareers"] },
  rbc: { name: "RBC", tokens: ["rbc~wd3~RBCGLOBAL1"] },
  salesforce: { name: "Salesforce", tokens: ["salesforce~wd12~External_Career_Site"] },
  sci: { name: "Sci", tokens: ["sci~wd5~sci"] },
  universityofmiami: { name: "University of Miami", tokens: ["umiami~wd1~UMCareerStaff"] },
  barclays: { name: "Barclays", tokens: ["barclays~wd3~External_Career_Site_Barclays"] },
  brownuniversityhealth: { name: "Brown University Health", tokens: ["brownhealth~wd12~External_Careers"] },
  santander: { name: "Santander", tokens: ["santander~wd3~SantanderCareers"] },
  sunbeltrentals: { name: "Sunbelt Rentals", tokens: ["sunbeltrentals~wd1~sbcareers"] },
  uhaul: { name: "U-Haul", tokens: ["uhaul~wd1~UhaulJobs"] },
  wasteconnections: { name: "Waste Connections", tokens: ["wasteconnections~wd1~Careers"] },
  accenture: { name: "Accenture", tokens: ["accenture~wd103~AccentureCareers", "accenture~wd103~AvanadeCareers"] },
  abb: { name: "ABB", tokens: ["abb~wd3~external_career_page"] },
  chanel: { name: "Chanel", tokens: ["cc~wd3~ChanelCareers"] },
  fourseasons: { name: "Four Seasons", tokens: ["fourseasons~wd3~search"] },
  gsk: { name: "GSK", tokens: ["gsk~wd5~GSKCareers"] },
  myhrabc: { name: "Myhrabc", tokens: ["myhrabc~wd5~Global"] },
  parsons: { name: "Parsons", tokens: ["parsons~wd5~Search"] },
  sentara: { name: "Sentara", tokens: ["sentara~wd1~SCS"] },
  slihrms: { name: "Slihrms", tokens: ["slihrms~wd3~Careers"] },
  "2020companies": { name: "2020companies", tokens: ["2020companies~wd1~External_Careers"] },
  appliedmaterials: { name: "Applied Materials", tokens: ["amat~wd1~External"] },
  babilou: { name: "Babilou", tokens: ["babilou~wd3~Babilou"] },
  bah: { name: "BAH", tokens: ["bah~wd1~BAH_Jobs"] },
  barcelo: { name: "Barcelo", tokens: ["barcelo~wd3~Barcelo_Careers"] },
  bbva: { name: "BBVA", tokens: ["bbva~wd3~BBVA"] },
  circlehealth: { name: "Circlehealth", tokens: ["circlehealth~wd103~chgcareers"] },
  debeka: { name: "Debeka", tokens: ["debeka~wd3~Karriere"] },
  dinebrands: { name: "Dine Brands", tokens: ["dinebrands~wd503~RestaurantCareerSite"] },
  eiffage: { name: "Eiffage", tokens: ["eiffage~wd3~Eiffage_Careers"] },
  fielmann: { name: "Fielmann", tokens: ["fielmann~wd3~External"] },
  fina: { name: "Fina", tokens: ["fina~wd103~DeloitteRecrute"] },
  idex: { name: "Idex", tokens: ["idex~wd3~toutes-nos-offres-demploi"] },
  jeffersonhealth: { name: "Jefferson Health", tokens: ["jeffersonhealth~wd5~ThomasJeffersonExternal"] },
  kbr: { name: "KBR", tokens: ["kbr~wd5~KBR_Careers"] },
  kyndryl: { name: "Kyndryl", tokens: ["kyndryl~wd5~KyndrylProfessionalCareers"] },
  multicare: { name: "Multicare", tokens: ["multicare~wd1~multicare"] },
  tidalwaveautospa: { name: "Tidalwaveautospa", tokens: ["tidalwaveautospa~wd1~TWAS"] },
  campingworld: { name: "Camping World", tokens: ["campingworld~wd5~Jobs"] },
  primark: { name: "Primark", tokens: ["Primark"] },
  redbull: { name: "Red Bull", tokens: ["RedBull"] },
  rsm: { name: "Rsm", tokens: ["rsm~wd1~rsmcareers"] },
  acciona: { name: "Acciona", tokens: ["acciona~wd3~ACCIONA_Employment_Channel"] },
  lesschwab: { name: "Lesschwab", tokens: ["lesschwab~wd1~stores"] },
  pnc: { name: "PNC", tokens: ["pnc~wd5~External"] },
  bhs: { name: "Bhs", tokens: ["bhs~wd1~careers"] },
  pavago: { name: "Pavago", tokens: ["pavago"] },
  drivenbrands: { name: "Driven Brands", tokens: ["drivenbrands~wd1~DrivenBrandsCareerSite"] },
  dxctechnology: { name: "Dxctechnology", tokens: ["dxctechnology~wd1~DXCJobs"] },
  mars: { name: "Mars", tokens: ["mars~wd3~External"] },
  expressoilchangetireengineers: { name: "Express Oil Change & Tire Engineers", tokens: ["EOCTEBP"] },
  leidos: { name: "Leidos", tokens: ["leidos~wd5~External"] },
  tdbank: { name: "TD Bank", tokens: ["td~wd3~TD_Bank_Careers"] },
  bakerhughes: { name: "Baker Hughes", tokens: ["bakerhughes~wd5~BakerHughes"] },
  securitas: { name: "Securitas", tokens: ["Securitas"] },
  asmglobal: { name: "Asmglobal", tokens: ["asmglobal~wd1~careers"] },
  livenation: { name: "Livenation", tokens: ["livenation~wd503~InsomniacExternalSite", "livenation~wd503~LNExternalSite"] },
  westernveterinarypartnersllc: { name: "Western Veterinary Partners, LLC", tokens: ["westernveterinarypartnersllc"] },
  usfoods: { name: "Usfoods", tokens: ["usfoods~wd1~usfoodscareersExternal"] },
  mdlz: { name: "Mdlz", tokens: ["mdlz~wd3~External"] },
  kiongroup: { name: "Kiongroup", tokens: ["kiongroup~wd3~KIONGroup", "kiongroup~wd3~KION_SCS"] },
  geisinger: { name: "Geisinger", tokens: ["geisinger~wd5~GeisingerExternal"] },
  pacs: { name: "Pacs", tokens: ["pacs~wd108~pacs"] },
  gdit: { name: "GDIT", tokens: ["gdit~wd5~External_Career_Site"] },
  theuniversityofkansashealthsystem: { name: "The University of Kansas Health System", tokens: ["kansashealthsystem~wd1~careers"] },
  ferguson: { name: "Ferguson", tokens: ["ferguson~wd1~Ferguson_Experienced"] },
  lkqcorp: { name: "Lkqcorp", tokens: ["lkqcorp~wd5~ExternalCareerSite-LKQ"] },
  weismarkets: { name: "Weis Markets", tokens: ["weis~wd108~Careers"] },
  aoncorporation: { name: "Aon Corporation", tokens: ["jobs.aon.com"] },
  massgeneralbrigham: { name: "Massgeneralbrigham", tokens: ["massgeneralbrigham~wd1~MGBExternal"] },
  bilh: { name: "Bilh", tokens: ["bilh~wd1~External"] },
  pvh: { name: "PVH", tokens: ["pvh~wd1~PVH_Careers"] },
  williamssonoma: { name: "Williams-Sonoma", tokens: ["ehac~us6~CX_1"] },
  philips: { name: "Philips", tokens: ["philips~wd3~jobs-and-careers"] },
  wppmedia: { name: "WPP Media", tokens: ["wppmedia"] },
  manulife: { name: "Manulife", tokens: ["manulife~wd3~MFCJH_Jobs"] },
  rochester: { name: "Rochester", tokens: ["rochester~wd5~UR_Staff"] },
  rollsroyce: { name: "Rolls-Royce", tokens: ["rollsroyce~wd3~professional", "rollsroyce~wd3~rrpowersystems"] },
  skechers: { name: "Skechers", tokens: ["skechers~wd5~One-career-site"] },
  avisbudget: { name: "Avisbudget", tokens: ["avisbudget~wd1~ABG_Careers"] },
  deliveryhero: { name: "Delivery Hero", tokens: ["DeliveryHero"] },
  blueorigin: { name: "Blue Origin", tokens: ["blueorigin~wd5~BlueOrigin"] },
  carilionclinic: { name: "Carilion Clinic", tokens: ["carilionclinic~wd12~External_Careers"] },
  hubinternational: { name: "Hubinternational", tokens: ["hubinternational~wd1~HUBInternational"] },
  martinbrower: { name: "Martin Brower", tokens: ["jobportal.martinbrower.com"] },
  wellstar: { name: "Wellstar", tokens: ["wellstar~wd1~wellstarcareers"] },
  nike: { name: "Nike", tokens: ["nike~wd1~nke"] },
  unilever: { name: "Unilever", tokens: ["unilever~wd3~TMICC", "unilever~wd3~Unilever_Experienced_Professionals"] },
  whitecap: { name: "Whitecap", tokens: ["whitecap~wd1~careers"] },
  sunlife: { name: "Sunlife", tokens: ["sunlife~wd3~Experienced", "sunlife~wd3~Experienced-Jobs"] },
  asda: { name: "Asda", tokens: ["asda~wd103~AsdaJobs"] },
  pfizer: { name: "Pfizer", tokens: ["pfizer~wd1~PfizerCareers"] },
  virtua: { name: "Virtua", tokens: ["virtua~wd1~Virtua_Health_External_Career_Site"] },
  extraspacestorage: { name: "Extra Space Storage", tokens: ["extraspace~wd5~ESS_External"] },
  crowdstrike: { name: "Crowdstrike", tokens: ["crowdstrike~wd5~crowdstrikecareers"] },
  motorolasolutions: { name: "Motorola Solutions", tokens: ["motorolasolutions~wd5~Careers"] },
  stanleyblackdecker: { name: "Stanley Black & Decker", tokens: ["sbdinc~wd1~Stanley_Black_Decker_Career_Site"] },
  ufpindustries: { name: "UFP Industries", tokens: ["ufpi~wd503~ufpi"] },
  advanceauto: { name: "Advanceauto", tokens: ["advanceauto~wd5~AdvanceExternalCareers"] },
  mgmresorts: { name: "Mgmresorts", tokens: ["mgmresorts~wd5~MGMCareers"] },
  landrys: { name: "Landry's", tokens: ["careers.landrysinc.com"] },
  akima: { name: "Akima", tokens: ["careers.akima.com"] },
  allianceanimalhealth: { name: "Alliance Animal Health", tokens: ["AllianceAnimalHealth"] },
  ramboll: { name: "Ramboll", tokens: ["Ramboll3"] },
  uline: { name: "Uline", tokens: ["uline~wd1~Uline_Careers"] },
  tti: { name: "Tti", tokens: ["tti~wd1~Milwaukee", "tti~wd1~TTI_PE"] },
  autodesk: { name: "Autodesk", tokens: ["autodesk~wd1~Ext"] },
  bmc: { name: "Bmc", tokens: ["bmc~wd1~BMC"] },
  uob: { name: "UOB", tokens: ["uobgroup~wd3~UOBExternal"] },
  intel: { name: "Intel", tokens: ["intel~wd1~External"] },
  galderma: { name: "Galderma", tokens: ["galderma~wd3~External", "galderma~wd3~broadbean_external"] },
  upstreamrehabilitation: { name: "Upstream Rehabilitation", tokens: ["urpt"] },
  fiserv: { name: "Fiserv", tokens: ["fiserv~wd5~EXT"] },
  kla: { name: "KLA", tokens: ["kla~wd1~Search"] },
  panerabread: { name: "Panera Bread", tokens: ["panerabread~wd5~Panera_Careers"] },
  amcor: { name: "Amcor", tokens: ["amcor~wd5~amcor_external_career_site"] },
  bupa: { name: "Bupa", tokens: ["bupa~wd3~EXT_CAREER"] },
  kimmelassociates: { name: "Kimmel & Associates", tokens: ["kimmel-associates"] },
  nuffieldhealth: { name: "Nuffield Health", tokens: ["nuffieldhealth~wd3~NH_Careers"] },
  saks: { name: "Saks", tokens: ["saks~wd1~careers_at_saks"] },
  keybank: { name: "Keybank", tokens: ["keybank~wd5~External_Career_Site"] },
  regeneron: { name: "Regeneron", tokens: ["regeneron~wd1~Careers"] },
  usphysicaltherapy: { name: "US Physical Therapy", tokens: ["USPhysicalTherapy2"] },
  townepark: { name: "Townepark", tokens: ["townepark~wd5~ext"] },
  haleon: { name: "Haleon", tokens: ["gsknch~wd3~GSKCareers"] },
  heidelbergmaterials: { name: "Heidelbergmaterials", tokens: ["heidelbergmaterials~wd3~Global_HM_Career_Site"] },
  kone: { name: "KONE", tokens: ["kone~wd3~Careers"] },
  sedgwick: { name: "Sedgwick", tokens: ["sedgwick~wd1~Sedgwick"] },
  onehealthineers: { name: "Onehealthineers", tokens: ["onehealthineers~wd3~SHSJB", "onehealthineers~wd3~ijmhrms"] },
  sec: { name: "Sec", tokens: ["sec~wd3~Samsung_Careers"] },
  albanymed: { name: "Albany Med", tokens: ["albanymed~wd5~Albany_Med"] },
  v2x: { name: "V2X", tokens: ["careers.gov2x.com"] },
  shm: { name: "Shm", tokens: ["shm~wd5~Summit_CityMD"] },
  wabtec: { name: "Wabtec", tokens: ["Wabtec"] },
  heinz: { name: "Heinz", tokens: ["heinz~wd1~KraftHeinz_Careers", "heinz~wd1~KraftHeinz_Careers_BC"] },
  icf: { name: "Icf", tokens: ["icf~wd5~ICFExternal_Career_Site"] },
  valeo: { name: "Valeo", tokens: ["valeo~wd3~valeo_jobs"] },
  weekdayai: { name: "Weekday AI", tokens: ["weekday-1"] },
  servicenow: { name: "ServiceNow", tokens: ["ServiceNow"] },
  washingtonuniversityinstlouis: { name: "Washington University in St. Louis", tokens: ["wustl~wd1~External"] },
  extendicare: { name: "Extendicare", tokens: ["extendicare~wd10~Extendicare2023", "extendicare~wd10~Paramed2023"] },
  adventisthealthcare: { name: "Adventist HealthCare", tokens: ["adventisthealthcare~wd1~AdventistHealthCareCareers"] },
  cigna: { name: "Cigna", tokens: ["cigna~wd5~cignacareers"] },
  geaerospace: { name: "GE Aerospace", tokens: ["geaerospace~wd5~GE_ExternalSite"] },
  globalmedicalresponse: { name: "Global Medical Response", tokens: ["careers.gmr.net"] },
  lseg: { name: "Lseg", tokens: ["lseg~wd3~Careers"] },
  smithfieldfoods: { name: "Smithfieldfoods", tokens: ["smithfieldfoods~wd1~Careers"] },
  destinationcareers: { name: "Destination Careers", tokens: ["destinationknot"] },
  gundersenhealth: { name: "Gundersenhealth", tokens: ["gundersenhealth~wd5~Gundersen"] },
  renesaselectronics: { name: "Renesas Electronics", tokens: ["RenesasElectronics"] },
  lonza: { name: "Lonza", tokens: ["lonza~wd3~Lonza_Careers"] },
  ryder: { name: "Ryder", tokens: ["ryder~wd5~RyderCareers"] },
  uottawa: { name: "Uottawa", tokens: ["uottawa~wd3~uOttawa_External_Career_Site"] },
  aia: { name: "Aia", tokens: ["aia~wd3~External"] },
  ecolab: { name: "Ecolab", tokens: ["ecolab~wd1~ecolab_external"] },
  bectondickinson: { name: "Becton Dickinson", tokens: ["bdx~wd1~EXTERNAL_CAREER_SITE_USA"] },
  fidelity: { name: "Fidelity", tokens: ["fmr~wd1~fidelitycareers"] },
  ocbc: { name: "OCBC", tokens: ["ocbc~wd102~External"] },
  baxter: { name: "Baxter", tokens: ["baxter~wd1~baxter"] },
  cnx: { name: "Cnx", tokens: ["cnx~wd1~external_global"] },
  pennstateuniversity: { name: "Penn State University", tokens: ["psu~wd1~PSU_Staff"] },
  horacemannagentopportunities: { name: "Horace Mann - Agent Opportunities", tokens: ["horacemannagents"] },
  adobe: { name: "Adobe", tokens: ["adobe~wd5~external_experienced"] },
  coffeeandbagelbrands: { name: "Coffee and Bagel Brands", tokens: ["coffeeandbagelbrands~wd1~coffeeandbagelbrands"] },
  mymvw: { name: "Mymvw", tokens: ["mymvw~wd5~MVW"] },
  utaustin: { name: "Utaustin", tokens: ["utaustin~wd1~UTstaff", "utaustin~wd1~UTstudent"] },
  parstherapy: { name: "PARS Therapy", tokens: ["pars-therapy"] },
  intuitive: { name: "Intuitive", tokens: ["intuitive"] },
  ntu: { name: "Ntu", tokens: ["ntu~wd3~Careers"] },
  okgov: { name: "Okgov", tokens: ["okgov~wd1~okgovjobs"] },
  hdsupply: { name: "HD Supply", tokens: ["hdsupply~wd1~external"] },
  mercierconsultancygroup: { name: "Mercier Consultancy Group", tokens: ["mercier-consultancy-group"] },
  swarovski: { name: "Swarovski", tokens: ["swarovski~wd3~swarovski"] },
  zeissgroup: { name: "Zeissgroup", tokens: ["zeissgroup~wd3~External"] },
  pfg: { name: "Pfg", tokens: ["pfg~wd3~SaveonfoodsCareers"] },
  then2company: { name: "The N2 Company", tokens: ["n2publishingglassdoor"] },
  oldmutual: { name: "Old Mutual", tokens: ["oldmutual~wd3~Old_Mutual_Careers"] },
  princesscruises: { name: "Princesscruises", tokens: ["princesscruises"] },
  vcuhealth: { name: "Vcuhealth", tokens: ["vcuhealth~wd1~VCUHealth_careers"] },
  ingrammicro: { name: "Ingrammicro", tokens: ["ingrammicro~wd5~IngramMicro"] },
  nationwidechildrens: { name: "Nationwidechildrens", tokens: ["nationwidechildrens~wd5~NCHCareers"] },
  gartner: { name: "Gartner", tokens: ["gartner~wd5~EXT"] },
  northerntrust: { name: "Northern Trust", tokens: ["ntrs~wd1~northerntrust"] },
  medline: { name: "Medline", tokens: ["medline~wd5~Medline"] },
  brightli: { name: "Brightli", tokens: ["brightli~wd5~BrightliTalent"] },
  mckesson: { name: "Mckesson", tokens: ["mckesson~wd3~External_Careers"] },
  nationalfederationofindependentbusinessnfib: { name: "National Federation of Independent Business (NFIB)", tokens: ["careers.nfib.com"] },
  ecs: { name: "ECS", tokens: ["careers.ecslimited.com"] },
  marmon: { name: "Marmon", tokens: ["marmon~wd501~Marmon_Careers"] },
  bne: { name: "Bne", tokens: ["bne~wd1~Hardees"] },
  mufgub: { name: "Mufgub", tokens: ["mufgub~wd3~MUFG-Careers"] },
  "7eleven": { name: "7-Eleven", tokens: ["my7elevenhr~wd12~Careers"] },
  michelinhr: { name: "Michelinhr", tokens: ["michelinhr~wd3~Michelin"] },
  renuity: { name: "Renuity", tokens: ["renuity"] },
  gilead: { name: "Gilead", tokens: ["gilead~wd1~gileadcareers", "gilead~wd1~gileadhotjobcareers"] },
  scahealth: { name: "SCA Health", tokens: ["careers.sca.health"] },
  cottonon: { name: "Cotton On", tokens: ["ekxm~ap1~CX_1"] },
  erickson: { name: "Erickson", tokens: ["erickson~wd108~External"] },
  assystem: { name: "ASSYSTEM", tokens: ["ASSYSTEM"] },
  radnet: { name: "RadNet", tokens: ["careers.radnet.com"] },
  erm: { name: "Erm", tokens: ["erm~wd3~ERM_Careers"] },
  ppg: { name: "PPG", tokens: ["ppg~wd5~ppg_careers"] },
  syneoshealth: { name: "Syneoshealth", tokens: ["syneoshealth~wd12~Syneos_Health_External_Site"] },
  sixt: { name: "SIXT", tokens: ["SIXT"] },
  ssctech: { name: "Ssctech", tokens: ["ssctech~wd1~ssctechnologies"] },
  whataburger: { name: "Whataburger", tokens: ["whataburger~wd5~WAB_CAREERS"] },
  brookfield: { name: "Brookfield", tokens: ["brookfield~wd5~brookfield", "brookfield~wd5~brookfieldproperties"] },
  wisconsin: { name: "Wisconsin", tokens: ["wisconsin~wd1~UW_Comprehensives", "wisconsin~wd1~UW_Madison"] },
  catalent: { name: "Catalent", tokens: ["catalent~wd1~External"] },
  continental: { name: "Continental", tokens: ["Continental"] },
  thomsonreuters: { name: "Thomson Reuters", tokens: ["thomsonreuters~wd5~External_Career_Site"] },
  flir: { name: "Flir", tokens: ["flir~wd1~flircareers"] },
  svha: { name: "Svha", tokens: ["svha~wd3~SVHA_SVHA", "svha~wd3~broadbean_external"] },
  nov: { name: "NOV", tokens: ["egay~us6~CX_1"] },
  rivhs: { name: "Rivhs", tokens: ["rivhs~wd1~Non-ProviderRHS"] },
  jbhunt: { name: "Jbhunt", tokens: ["jbhunt~wd501~Careers"] },
  humana: { name: "Humana", tokens: ["humana~wd5~Humana_External_Career_Site"] },
  thirdchannel: { name: "ThirdChannel", tokens: ["thirdchannel-inc"] },
  ace: { name: "Ace", tokens: ["ace~wd5~careers"] },
  hyperiongrp: { name: "Hyperiongrp", tokens: ["hyperiongrp~wd3~Hyperion_External", "hyperiongrp~wd3~broadbean_external"] },
  medhealth: { name: "MedHealth", tokens: ["MedHealth3"] },
  saintlukes: { name: "Saintlukes", tokens: ["saintlukes~wd1~saintlukeshealthcareers"] },
  asml: { name: "ASML", tokens: ["asml~wd3~asmlext1"] },
  wakemed: { name: "WakeMed", tokens: ["jobs.wakemed.org"] },
  mindrift: { name: "Mindrift", tokens: ["toloka-ai"] },
  onelineage: { name: "Onelineage", tokens: ["onelineage~wd1~External"] },
  texasamuniversitysystem: { name: "Texas A&M University System", tokens: ["tamus~wd1~System-wide_External"] },
  vanguard: { name: "Vanguard", tokens: ["vanguard~wd5~vanguard_external"] },
  veterinaryemergencygroupveg: { name: "Veterinary Emergency Group (VEG)", tokens: ["veterinaryemergencygroupst"] },
  allstate: { name: "Allstate", tokens: ["allstate~wd5~allstate_careers"] },
  sasllc: { name: "Sasllc", tokens: ["sasllc~wd1~Careers"] },
  cgm: { name: "Cgm", tokens: ["cgm~wd3~cgm"] },
  oshkoshcorporation: { name: "Oshkoshcorporation", tokens: ["oshkoshcorporation~wd5~Oshkosh"] },
  "10000blackinterns": { name: "10,000 Black Interns", tokens: ["10kbi"] },
  sandvik: { name: "Sandvik", tokens: ["sandvik~wd3~sandvik-jobs"] },
  bluelightconsulting: { name: "Bluelight Consulting", tokens: ["bluelightconsulting"] },
  trumed: { name: "Trumed", tokens: ["trumed~wd1~TMC_External_Career_Site"] },
  abercrombie: { name: "Abercrombie", tokens: ["abercrombie~wd108~anf"] },
  nxp: { name: "Nxp", tokens: ["nxp~wd3~careers"] },
  saintfrancis: { name: "Saintfrancis", tokens: ["saintfrancis~wd115~External"] },
  globalfoundries: { name: "Globalfoundries", tokens: ["globalfoundries~wd1~External"] },
  newyorkpresbyterian: { name: "NewYork-Presbyterian", tokens: ["nyp~wd1~nypcareers"] },
  solenis: { name: "Solenis", tokens: ["solenis~wd1~Solenis"] },
  iff: { name: "Iff", tokens: ["iff~wd5~IFF_Careers"] },
  cedarssinai: { name: "Cedars-Sinai", tokens: ["hdkk~us6~CX_1"] },
  lego: { name: "Lego", tokens: ["lego~wd103~LEGO_External"] },
  elevancehealth: { name: "Elevance Health", tokens: ["elevancehealth~wd1~ANT"] },
  alcon: { name: "Alcon", tokens: ["alcon~wd5~careers_alcon"] },
  christianacare: { name: "Christianacare", tokens: ["christianacare~wd5~CCHS"] },
  groundworks: { name: "Groundworks", tokens: ["groundworks~wd1~Groundworks"] },
  kempinski: { name: "Kempinski", tokens: ["kempinski"] },
  theapexgroup: { name: "Theapexgroup", tokens: ["theapexgroup~wd3~apexgroupcareers"] },
  fogo: { name: "Fogo", tokens: ["fogo~wd5~Fogo"] },
  aresmgmt: { name: "Aresmgmt", tokens: ["aresmgmt~wd1~External"] },
  coxhealth: { name: "Coxhealth", tokens: ["coxhealth~wd5~CoxHealth_External"] },
  danaher: { name: "Danaher", tokens: ["danaher~wd1~DanaherJobs"] },
  ferrovial: { name: "Ferrovial", tokens: ["ferrovial~wd3~Ferrovial_Career_Site"] },
  fedex: { name: "Fedex", tokens: ["fedex~wd1~FXE_APAC_External", "fedex~wd1~fxe-eu_external"] },
  infuse: { name: "INFUSE", tokens: ["infuse"] },
  raisingcanes: { name: "Raising Cane's", tokens: ["RaisingCanes"] },
  hhs: { name: "Hhs", tokens: ["hhs~wd12~HHS1HourlyJobs", "hhs~wd12~HHS1Jobs"] },
  atriumhospitality: { name: "Atriumhospitality", tokens: ["atriumhospitality~wd5~AtriumHospitality"] },
  universityofcaliforniairvine: { name: "University of California, Irvine", tokens: ["jobs.uci.edu"] },
  xylem: { name: "Xylem", tokens: ["xylem~wd5~xylem-careers"] },
  bakertilly: { name: "Bakertilly", tokens: ["bakertilly~wd5~btcareers"] },
  srsdistribution: { name: "Srsdistribution", tokens: ["srsdistribution~wd1~GMS", "srsdistribution~wd1~SRS"] },
  gohealthuc: { name: "Gohealthuc", tokens: ["gohealthuc~wd12~External"] },
  aisleandabroad: { name: "Aisle And Abroad", tokens: ["aisle_and_abroad"] },
  paychex: { name: "Paychex", tokens: ["careers.paychex.com"] },
  americanredcross: { name: "Americanredcross", tokens: ["americanredcross~wd1~American_Red_Cross_Careers"] },
  experian: { name: "Experian", tokens: ["Experian"] },
  leonardocompany: { name: "Leonardocompany", tokens: ["leonardocompany~wd3~LeonardoCareerSite"] },
  nghs: { name: "Nghs", tokens: ["nghs~wd1~External"] },
  desjardins: { name: "Desjardins", tokens: ["desjardins~wd10~desjardins"] },
  r1rcm: { name: "R1rcm", tokens: ["r1rcm~wd1~R1RCM"] },
  nielseniq: { name: "NielsenIQ", tokens: ["NielsenIQ"] },
  rockwellautomation: { name: "Rockwell Automation", tokens: ["rockwellautomation~wd1~External_Rockwell_Automation"] },
  brookshires: { name: "Brookshires", tokens: ["brookshires~wd108~BGC"] },
  ebay: { name: "eBay", tokens: ["ebay~wd5~apply"] },
  agecare: { name: "Agecare", tokens: ["agecare~wd10~AgeCare_Careers_External"] },
  dungarvin: { name: "Dungarvin", tokens: ["Dungarvin"] },
  wood: { name: "Wood", tokens: ["ehif~em2~CX_1"] },
  gfs: { name: "Gfs", tokens: ["gfs~wd5~usjobs-gen-gfs"] },
  nexstar: { name: "Nexstar", tokens: ["nexstar~wd5~nexstar"] },
  brunswick: { name: "Brunswick", tokens: ["brunswick~wd1~search"] },
  deangelocontractingservices: { name: "DeAngelo Contracting Services", tokens: ["DeAngeloContractingServices"] },
  dhpace: { name: "DH Pace", tokens: ["dhpace"] },
  familyresourcehomecare: { name: "Family Resource Home Care", tokens: ["family-resource-home-care"] },
  frasersgroup: { name: "Frasers Group", tokens: ["FrasersGroup"] },
  nbcuniversal: { name: "NBCUniversal", tokens: ["NBCUniversal3"] },
  zoetis: { name: "Zoetis", tokens: ["zoetis~wd5~broadbean_external", "zoetis~wd5~zoetis"] },
  nvent: { name: "Nvent", tokens: ["nvent~wd5~nVent"] },
  "84lumber": { name: "84 Lumber", tokens: ["careers.84lumber.com"] },
  agiliti: { name: "Agiliti", tokens: ["agiliti~wd5~Careers", "agiliti~wd5~Operations"] },
  eyecarepartnerscareeropportunities: { name: "Eye Care Partners Career Opportunities", tokens: ["ecpcareers"] },
  lanesgroup: { name: "Lanes Group", tokens: ["lanesgroup"] },
  loganhealth: { name: "Loganhealth", tokens: ["loganhealth~wd1~Logan_Careers"] },
  openai: { name: "OpenAI", tokens: ["openai"] },
  sagehaus: { name: "Sage Haus", tokens: ["sage-haus"] },
  ensemblehp: { name: "Ensemblehp", tokens: ["ensemblehp~wd5~EnsembleHealthPartnersCareers"] },
  regalrexnord: { name: "Regalrexnord", tokens: ["regalrexnord~wd1~Careers"] },
  stormontvail: { name: "Stormontvail", tokens: ["stormontvail~wd1~SVH"] },
  archildrens: { name: "Archildrens", tokens: ["archildrens~wd1~External_Career_Site"] },
  coupang: { name: "Coupang", tokens: ["coupang"] },
  myhrhome: { name: "Myhrhome", tokens: ["myhrhome~wd1~OneMainCareers"] },
  card: { name: "Card", tokens: ["card~wd5~Search"] },
  selinc: { name: "Selinc", tokens: ["selinc~wd1~SEL"] },
  arrow: { name: "Arrow", tokens: ["arrow~wd1~ac"] },
  davebusters: { name: "Dave & Buster's", tokens: ["daveandbusters~wd1~Dave_and_Busters_Careers"] },
  bobsdf: { name: "Bobsdf", tokens: ["bobsdf~wd1~Bobs_Careers"] },
  entegris: { name: "Entegris", tokens: ["entegris~wd1~EntegrisCareers"] },
  fis: { name: "FIS", tokens: ["fis~wd5~SearchJobs"] },
  spglobal: { name: "S&P Global", tokens: ["spgi~wd5~SPGI_Careers"] },
  auchanportugal: { name: "Auchanportugal", tokens: ["auchanportugal~wd3~auchan-retail"] },
  bronsonhg: { name: "Bronsonhg", tokens: ["bronsonhg~wd1~newhires"] },
  destinationpet: { name: "Destinationpet", tokens: ["destinationpet~wd5~DPEC"] },
  prysmiangroup: { name: "Prysmiangroup", tokens: ["prysmiangroup~wd3~Careers"] },
  tuftsmedicine: { name: "Tuftsmedicine", tokens: ["tuftsmedicine~wd1~Jobs"] },
  lbg: { name: "Lbg", tokens: ["lbg~wd3~broadbean_external", "lbg~wd3~lbg_Careers"] },
  cornell: { name: "Cornell", tokens: ["cornell~wd1~CornellCareerPage", "cornell~wd1~cornellpositions"] },};