// The job board's company allowlist. Every entry was LIVE-VERIFIED against
// the ATS's official public job-board API before shipping (200 + >0 postings,
// last sweep 2026-07-11, 870 companies). These endpoints are published by the vendors for exactly
// this consumption — no scraping, no auth, no ToS gray zone:
//   Greenhouse: https://boards-api.greenhouse.io/v1/boards/{token}/jobs
//   Lever:      https://api.lever.co/v0/postings/{token}?mode=json
//   Ashby:      https://api.ashbyhq.com/posting-api/job-board/{token}
// Tokens rot when companies migrate ATSs; the fetcher tolerates failures and
// reports failedSources so a dead token degrades, never breaks, the board.

export type JobSourceKind = "greenhouse" | "lever" | "ashby" | "smartrecruiters" | "workable" | "bamboohr";

export interface JobSource {
  name: string; // display name
  source: JobSourceKind;
  token: string; // the company's board token on that ATS
}

// Boards with heavy inventory get re-checked every cycle (~10 min); the
// long tail rotates through cold slices (full rotation ≤ ~1 hour). The set
// is recomputed at each discovery sweep from verified posting counts.
export const HOT_TOKENS: Set<string> = new Set([
  "boxlunch", "BoschGroup", "CROSSMARK1", "SGS", "AECOM2", "Dominos",
  "GreeneKing", "VeoliaEnvironnementSA", "JYSK", "TurnerTownsend", "eosfitness", "pulse",
  "bayada", "Eurofins", "andurilindustries", "carvana", "SopraSteria1", "spacex",
  "liquidpersonnel", "Securitas", "Devoteam", "Continental", "agency", "databricks",
  "veeva", "plscareers", "openai", "Experian", "Accor", "stripe",
  "datadog", "snowflake", "ServiceNow", "anthropic", "mongodb", "hellofresh",
  "rocketlab", "okta", "harvey", "relativity", "onemedical", "latitudeinc",
  "samsara", "toast", "coreweave", "remotecom", "palantir", "sila",
  "brex", "oscar", "applied", "CesiumAstro", "lucidmotors", "cloudflare",
  "distro", "point72", "scoutmotors", "legora", "braze", "Ubisoft2",
  "zoox", "janestreet", "xai", "airbnb", "icapitalnetwork", "sezzle",
  "betterhelp", "urbancompass", "deliveroo", "super", "optiverus", "sonyinteractiveentertainmentglobal",
  "pinterest", "reddit", "scaleai", "trueanomalyinc", "wyetechllc", "elevenlabs",
  "affirm", "prolific", "figma", "klaviyo", "clera", "base-power",
  "imc", "sierra", "stage", "twilio", "whoop", "gitlab",
  "asana", "aurorainnovation", "flexport", "notion", "instacart", "scopely",
  "drweng", "intercom", "hadrian-automation", "zip", "coinbase", "octoenergy",
  "cohere", "handshake", "fivetran", "ramp", "Sodexo", "LGCGroup",
  "ixllearning", "lilasciences", "trm-labs", "vanta", "decagon", "cursor",
  "robinhood", "tractian", "Colliers", "spotify", "billiontoone", "justworks",
]);

export const JOB_SOURCES: JobSource[] = [
  // CDX census sweep (2026-07-12): Wayback CDX enumeration of vendor domains,
  // every board live-verified via the vendor's official public API and named
  // from the vendor's own metadata. 14 boards, ~37782 postings at selection time.
  { name: "EōS Fitness", source: "greenhouse", token: "eosfitness" },
  { name: "BAYADA Home Health Care", source: "greenhouse", token: "bayada" },
  { name: "Carvana", source: "greenhouse", token: "carvana" },
  { name: "Liquid Personnel", source: "greenhouse", token: "liquidpersonnel" },
  { name: "BoxLunch & Hot Topic", source: "lever", token: "boxlunch" },
  { name: "CROSSMARK", source: "smartrecruiters", token: "CROSSMARK1" },
  { name: "SGS", source: "smartrecruiters", token: "SGS" },
  { name: "AECOM", source: "smartrecruiters", token: "AECOM2" },
  { name: "Domino's", source: "smartrecruiters", token: "Dominos" },
  { name: "Greene King", source: "smartrecruiters", token: "GreeneKing" },
  { name: "Veolia Environnement SA", source: "smartrecruiters", token: "VeoliaEnvironnementSA" },
  { name: "Turner & Townsend", source: "smartrecruiters", token: "TurnerTownsend" },
  { name: "Eurofins", source: "smartrecruiters", token: "Eurofins" },
  { name: "Sopra Steria", source: "smartrecruiters", token: "SopraSteria1" },
  // Sweep #5 (2026-07-11): 261 boards from public link corpora + YC remainder.
  { name: "8vc", source: "ashby", token: "8vc" },
  { name: "ABACUS", source: "greenhouse", token: "abacus" },
  { name: "Able", source: "greenhouse", token: "able" },
  { name: "Aledade", source: "lever", token: "aledade" },
  { name: "Alpha Financial Markets Consulting", source: "greenhouse", token: "alphafmcroles" },
  { name: "Alta Resource Technologies, Inc.", source: "greenhouse", token: "altaresourcetechnologiesinc" },
  { name: "AMAROK", source: "greenhouse", token: "amarok" },
  { name: "Anduril Industries", source: "greenhouse", token: "andurilindustries" },
  { name: "Applied", source: "ashby", token: "applied" },
  { name: "Aqua Voice", source: "ashby", token: "aqua-voice" },
  { name: "Aquatic Capital Management", source: "greenhouse", token: "aquaticcapitalmanagement" },
  { name: "Ark Veterinary Hospital & Urgent Care", source: "greenhouse", token: "ark" },
  { name: "Armory", source: "ashby", token: "armory" },
  { name: "Artefact US", source: "greenhouse", token: "artefactus" },
  { name: "Astera", source: "ashby", token: "astera" },
  { name: "Astera Labs Early", source: "greenhouse", token: "asteraearlycareer2026" },
  { name: "Authorium", source: "ashby", token: "Authorium" },
  { name: "B12", source: "greenhouse", token: "b12" },
  { name: "Babel Street", source: "greenhouse", token: "babelstreet" },
  { name: "Base Power", source: "ashby", token: "base-power" },
  { name: "Bayutdubizzle", source: "workable", token: "bayutdubizzle" },
  { name: "BDG", source: "lever", token: "BDG" },
  { name: "Ben", source: "ashby", token: "ben" },
  { name: "Beyond Reach Labs", source: "ashby", token: "beyondreachlabs" },
  { name: "Bifrost", source: "ashby", token: "bifrost" },
  { name: "BillionToOne", source: "greenhouse", token: "billiontoone" },
  { name: "Binance Us", source: "ashby", token: "binance.us" },
  { name: "Birdie", source: "ashby", token: "birdie" },
  { name: "Blink", source: "ashby", token: "blink" },
  { name: "Blue", source: "lever", token: "blue" },
  { name: "Bot Auto", source: "greenhouse", token: "botauto" },
  { name: "Brainco", source: "ashby", token: "brainco" },
  { name: "Breaker", source: "ashby", token: "breaker" },
  { name: "Built Technologies", source: "greenhouse", token: "getbuilt" },
  { name: "CAMP", source: "greenhouse", token: "camp" },
  { name: "CAPSULE", source: "ashby", token: "capsule" },
  { name: "Capy", source: "ashby", token: "capy" },
  { name: "Carbon, Inc.", source: "greenhouse", token: "carbon" },
  { name: "Careers at KKR", source: "greenhouse", token: "stage" },
  { name: "Cedar", source: "ashby", token: "cedar" },
  { name: "Centerfield", source: "ashby", token: "centerfield" },
  { name: "Cerebras", source: "ashby", token: "cerebras" },
  { name: "CesiumAstro", source: "lever", token: "CesiumAstro" },
  { name: "CGS Nexus", source: "greenhouse", token: "nexus" },
  { name: "Clarity Innovations", source: "greenhouse", token: "clarityinnovates" },
  { name: "CLEAR - Corporate", source: "greenhouse", token: "clear" },
  { name: "Clera", source: "ashby", token: "clera" },
  { name: "Clever", source: "greenhouse", token: "clever" },
  { name: "Clinical Architecture", source: "greenhouse", token: "clinicalarchitecture" },
  { name: "Clutch Technologies Inc.", source: "greenhouse", token: "clutch" },
  { name: "Collective", source: "ashby", token: "collective" },
  { name: "Compound", source: "ashby", token: "compound" },
  { name: "Context.dev", source: "ashby", token: "context" },
  { name: "Continue", source: "ashby", token: "continue" },
  { name: "Cylake Inc", source: "ashby", token: "cylake-inc" },
  { name: "D3", source: "greenhouse", token: "d3" },
  { name: "Datalabusa", source: "lever", token: "datalabusa" },
  { name: "Deliveroo", source: "ashby", token: "deliveroo" },
  { name: "Diversified Automation", source: "lever", token: "diversified-automation" },
  { name: "Docugami", source: "greenhouse", token: "docugami" },
  { name: "Double \u2013 Coding Copilot", source: "ashby", token: "double" },
  { name: "Doublezero", source: "ashby", token: "doublezero" },
  { name: "dv01", source: "greenhouse", token: "dv01" },
  { name: "Echo", source: "ashby", token: "echo" },
  { name: "Ellipsislabs", source: "ashby", token: "ellipsislabs" },
  { name: "Elwood Technologies", source: "greenhouse", token: "elwoodtechnologies" },
  { name: "EMARKETER", source: "greenhouse", token: "emarketer" },
  { name: "Emburse", source: "lever", token: "emburse" },
  { name: "Epic Kids Inc.", source: "greenhouse", token: "epickids" },
  { name: "Espa", source: "ashby", token: "espa" },
  { name: "Eternal", source: "lever", token: "eternal" },
  { name: "Eulerity", source: "greenhouse", token: "eulerity" },
  { name: "Evolver", source: "greenhouse", token: "evolver" },
  { name: "Evry Health", source: "lever", token: "evry-health" },
  { name: "F. Schumacher & Co.", source: "greenhouse", token: "fschumacherco" },
  { name: "Fable", source: "ashby", token: "fable" },
  { name: "Fetch", source: "greenhouse", token: "fetch" },
  { name: "Finary", source: "ashby", token: "finary" },
  { name: "firsthand Health", source: "greenhouse", token: "firsthand" },
  { name: "Flagright Com", source: "ashby", token: "flagright.com" },
  { name: "Flashpoint Io", source: "ashby", token: "flashpoint.io" },
  { name: "Flip", source: "greenhouse", token: "flip" },
  { name: "Float", source: "ashby", token: "float" },
  { name: "Flux", source: "ashby", token: "flux" },
  { name: "Fluxergy 2", source: "lever", token: "fluxergy-2" },
  { name: "Freedom Technology Solutions Group", source: "greenhouse", token: "freedomconsulting" },
  { name: "Fulcrum", source: "ashby", token: "fulcrum" },
  { name: "Fuse", source: "ashby", token: "fuse" },
  { name: "Galaxy Integrated Technologies", source: "greenhouse", token: "galaxy" },
  { name: "Gen Digital", source: "ashby", token: "gen-digital" },
  { name: "Genbio", source: "lever", token: "genbio" },
  { name: "Geneva Trading", source: "greenhouse", token: "genevatrading" },
  { name: "GenScript/ProBio", source: "greenhouse", token: "genscript" },
  { name: "Gigaml", source: "ashby", token: "gigaml" },
  { name: "Glade", source: "ashby", token: "glade" },
  { name: "Glimpse", source: "ashby", token: "glimpse" },
  { name: "Grai", source: "ashby", token: "grai" },
  { name: "GRIN", source: "greenhouse", token: "grin" },
  { name: "Groww", source: "greenhouse", token: "groww" },
  { name: "Hadrian Automation", source: "ashby", token: "hadrian-automation" },
  { name: "Handshake", source: "ashby", token: "handshake" },
  { name: "Hatch", source: "ashby", token: "hatch" },
  { name: "Headstart", source: "ashby", token: "headstart" },
  { name: "Hexa", source: "ashby", token: "hexa" },
  { name: "Hiverge", source: "ashby", token: "hiverge" },
  { name: "Honeydew", source: "ashby", token: "honeydew" },
  { name: "Hush", source: "lever", token: "hush" },
  { name: "Hypercore", source: "ashby", token: "hypercore" },
  { name: "Icon", source: "ashby", token: "icon" },
  { name: "Ifm Us", source: "lever", token: "ifm-us" },
  { name: "iHerb", source: "greenhouse", token: "iherb" },
  { name: "Infera", source: "ashby", token: "infera" },
  { name: "Innate", source: "ashby", token: "innate" },
  { name: "Instead", source: "greenhouse", token: "instead" },
  { name: "ion design", source: "lever", token: "ion" },
  { name: "iSpot", source: "greenhouse", token: "ispottv" },
  { name: "Journey", source: "greenhouse", token: "journey" },
  { name: "Kensington", source: "greenhouse", token: "kensingtontours" },
  { name: "Kos Ai", source: "ashby", token: "kos.ai" },
  { name: "Kustomer", source: "ashby", token: "kustomer" },
  { name: "Lambda", source: "ashby", token: "lambda" },
  { name: "Langfuse", source: "ashby", token: "langfuse" },
  { name: "Later", source: "greenhouse", token: "later" },
  { name: "Latitudeinc", source: "lever", token: "latitudeinc" },
  { name: "Layup", source: "lever", token: "layup" },
  { name: "Level", source: "ashby", token: "level" },
  { name: "Lexical", source: "bamboohr", token: "lexical" },
  { name: "Lightfield", source: "ashby", token: "Lightfield" },
  { name: "Lila Sciences", source: "greenhouse", token: "lilasciences" },
  { name: "Lingo.dev", source: "ashby", token: "lingodotdev" },
  { name: "Liquid", source: "ashby", token: "liquid" },
  { name: "Lucid Motors", source: "greenhouse", token: "lucidmotors" },
  { name: "Mable", source: "lever", token: "mable" },
  { name: "Maven", source: "ashby", token: "maven" },
  { name: "Maxima", source: "ashby", token: "maxima" },
  { name: "Meesho", source: "lever", token: "meesho" },
  { name: "Melotech", source: "ashby", token: "melotech" },
  { name: "Mercator", source: "ashby", token: "mercator" },
  { name: "Meshy", source: "ashby", token: "meshy" },
  { name: "Mirage", source: "ashby", token: "mirage" },
  { name: "Modus", source: "ashby", token: "modus" },
  { name: "Momentus Space LLC", source: "greenhouse", token: "momentus" },
  { name: "mthree Recruiting Portal", source: "greenhouse", token: "mthreerecruitingportal" },
  { name: "Multiverse", source: "ashby", token: "multiverse" },
  { name: "N1", source: "ashby", token: "n1" },
  { name: "Nabla Bio", source: "ashby", token: "nabla" },
  { name: "Neuralink", source: "greenhouse", token: "neuralink" },
  { name: "NewsBreak", source: "greenhouse", token: "newsbreak" },
  { name: "Nexus", source: "ashby", token: "agent" },
  { name: "Niural", source: "ashby", token: "niural" },
  { name: "Northslope Technologies", source: "ashby", token: "northslope-technologies" },
  { name: "NorthwoodSpace", source: "ashby", token: "NorthwoodSpace" },
  { name: "Novelcare", source: "ashby", token: "novel" },
  { name: "NPX", source: "ashby", token: "NPX" },
  { name: "Odin", source: "ashby", token: "odin" },
  { name: "OfferUp", source: "greenhouse", token: "offerup" },
  { name: "Oklo", source: "greenhouse", token: "oklo" },
  { name: "Ollama", source: "ashby", token: "ollama" },
  { name: "Omni", source: "ashby", token: "omni" },
  { name: "OpenProse", source: "ashby", token: "prose" },
  { name: "PagerDuty", source: "greenhouse", token: "pagerduty" },
  { name: "Pantheon Systems, Inc", source: "greenhouse", token: "pantheon" },
  { name: "Pearl", source: "ashby", token: "pearl" },
  { name: "People Culture Talent", source: "ashby", token: "people-culture-talent" },
  { name: "Periodic Labs", source: "ashby", token: "periodic-labs" },
  { name: "Perpay", source: "greenhouse", token: "perpay" },
  { name: "Phamily", source: "greenhouse", token: "jobsatphamily" },
  { name: "Phonic", source: "ashby", token: "phonic" },
  { name: "Ping Identity", source: "greenhouse", token: "pingidentity" },
  { name: "Pingwind", source: "lever", token: "pingwind" },
  { name: "Playground", source: "ashby", token: "playground" },
  { name: "PlayStation Global", source: "greenhouse", token: "sonyinteractiveentertainmentglobal" },
  { name: "PLS", source: "greenhouse", token: "plscareers" },
  { name: "Plume", source: "greenhouse", token: "plume" },
  { name: "Plus 2", source: "lever", token: "plus-2" },
  { name: "Podium", source: "greenhouse", token: "podium81" },
  { name: "Pony Dot Ai", source: "workable", token: "pony-dot-ai" },
  { name: "Post.fm", source: "ashby", token: "post" },
  { name: "POWERX", source: "greenhouse", token: "powerx" },
  { name: "Preference Model", source: "ashby", token: "Preference-Model" },
  { name: "Primer", source: "ashby", token: "primer" },
  { name: "Prompt", source: "ashby", token: "prompt" },
  { name: "Proper", source: "lever", token: "proper" },
  { name: "Pulse Healthcare", source: "greenhouse", token: "pulse" },
  { name: "Pursuit", source: "greenhouse", token: "pursuit" },
  { name: "Pylon Labs", source: "ashby", token: "pylon-labs" },
  { name: "Quadric Dot I O Inc", source: "workable", token: "quadric-dot-i-o-inc" },
  { name: "QuEra Computing, Inc.", source: "greenhouse", token: "queracomputinginc" },
  { name: "Queue", source: "ashby", token: "queue" },
  { name: "Quora", source: "ashby", token: "quora" },
  { name: "Realm", source: "greenhouse", token: "realm" },
  { name: "Realmalliance", source: "ashby", token: "realmalliance" },
  { name: "Remarcable Inc", source: "ashby", token: "remarcable-inc" },
  { name: "Reply", source: "lever", token: "reply" },
  { name: "Retrofit Technology", source: "greenhouse", token: "retrofit" },
  { name: "Revel", source: "ashby", token: "revel" },
  { name: "Revi", source: "lever", token: "revi" },
  { name: "Rigetti Computing", source: "lever", token: "rigetti" },
  { name: "Rivet", source: "ashby", token: "rivet" },
  { name: "RoadRunner Recycling Inc.", source: "greenhouse", token: "roadrunner" },
  { name: "Rocket Money", source: "greenhouse", token: "truebill" },
  { name: "Rokt", source: "workable", token: "rokt" },
  { name: "Sable", source: "ashby", token: "sable" },
  { name: "Scout AI", source: "greenhouse", token: "scoutai" },
  { name: "Scout24", source: "greenhouse", token: "scout24" },
  { name: "Scribe", source: "ashby", token: "scribe" },
  { name: "Seed", source: "greenhouse", token: "seed" },
  { name: "Seesaw", source: "greenhouse", token: "seesaw" },
  { name: "Sensei Wellness Holdings Inc.,", source: "greenhouse", token: "sensei" },
  { name: "Sentilink", source: "ashby", token: "sentilink" },
  { name: "Sezzle", source: "greenhouse", token: "sezzle" },
  { name: "SHEIN", source: "greenhouse", token: "shein" },
  { name: "Sigma Computing", source: "greenhouse", token: "sigmacomputing" },
  { name: "Sila", source: "lever", token: "sila" },
  { name: "Silver", source: "ashby", token: "silver" },
  { name: "SimpliSafe", source: "greenhouse", token: "simplisafe" },
  { name: "Skio", source: "lever", token: "skio" },
  { name: "Skip", source: "ashby", token: "skip" },
  { name: "SkyLink", source: "ashby", token: "skylink" },
  { name: "Snowflake", source: "ashby", token: "snowflake" },
  { name: "Solink", source: "ashby", token: "solink" },
  { name: "Spotlight Realty", source: "ashby", token: "spotlight" },
  { name: "SQUAD", source: "greenhouse", token: "squad" },
  { name: "Stellar", source: "ashby", token: "stellar" },
  { name: "Symphony Communication Services", source: "greenhouse", token: "symphony" },
  { name: "Syncro", source: "greenhouse", token: "syncro" },
  { name: "Teamworks", source: "ashby", token: "teamworks" },
  { name: "Technergetics", source: "greenhouse", token: "technergetics" },
  { name: "Teleo", source: "lever", token: "teleo" },
  { name: "Tenstorrent University", source: "greenhouse", token: "tenstorrentuniversity" },
  { name: "The Athletic", source: "lever", token: "theathletic" },
  { name: "The Nuclear Company", source: "greenhouse", token: "thenuclearcompany" },
  { name: "The Token Company", source: "ashby", token: "the-token-company" },
  { name: "Tilt", source: "ashby", token: "tilt" },
  { name: "Titan Msp", source: "ashby", token: "titan-msp" },
  { name: "Torc Robotics", source: "greenhouse", token: "torcrobotics" },
  { name: "Tracebit", source: "ashby", token: "tracebit" },
  { name: "TransMarket Group", source: "greenhouse", token: "transmarketgroup" },
  { name: "Tri", source: "lever", token: "tri" },
  { name: "TribalScale", source: "greenhouse", token: "tribalscale" },
  { name: "Trident", source: "greenhouse", token: "trident" },
  { name: "True Anomaly", source: "greenhouse", token: "trueanomalyinc" },
  { name: "Twitch", source: "greenhouse", token: "twitch" },
  { name: "Uare.ai", source: "greenhouse", token: "uareai" },
  { name: "Uber Freight", source: "greenhouse", token: "uberfreight" },
  { name: "Uiflow", source: "ashby", token: "ycombinator" },
  { name: "Uncountable", source: "ashby", token: "uncountable" },
  { name: "Understood Care", source: "greenhouse", token: "understoodcare" },
  { name: "Unify", source: "lever", token: "unify" },
  { name: "UpKeep", source: "greenhouse", token: "upkeep" },
  { name: "Veriff", source: "greenhouse", token: "veriff" },
  { name: "Vibe", source: "ashby", token: "vibe" },
  { name: "Wealth Com", source: "ashby", token: "wealth-com" },
  { name: "Weave", source: "greenhouse", token: "weave" },
  { name: "Whoop", source: "lever", token: "whoop" },
  { name: "Wonderschool", source: "greenhouse", token: "wonderschool" },
  { name: "World Surf League", source: "greenhouse", token: "worldsurfleague" },
  { name: "Wyetechllc", source: "lever", token: "wyetechllc" },
  { name: "XPENG", source: "greenhouse", token: "xpengmotors" },
  { name: "Yotta", source: "ashby", token: "yotta" },
  { name: "Zencoder", source: "greenhouse", token: "zencoder" },
  // Mass discovery (YC directory sweep, 2026-07-11): 415 boards.
  // Greenhouse names come from the vendor's own board meta (collision-proof).
  { name: "Abacum", source: "ashby", token: "abacum" },
  { name: "Abstra", source: "bamboohr", token: "abstra" },
  { name: "Abundant", source: "ashby", token: "abundant" },
  { name: "Accord", source: "ashby", token: "accord" },
  { name: "ACLU - National Office", source: "greenhouse", token: "aclu" },
  { name: "Adaptyv", source: "ashby", token: "adaptyv" },
  { name: "AfterQuery", source: "ashby", token: "afterquery" },
  { name: "AgentMail", source: "ashby", token: "agentmail" },
  { name: "AIOS", source: "ashby", token: "aios" },
  { name: "AiPrise", source: "ashby", token: "aiprise" },
  { name: "Airbyte", source: "ashby", token: "airbyte" },
  { name: "Albedo", source: "greenhouse", token: "albedo" },
  { name: "Alchemy", source: "ashby", token: "alchemy" },
  { name: "Aleph", source: "lever", token: "aleph" },
  { name: "Algolia", source: "greenhouse", token: "algolia" },
  { name: "Alpaca", source: "greenhouse", token: "alpaca" },
  { name: "Anara", source: "ashby", token: "anara" },
  { name: "Anima", source: "ashby", token: "anima" },
  { name: "Anthrogen", source: "ashby", token: "anthrogen" },
  { name: "Apolink", source: "ashby", token: "apolink" },
  { name: "Arketa", source: "ashby", token: "arketa" },
  { name: "ARQ", source: "ashby", token: "arq" },
  { name: "Artie", source: "ashby", token: "artie" },
  { name: "Artisan", source: "ashby", token: "artisan" },
  { name: "Asimov", source: "ashby", token: "asimov" },
  { name: "Aspora", source: "ashby", token: "aspora" },
  { name: "Assembly", source: "ashby", token: "assembly" },
  { name: "AssemblyAI", source: "greenhouse", token: "assemblyai" },
  { name: "Astro Mechanica", source: "ashby", token: "astro-mechanica" },
  { name: "Atlas", source: "ashby", token: "atlas" },
  { name: "AtoB", source: "ashby", token: "atob" },
  { name: "Atomic", source: "ashby", token: "atomic" },
  { name: "Attain", source: "greenhouse", token: "attain" },
  { name: "Attune", source: "bamboohr", token: "attune" },
  { name: "Auctor", source: "ashby", token: "auctor" },
  { name: "Aurelian", source: "ashby", token: "aurelian" },
  { name: "authzed", source: "ashby", token: "authzed" },
  { name: "Automat", source: "ashby", token: "automat" },
  { name: "Aviator", source: "ashby", token: "aviator" },
  { name: "Avoca", source: "ashby", token: "avoca" },
  { name: "Axiom", source: "greenhouse", token: "axiom" },
  { name: "Axle", source: "greenhouse", token: "axle" },
  { name: "Axle Health", source: "ashby", token: "axle-health" },
  { name: "Bankjoy", source: "ashby", token: "bankjoy" },
  { name: "Belvo", source: "ashby", token: "belvo" },
  { name: "Benchling", source: "ashby", token: "benchling" },
  { name: "Benepass", source: "ashby", token: "benepass" },
  { name: "Bird", source: "greenhouse", token: "bird" },
  { name: "Bitmovin", source: "greenhouse", token: "bitmovin" },
  { name: "Bitrise", source: "bamboohr", token: "bitrise" },
  { name: "Bitstack", source: "ashby", token: "bitstack" },
  { name: "Blacksmith", source: "ashby", token: "blacksmith" },
  { name: "Blaxel", source: "ashby", token: "blaxel" },
  { name: "Blee", source: "ashby", token: "blee" },
  { name: "Blissway", source: "ashby", token: "blissway" },
  { name: "Boom", source: "ashby", token: "boom" },
  { name: "Bree", source: "ashby", token: "bree" },
  { name: "Bridge to Enter Advanced Mathematics (BEAM)", source: "greenhouse", token: "beam" },
  { name: "Bud", source: "bamboohr", token: "bud" },
  { name: "Cambly", source: "ashby", token: "cambly" },
  { name: "CaptivateIQ", source: "lever", token: "captivateiq" },
  { name: "CarbonChain", source: "greenhouse", token: "carbonchain" },
  { name: "Cardboard", source: "ashby", token: "cardboard" },
  { name: "CareMessage", source: "lever", token: "caremessage" },
  { name: "Caribou Financial", source: "greenhouse", token: "caribou" },
  { name: "Casca", source: "ashby", token: "casca" },
  { name: "Centralize", source: "ashby", token: "centralize" },
  { name: "Charge Robotics", source: "ashby", token: "charge-robotics" },
  { name: "Chestnut", source: "ashby", token: "chestnut" },
  { name: "Chowdeck", source: "bamboohr", token: "chowdeck" },
  { name: "Circleback", source: "ashby", token: "circleback" },
  { name: "CircuitHub", source: "ashby", token: "circuithub" },
  { name: "Claim Health", source: "ashby", token: "claim-health" },
  { name: "ClaimSorted", source: "ashby", token: "claimsorted" },
  { name: "Clarion", source: "ashby", token: "clarion" },
  { name: "ClassDojo", source: "ashby", token: "classdojo" },
  { name: "Clearly AI", source: "ashby", token: "clearly-ai" },
  { name: "Clipboard", source: "ashby", token: "clipboard" },
  { name: "Close", source: "ashby", token: "close" },
  { name: "Coast", source: "greenhouse", token: "coast" },
  { name: "Codes Health", source: "ashby", token: "codes-health" },
  { name: "Comena", source: "ashby", token: "comena" },
  { name: "Complete", source: "ashby", token: "complete" },
  { name: "Concourse", source: "ashby", token: "concourse" },
  { name: "Conductor", source: "ashby", token: "conductor" },
  { name: "Confido", source: "ashby", token: "confido" },
  { name: "Conveo", source: "ashby", token: "conveo" },
  { name: "Copia", source: "lever", token: "copia" },
  { name: "Cortex", source: "greenhouse", token: "cortex" },
  { name: "Corvus Robotics", source: "ashby", token: "corvus-robotics" },
  { name: "CTGT", source: "ashby", token: "ctgt" },
  { name: "Cua", source: "bamboohr", token: "cua" },
  { name: "Curri", source: "ashby", token: "curri" },
  { name: "Datafold", source: "ashby", token: "datafold" },
  { name: "Dataleap", source: "ashby", token: "dataleap" },
  { name: "David AI", source: "ashby", token: "david-ai" },
  { name: "Dedalus Labs", source: "ashby", token: "dedalus-labs" },
  { name: "Deepgram", source: "ashby", token: "deepgram" },
  { name: "Deepnote", source: "ashby", token: "deepnote" },
  { name: "Dex", source: "ashby", token: "dex" },
  { name: "Diligent Services", source: "greenhouse", token: "diligent" },
  { name: "Dispatch", source: "ashby", token: "dispatch" },
  { name: "Distro", source: "lever", token: "distro" },
  { name: "Ditto", source: "ashby", token: "ditto" },
  { name: "doola", source: "lever", token: "doola" },
  { name: "Doppler", source: "ashby", token: "doppler" },
  { name: "Duffel", source: "lever", token: "duffel" },
  { name: "Ekho", source: "ashby", token: "ekho" },
  { name: "Ello", source: "ashby", token: "ello" },
  { name: "Embrace", source: "greenhouse", token: "embrace" },
  { name: "Encord", source: "ashby", token: "encord" },
  { name: "Enode", source: "ashby", token: "enode" },
  { name: "Enveritas", source: "greenhouse", token: "enveritas" },
  { name: "Escape", source: "ashby", token: "escape" },
  { name: "Eventual", source: "ashby", token: "eventual" },
  { name: "Exa", source: "ashby", token: "exa" },
  { name: "Extend", source: "greenhouse", token: "extend" },
  { name: "FamPay", source: "lever", token: "fampay" },
  { name: "Fieldguide", source: "ashby", token: "fieldguide" },
  { name: "Finch", source: "lever", token: "finch" },
  { name: "Finni Health", source: "ashby", token: "finni-health" },
  { name: "Finvest", source: "ashby", token: "finvest" },
  { name: "Firecrawl", source: "ashby", token: "firecrawl" },
  { name: "Fivetran", source: "greenhouse", token: "fivetran" },
  { name: "Flai", source: "ashby", token: "flai" },
  { name: "Fleek", source: "ashby", token: "fleek" },
  { name: "Fleetline", source: "ashby", token: "fleetline" },
  { name: "FleetWorks", source: "ashby", token: "fleetworks" },
  { name: "Fleetzero", source: "lever", token: "fleetzero" },
  { name: "Flex", source: "greenhouse", token: "flex" },
  { name: "Flint", source: "ashby", token: "flint" },
  { name: "Flo", source: "bamboohr", token: "flo" },
  { name: "FlutterFlow", source: "ashby", token: "flutterflow" },
  { name: "Formal", source: "ashby", token: "formal" },
  { name: "Formance", source: "ashby", token: "formance" },
  { name: "Fresco", source: "bamboohr", token: "fresco" },
  { name: "FurtherAI", source: "ashby", token: "furtherai" },
  { name: "Gecko Robotics", source: "ashby", token: "gecko-robotics" },
  { name: "Gigs", source: "greenhouse", token: "gigs" },
  { name: "GiveCampus", source: "greenhouse", token: "givecampus" },
  { name: "Glide", source: "lever", token: "glide" },
  { name: "GoCardless", source: "greenhouse", token: "gocardless" },
  { name: "GoLinks", source: "ashby", token: "golinks" },
  { name: "GovDash", source: "ashby", token: "govdash" },
  { name: "Greenboard", source: "ashby", token: "greenboard" },
  { name: "Greptile", source: "ashby", token: "greptile" },
  { name: "GREY", source: "greenhouse", token: "grey" },
  { name: "Gridware", source: "lever", token: "gridware" },
  { name: "Gumloop", source: "ashby", token: "gumloop" },
  { name: "H1", source: "lever", token: "h1" },
  { name: "H3X Technologies", source: "ashby", token: "h3x-technologies" },
  { name: "HackerRank", source: "greenhouse", token: "hackerrank" },
  { name: "Handoff", source: "lever", token: "handoff" },
  { name: "Happl", source: "ashby", token: "happl" },
  { name: "Haven Interactive Studios", source: "greenhouse", token: "haven" },
  { name: "HealthSherpa", source: "ashby", token: "healthsherpa" },
  { name: "Healthtech 1", source: "ashby", token: "healthtech-1" },
  { name: "Hightouch", source: "greenhouse", token: "hightouch" },
  { name: "Hive", source: "greenhouse", token: "hive" },
  { name: "HockeyStack", source: "ashby", token: "hockeystack" },
  { name: "Homebase", source: "ashby", token: "homebase" },
  { name: "hud", source: "ashby", token: "hud" },
  { name: "Hudu", source: "ashby", token: "hudu" },
  { name: "Humaans", source: "ashby", token: "humaans" },
  { name: "Humanly", source: "ashby", token: "humanly" },
  { name: "Hyperbound", source: "ashby", token: "hyperbound" },
  { name: "Icarus", source: "greenhouse", token: "icarus" },
  { name: "Idler", source: "ashby", token: "idler" },
  { name: "Infinite", source: "ashby", token: "infinite" },
  { name: "Infisical", source: "ashby", token: "infisical" },
  { name: "Inkeep", source: "ashby", token: "inkeep" },
  { name: "Instawork", source: "greenhouse", token: "instawork" },
  { name: "Invert", source: "ashby", token: "invert" },
  { name: "Invopop", source: "ashby", token: "invopop" },
  { name: "Juicebox", source: "ashby", token: "juicebox" },
  { name: "Julius", source: "ashby", token: "julius" },
  { name: "Junction", source: "ashby", token: "junction" },
  { name: "Kalshi", source: "greenhouse", token: "kalshi" },
  { name: "Kastle", source: "ashby", token: "kastle" },
  { name: "Kingdom", source: "ashby", token: "kingdom" },
  { name: "Knowtex", source: "ashby", token: "knowtex" },
  { name: "Kodex", source: "ashby", token: "kodex" },
  { name: "Kombo", source: "ashby", token: "kombo" },
  { name: "Lago", source: "ashby", token: "lago" },
  { name: "LAIKA", source: "greenhouse", token: "laika" },
  { name: "Lance", source: "ashby", token: "lance" },
  { name: "LanceDB", source: "ashby", token: "lancedb" },
  { name: "Langdock", source: "ashby", token: "langdock" },
  { name: "Latent", source: "ashby", token: "latent" },
  { name: "Legacy", source: "bamboohr", token: "legacy" },
  { name: "Legalist", source: "greenhouse", token: "legalist" },
  { name: "Legora", source: "ashby", token: "legora" },
  { name: "LemFi", source: "ashby", token: "lemfi" },
  { name: "Lio (formerly askLio)", source: "ashby", token: "lio" },
  { name: "LiteLLM", source: "ashby", token: "litellm" },
  { name: "LiveFlow", source: "ashby", token: "liveflow" },
  { name: "Lob", source: "greenhouse", token: "lob" },
  { name: "Loula", source: "ashby", token: "loula" },
  { name: "Lucis", source: "ashby", token: "lucis" },
  { name: "Luminai", source: "ashby", token: "luminai" },
  { name: "Mach9", source: "ashby", token: "mach9" },
  { name: "Magnetic", source: "bamboohr", token: "magnetic" },
  { name: "Mantis", source: "greenhouse", token: "mantis" },
  { name: "MarqVision", source: "greenhouse", token: "marqvision" },
  { name: "Mashgin", source: "lever", token: "mashgin" },
  { name: "Mastra", source: "ashby", token: "mastra" },
  { name: "Mattermost", source: "greenhouse", token: "mattermost" },
  { name: "MaverickX", source: "lever", token: "maverickx" },
  { name: "Meadow", source: "ashby", token: "meadow" },
  { name: "Mednet", source: "ashby", token: "mednet" },
  { name: "Mercura", source: "ashby", token: "mercura" },
  { name: "Meridial", source: "greenhouse", token: "agency" },
  { name: "Mesh", source: "greenhouse", token: "mesh" },
  { name: "Meticulous", source: "ashby", token: "meticulous" },
  { name: "Metriport", source: "ashby", token: "metriport" },
  { name: "Middesk", source: "ashby", token: "middesk" },
  { name: "Minerva", source: "ashby", token: "minerva" },
  { name: "Mintlify", source: "ashby", token: "mintlify" },
  { name: "Miso", source: "ashby", token: "miso" },
  { name: "Mixpanel", source: "greenhouse", token: "mixpanel" },
  { name: "Momentic Studios", source: "greenhouse", token: "momentic" },
  { name: "Moss", source: "ashby", token: "moss" },
  { name: "Mutiny", source: "ashby", token: "mutiny" },
  { name: "NABIS", source: "greenhouse", token: "nabis" },
  { name: "Nanonets", source: "greenhouse", token: "nanonets" },
  { name: "Nash", source: "ashby", token: "nash" },
  { name: "Nectar", source: "bamboohr", token: "nectar" },
  { name: "Netomi", source: "lever", token: "netomi" },
  { name: "New Story", source: "ashby", token: "new-story" },
  { name: "Newton", source: "lever", token: "newton" },
  { name: "NimbleRx", source: "lever", token: "nimblerx" },
  { name: "Notabene", source: "ashby", token: "notabene" },
  { name: "Nourish", source: "bamboohr", token: "nourish" },
  { name: "Novig", source: "ashby", token: "novig" },
  { name: "Nox Metals", source: "ashby", token: "nox-metals" },
  { name: "Numeral", source: "ashby", token: "numeral" },
  { name: "Odeko", source: "greenhouse", token: "odeko" },
  { name: "Odys Aviation", source: "ashby", token: "odys-aviation" },
  { name: "OffDeal", source: "ashby", token: "offdeal" },
  { name: "Onebrief", source: "ashby", token: "onebrief" },
  { name: "Oneleet", source: "ashby", token: "oneleet" },
  { name: "OneSchema", source: "ashby", token: "oneschema" },
  { name: "Onshore", source: "greenhouse", token: "onshore" },
  { name: "Onyx", source: "ashby", token: "onyx" },
  { name: "Opencall", source: "ashby", token: "opencall" },
  { name: "OpenSea", source: "ashby", token: "opensea" },
  { name: "Openwork", source: "greenhouse", token: "openwork" },
  { name: "Ophelia", source: "greenhouse", token: "ophelia" },
  { name: "Osmosis", source: "greenhouse", token: "osmosis" },
  { name: "Output Biosciences", source: "ashby", token: "output" },
  { name: "Outset", source: "ashby", token: "outset" },
  { name: "Overview", source: "ashby", token: "overview" },
  { name: "Padlet", source: "ashby", token: "padlet" },
  { name: "Papa", source: "greenhouse", token: "papa" },
  { name: "Paradigm", source: "ashby", token: "paradigm" },
  { name: "Paragon", source: "bamboohr", token: "paragon" },
  { name: "Parallel Bio", source: "ashby", token: "parallel-bio" },
  { name: "Parallel Systems", source: "greenhouse", token: "parallel" },
  { name: "Parker", source: "ashby", token: "parker" },
  { name: "Parrot", source: "bamboohr", token: "parrot" },
  { name: "Pelago", source: "greenhouse", token: "pelago" },
  { name: "People.ai", source: "lever", token: "people-ai" },
  { name: "PermitFlow", source: "ashby", token: "permitflow" },
  { name: "Permutive", source: "ashby", token: "permutive" },
  { name: "Phoenix", source: "ashby", token: "phoenix" },
  { name: "Phonely", source: "ashby", token: "phonely" },
  { name: "Photoroom", source: "ashby", token: "photoroom" },
  { name: "Pirros", source: "ashby", token: "pirros" },
  { name: "Plane", source: "ashby", token: "plane" },
  { name: "PointOne", source: "ashby", token: "pointone" },
  { name: "Polymath", source: "ashby", token: "polymath" },
  { name: "Popl", source: "ashby", token: "popl" },
  { name: "Porter", source: "lever", token: "porter" },
  { name: "Posh", source: "ashby", token: "posh" },
  { name: "Postscript", source: "greenhouse", token: "postscript" },
  { name: "PowerUs", source: "ashby", token: "powerus" },
  { name: "Prodigal", source: "greenhouse", token: "prodigal" },
  { name: "Prolific", source: "greenhouse", token: "prolific" },
  { name: "Promise", source: "ashby", token: "promise" },
  { name: "Pronto", source: "greenhouse", token: "pronto" },
  { name: "Prospa", source: "greenhouse", token: "prospa" },
  { name: "Prosper", source: "lever", token: "prosper" },
  { name: "Prox", source: "ashby", token: "prox" },
  { name: "Pure", source: "ashby", token: "pure" },
  { name: "Pyka", source: "lever", token: "pyka" },
  { name: "Pylon", source: "ashby", token: "pylon" },
  { name: "Quartzy", source: "lever", token: "quartzy" },
  { name: "Quicknode", source: "ashby", token: "quicknode" },
  { name: "Quindar", source: "ashby", token: "quindar" },
  { name: "Qventus", source: "greenhouse", token: "qventus" },
  { name: "RADAR", source: "greenhouse", token: "radar" },
  { name: "Raindrop", source: "bamboohr", token: "raindrop" },
  { name: "Raven", source: "greenhouse", token: "raven" },
  { name: "Reacher", source: "ashby", token: "reacher" },
  { name: "ReadMe", source: "ashby", token: "readme" },
  { name: "Ready", source: "ashby", token: "ready" },
  { name: "Recidiviz", source: "greenhouse", token: "recidiviz" },
  { name: "Redbird", source: "bamboohr", token: "redbird" },
  { name: "Reducto", source: "ashby", token: "reducto" },
  { name: "Reflex", source: "greenhouse", token: "reflex" },
  { name: "Regent", source: "greenhouse", token: "regent" },
  { name: "Relace", source: "ashby", token: "relace" },
  { name: "Remi", source: "bamboohr", token: "remi" },
  { name: "Replo", source: "ashby", token: "replo" },
  { name: "Rescale", source: "ashby", token: "rescale" },
  { name: "Resend", source: "ashby", token: "resend" },
  { name: "Retell AI", source: "ashby", token: "retell-ai" },
  { name: "RevenueCat", source: "ashby", token: "revenuecat" },
  { name: "Roboflow", source: "ashby", token: "roboflow" },
  { name: "Roofr", source: "greenhouse", token: "roofr" },
  { name: "Runway", source: "ashby", token: "runway" },
  { name: "SafetyKit", source: "ashby", token: "safetykit" },
  { name: "Sage Care", source: "ashby", token: "sagecare" },
  { name: "SalesPatriot", source: "ashby", token: "salespatriot" },
  { name: "Salient", source: "ashby", token: "salient" },
  { name: "Saturn", source: "ashby", token: "saturn" },
  { name: "Sazabi", source: "ashby", token: "sazabi" },
  { name: "Sendbird", source: "greenhouse", token: "sendbird" },
  { name: "SF Tensor", source: "ashby", token: "sf-tensor" },
  { name: "Shadeform", source: "ashby", token: "shadeform" },
  { name: "Shasqi", source: "ashby", token: "shasqi" },
  { name: "Shepherd", source: "ashby", token: "shepherd" },
  { name: "Sieve", source: "ashby", token: "sieve" },
  { name: "Sift", source: "ashby", token: "sift" },
  { name: "SigNoz", source: "ashby", token: "signoz" },
  { name: "Sim", source: "ashby", token: "sim" },
  { name: "Simetrik", source: "bamboohr", token: "simetrik" },
  { name: "Simple AI", source: "ashby", token: "simple-ai" },
  { name: "SIRUM", source: "greenhouse", token: "sirum" },
  { name: "SkydropX", source: "ashby", token: "skydropx" },
  { name: "Skyways", source: "lever", token: "skyways" },
  { name: "Slite", source: "bamboohr", token: "slite" },
  { name: "Slope", source: "ashby", token: "slope" },
  { name: "SmartAsset", source: "greenhouse", token: "smartasset" },
  { name: "Snapdocs", source: "ashby", token: "snapdocs" },
  { name: "SnapMagic", source: "ashby", token: "snapmagic" },
  { name: "Snappr", source: "lever", token: "snappr" },
  { name: "Sola", source: "ashby", token: "sola" },
  { name: "Solidroad", source: "ashby", token: "solidroad" },
  { name: "Solva", source: "ashby", token: "solva" },
  { name: "Spade", source: "ashby", token: "spade" },
  { name: "Spark", source: "bamboohr", token: "spark" },
  { name: "Speak", source: "ashby", token: "speak" },
  { name: "Spellbrush", source: "ashby", token: "spellbrush" },
  { name: "Sphere", source: "ashby", token: "sphere" },
  { name: "Sphinx", source: "ashby", token: "sphinx" },
  { name: "SpruceID", source: "ashby", token: "spruceid" },
  { name: "Stable", source: "ashby", token: "stable" },
  { name: "Starcloud", source: "greenhouse", token: "starcloud" },
  { name: "Stepful", source: "ashby", token: "stepful" },
  { name: "Stilta", source: "ashby", token: "stilta" },
  { name: "Stream", source: "ashby", token: "stream" },
  { name: "Submittable", source: "greenhouse", token: "submittable" },
  { name: "Subsets", source: "ashby", token: "subsets" },
  { name: "Substack", source: "ashby", token: "substack" },
  { name: "Substrate", source: "ashby", token: "substrate" },
  { name: "Suger", source: "lever", token: "suger" },
  { name: "Super Technologies", source: "greenhouse", token: "super" },
  { name: "super{set} Hive Community", source: "greenhouse", token: "superset" },
  { name: "Superside", source: "lever", token: "superside" },
  { name: "Svix", source: "ashby", token: "svix" },
  { name: "Swayable", source: "greenhouse", token: "swayable" },
  { name: "Sweep", source: "ashby", token: "sweep" },
  { name: "Switchboard", source: "ashby", token: "switchboard" },
  { name: "Sygaldry Technologies", source: "ashby", token: "sygaldry-technologies" },
  { name: "Synapticure", source: "lever", token: "synapticure" },
  { name: "Tailor", source: "ashby", token: "tailor" },
  { name: "Tajir", source: "ashby", token: "tajir" },
  { name: "Taktile", source: "ashby", token: "taktile" },
  { name: "Tavus", source: "ashby", token: "tavus" },
  { name: "telli", source: "ashby", token: "telli" },
  { name: "Tempo", source: "greenhouse", token: "tempo" },
  { name: "Tendo", source: "lever", token: "tendo" },
  { name: "Tennr", source: "ashby", token: "tennr" },
  { name: "Terminal", source: "ashby", token: "terminal" },
  { name: "Thera", source: "ashby", token: "thera" },
  { name: "Thndr", source: "ashby", token: "thndr" },
  { name: "Thunkable", source: "lever", token: "thunkable" },
  { name: "Titan", source: "ashby", token: "titan" },
  { name: "Toku", source: "ashby", token: "toku" },
  { name: "Topline Pro", source: "ashby", token: "topline-pro" },
  { name: "Tovala", source: "lever", token: "tovala" },
  { name: "Tractian", source: "lever", token: "tractian" },
  { name: "Tremendous", source: "ashby", token: "tremendous" },
  { name: "Triomics", source: "ashby", token: "triomics" },
  { name: "TRM Labs", source: "ashby", token: "trm-labs" },
  { name: "truthsystems", source: "ashby", token: "truthsystems" },
  { name: "Turion Space", source: "ashby", token: "turion-space" },
  { name: "Twenty", source: "ashby", token: "twenty" },
  { name: "Two Dots", source: "ashby", token: "two-dots" },
  { name: "Ultra", source: "ashby", token: "ultra" },
  { name: "Universe", source: "ashby", token: "universe" },
  { name: "Unusual", source: "lever", token: "unusual" },
  { name: "UpCodes", source: "ashby", token: "upcodes" },
  { name: "UpEquity", source: "bamboohr", token: "upequity" },
  { name: "Uplane", source: "ashby", token: "uplane" },
  { name: "Usul", source: "ashby", token: "usul" },
  { name: "Vector", source: "ashby", token: "vector" },
  { name: "Verifiable", source: "lever", token: "verifiable" },
  { name: "Verto", source: "ashby", token: "verto" },
  { name: "Vetcove", source: "ashby", token: "vetcove" },
  { name: "Vitalize", source: "ashby", token: "vitalize" },
  { name: "voize", source: "ashby", token: "voize" },
  { name: "Vooma", source: "ashby", token: "vooma" },
  { name: "Vori", source: "ashby", token: "vori" },
  { name: "Wallbit", source: "ashby", token: "wallbit" },
  { name: "Webflow", source: "greenhouse", token: "webflow" },
  { name: "Windmill", source: "ashby", token: "windmill" },
  { name: "Xendit", source: "greenhouse", token: "xendit" },
  { name: "Zapier", source: "ashby", token: "zapier" },
  { name: "Zeit AI", source: "ashby", token: "zeit-ai" },
  { name: "Zerocater", source: "greenhouse", token: "zerocater" },
  { name: "Ziina", source: "ashby", token: "ziina" },
  { name: "Zip", source: "ashby", token: "zip" },
  { name: "Zippi", source: "lever", token: "zippi" },
  // Sweep #4 (2026-07-11): 35 boards
  { name: "SpaceX", source: "greenhouse", token: "spacex" },
  { name: "Securitas", source: "smartrecruiters", token: "Securitas" },
  { name: "OpenAI", source: "ashby", token: "openai" },
  { name: "ServiceNow", source: "smartrecruiters", token: "ServiceNow" },
  { name: "Rocket Lab", source: "greenhouse", token: "rocketlab" },
  { name: "BetterHelp", source: "greenhouse", token: "betterhelp" },
  { name: "Optiver", source: "greenhouse", token: "optiverus" },
  { name: "IMC Trading", source: "greenhouse", token: "imc" },
  { name: "DRW", source: "greenhouse", token: "drweng" },
  { name: "Sodexo", source: "smartrecruiters", token: "Sodexo" },
  { name: "Vanta", source: "ashby", token: "vanta" },
  { name: "Decagon", source: "ashby", token: "decagon" },
  { name: "Squarepoint", source: "greenhouse", token: "squarepointcapital" },
  { name: "Hudson River Trading", source: "greenhouse", token: "wehrtyou" },
  { name: "Ethos Life", source: "greenhouse", token: "ethoslife" },
  { name: "Suno", source: "ashby", token: "suno" },
  { name: "Mercor", source: "ashby", token: "mercor" },
  { name: "Akuna Capital", source: "greenhouse", token: "akunacapital" },
  { name: "Warp", source: "ashby", token: "warp" },
  { name: "PostHog", source: "ashby", token: "posthog" },
  { name: "TaskRabbit", source: "greenhouse", token: "taskrabbit" },
  { name: "Bombas", source: "greenhouse", token: "bombas" },
  { name: "Talkspace", source: "greenhouse", token: "talkspace" },
  { name: "Railway", source: "ashby", token: "railway" },
  { name: "Neon", source: "ashby", token: "neon" },
  { name: "Aircall", source: "lever", token: "aircall" },
  { name: "BlaBlaCar", source: "lever", token: "blablacar" },
  { name: "Voodoo", source: "lever", token: "voodoo" },
  { name: "Qonto", source: "lever", token: "qonto" },
  { name: "Swile", source: "lever", token: "swile" },
  { name: "360Learning", source: "lever", token: "360learning" },
  { name: "Persado", source: "workable", token: "persado" },
  { name: "Zed", source: "ashby", token: "zed" },
  { name: "Thales", source: "smartrecruiters", token: "Thales" },
  { name: "Ledger", source: "lever", token: "ledger" },
  // SmartRecruiters (enterprise; API caps our fetch at 500/board)
  { name: "Bosch Group", source: "smartrecruiters", token: "BoschGroup" },
  { name: "JYSK", source: "smartrecruiters", token: "JYSK" },
  { name: "Devoteam", source: "smartrecruiters", token: "Devoteam" },
  { name: "Continental", source: "smartrecruiters", token: "Continental" },
  { name: "Experian", source: "smartrecruiters", token: "Experian" },
  { name: "Accor", source: "smartrecruiters", token: "Accor" },
  { name: "Ubisoft", source: "smartrecruiters", token: "Ubisoft2" },
  { name: "LGC Group", source: "smartrecruiters", token: "LGCGroup" },
  { name: "Colliers", source: "smartrecruiters", token: "Colliers" },
  { name: "McDonald's", source: "smartrecruiters", token: "McDonaldsCorporation" },
  { name: "Visa", source: "smartrecruiters", token: "visa" },
  // Workable
  { name: "Blueground", source: "workable", token: "blueground" },
  { name: "Plum", source: "workable", token: "withplum" },
  { name: "10x Genomics", source: "greenhouse", token: "10xgenomics" },
  { name: "Affirm", source: "greenhouse", token: "affirm" },
  { name: "Airbnb", source: "greenhouse", token: "airbnb" },
  { name: "Airtable", source: "greenhouse", token: "airtable" },
  { name: "Alloy", source: "greenhouse", token: "alloy" },
  { name: "Amplitude", source: "greenhouse", token: "amplitude" },
  { name: "Anthropic", source: "greenhouse", token: "anthropic" },
  { name: "Archer Aviation", source: "greenhouse", token: "archer" },
  { name: "Asana", source: "greenhouse", token: "asana" },
  { name: "Ashby", source: "ashby", token: "ashby" },
  { name: "Astranis", source: "greenhouse", token: "astranis" },
  { name: "Astronomer", source: "ashby", token: "astronomer" },
  { name: "Aurora Innovation", source: "greenhouse", token: "aurorainnovation" },
  { name: "Axios", source: "greenhouse", token: "axios" },
  { name: "Baseten", source: "ashby", token: "baseten" },
  { name: "Betterment", source: "greenhouse", token: "betterment" },
  { name: "Bombora", source: "greenhouse", token: "bombora" },
  { name: "Braze", source: "greenhouse", token: "braze" },
  { name: "Brex", source: "greenhouse", token: "brex" },
  { name: "Brooklinen", source: "greenhouse", token: "brooklinen" },
  { name: "Browserbase", source: "ashby", token: "browserbase" },
  { name: "Calm", source: "greenhouse", token: "calm" },
  { name: "Carta", source: "greenhouse", token: "carta" },
  { name: "Chan Zuckerberg Initiative", source: "greenhouse", token: "chanzuckerberginitiative" },
  { name: "Checkr", source: "greenhouse", token: "checkr" },
  { name: "Chime", source: "greenhouse", token: "chime" },
  { name: "Cloudflare", source: "greenhouse", token: "cloudflare" },
  { name: "Cohere", source: "ashby", token: "cohere" },
  { name: "Coinbase", source: "greenhouse", token: "coinbase" },
  { name: "Compass", source: "greenhouse", token: "urbancompass" },
  { name: "Consensys", source: "greenhouse", token: "consensys" },
  { name: "CoreWeave", source: "greenhouse", token: "coreweave" },
  { name: "Current", source: "greenhouse", token: "current" },
  { name: "Cursor", source: "ashby", token: "cursor" },
  { name: "Databricks", source: "greenhouse", token: "databricks" },
  { name: "Datadog", source: "greenhouse", token: "datadog" },
  { name: "Dexterity", source: "lever", token: "dexterity" },
  { name: "Discord", source: "greenhouse", token: "discord" },
  { name: "Docker", source: "ashby", token: "docker" },
  { name: "DriveWealth", source: "greenhouse", token: "drivewealth" },
  { name: "Dropbox", source: "greenhouse", token: "dropbox" },
  { name: "Duolingo", source: "greenhouse", token: "duolingo" },
  { name: "Earnin", source: "greenhouse", token: "earnin" },
  { name: "ElevenLabs", source: "ashby", token: "elevenlabs" },
  { name: "Faire", source: "greenhouse", token: "faire" },
  { name: "Fal", source: "ashby", token: "fal-ai" },
  { name: "Fictiv", source: "greenhouse", token: "fictiv" },
  { name: "Figma", source: "greenhouse", token: "figma" },
  { name: "Fireblocks", source: "greenhouse", token: "fireblocks" },
  { name: "Flexport", source: "greenhouse", token: "flexport" },
  { name: "Galaxy", source: "greenhouse", token: "galaxydigitalservices" },
  { name: "GetYourGuide", source: "greenhouse", token: "getyourguide" },
  { name: "Ginkgo Bioworks", source: "greenhouse", token: "ginkgobioworks" },
  { name: "GitLab", source: "greenhouse", token: "gitlab" },
  { name: "Glossier", source: "greenhouse", token: "glossier" },
  { name: "GOAT Group", source: "greenhouse", token: "goatgroup" },
  { name: "Granola", source: "ashby", token: "granola" },
  { name: "Grove Collaborative", source: "greenhouse", token: "grovecollaborative" },
  { name: "Guild", source: "greenhouse", token: "guild" },
  { name: "Gusto", source: "greenhouse", token: "gusto" },
  { name: "Harry's", source: "greenhouse", token: "harrys" },
  { name: "Harvey", source: "ashby", token: "harvey" },
  { name: "HelloFresh", source: "greenhouse", token: "hellofresh" },
  { name: "Highspot", source: "lever", token: "highspot" },
  { name: "Human Interest", source: "greenhouse", token: "humaninterest" },
  { name: "iCapital", source: "greenhouse", token: "icapitalnetwork" },
  { name: "Instacart", source: "greenhouse", token: "instacart" },
  { name: "Intercom", source: "greenhouse", token: "intercom" },
  { name: "IXL Learning", source: "greenhouse", token: "ixllearning" },
  { name: "Jane Street", source: "greenhouse", token: "janestreet" },
  { name: "Justworks", source: "greenhouse", token: "justworks" },
  { name: "Khan Academy", source: "greenhouse", token: "khanacademy" },
  { name: "Kikoff", source: "greenhouse", token: "kikoff" },
  { name: "Klaviyo", source: "greenhouse", token: "klaviyo" },
  { name: "Komodo Health", source: "greenhouse", token: "komodohealth" },
  { name: "LangChain", source: "ashby", token: "langchain" },
  { name: "Lattice", source: "greenhouse", token: "lattice" },
  { name: "Linear", source: "ashby", token: "linear" },
  { name: "Marqeta", source: "greenhouse", token: "marqeta" },
  { name: "MasterClass", source: "greenhouse", token: "masterclass" },
  { name: "Maven Clinic", source: "greenhouse", token: "mavenclinic" },
  { name: "Mercury", source: "greenhouse", token: "mercury" },
  { name: "Metabase", source: "lever", token: "metabase" },
  { name: "Misfits Market", source: "greenhouse", token: "misfitsmarket" },
  { name: "Modal", source: "ashby", token: "modal" },
  { name: "MongoDB", source: "greenhouse", token: "mongodb" },
  { name: "Motive", source: "greenhouse", token: "gomotive" },
  { name: "Newsela", source: "greenhouse", token: "newsela" },
  { name: "Notion", source: "ashby", token: "notion" },
  { name: "Nuro", source: "greenhouse", token: "nuro" },
  { name: "Octopus Energy", source: "lever", token: "octoenergy" },
  { name: "Okta", source: "greenhouse", token: "okta" },
  { name: "Olipop", source: "greenhouse", token: "olipop" },
  { name: "Omada Health", source: "greenhouse", token: "omadahealth" },
  { name: "One Medical", source: "greenhouse", token: "onemedical" },
  { name: "Oscar Health", source: "greenhouse", token: "oscar" },
  { name: "Outreach", source: "lever", token: "outreach" },
  { name: "Outschool", source: "greenhouse", token: "outschool" },
  { name: "Palantir", source: "lever", token: "palantir" },
  { name: "Palmetto", source: "greenhouse", token: "palmetto" },
  { name: "Parachute Home", source: "greenhouse", token: "parachutehome" },
  { name: "Parsley Health", source: "greenhouse", token: "parsleyhealth" },
  { name: "Peloton", source: "greenhouse", token: "peloton" },
  { name: "Pinterest", source: "greenhouse", token: "pinterest" },
  { name: "Plusgrade", source: "lever", token: "plusgrade" },
  { name: "Point72", source: "greenhouse", token: "point72" },
  { name: "project44", source: "greenhouse", token: "project44" },
  { name: "Ramp", source: "ashby", token: "ramp" },
  { name: "Recursion", source: "greenhouse", token: "recursionpharmaceuticals" },
  { name: "Reddit", source: "greenhouse", token: "reddit" },
  { name: "Redwood Materials", source: "greenhouse", token: "redwoodmaterials" },
  { name: "Relativity Space", source: "greenhouse", token: "relativity" },
  { name: "Remote", source: "greenhouse", token: "remotecom" },
  { name: "Replit", source: "ashby", token: "replit" },
  { name: "Robinhood", source: "greenhouse", token: "robinhood" },
  { name: "Roofstock", source: "greenhouse", token: "roofstock" },
  { name: "Samsara", source: "greenhouse", token: "samsara" },
  { name: "Scale AI", source: "greenhouse", token: "scaleai" },
  { name: "Scopely", source: "greenhouse", token: "scopely" },
  { name: "Scout Motors", source: "greenhouse", token: "scoutmotors" },
  { name: "Sierra", source: "ashby", token: "sierra" },
  { name: "SoFi", source: "greenhouse", token: "sofi" },
  { name: "Spotify", source: "lever", token: "spotify" },
  { name: "Sprout Social", source: "greenhouse", token: "sproutsocial" },
  { name: "Squarespace", source: "greenhouse", token: "squarespace" },
  { name: "StockX", source: "greenhouse", token: "stockx" },
  { name: "Stripe", source: "greenhouse", token: "stripe" },
  { name: "Supabase", source: "ashby", token: "supabase" },
  { name: "Sweetgreen", source: "greenhouse", token: "sweetgreen" },
  { name: "Toast", source: "greenhouse", token: "toast" },
  { name: "Together AI", source: "greenhouse", token: "togetherai" },
  { name: "Tulip", source: "greenhouse", token: "tulip" },
  { name: "Twilio", source: "greenhouse", token: "twilio" },
  { name: "Udemy", source: "greenhouse", token: "udemy" },
  { name: "Upgrade", source: "greenhouse", token: "upgrade" },
  { name: "Vacasa", source: "greenhouse", token: "vacasa" },
  { name: "Vapi", source: "ashby", token: "vapi" },
  { name: "Varda Space", source: "greenhouse", token: "vardaspace" },
  { name: "Veeva", source: "lever", token: "veeva" },
  { name: "Vercel", source: "greenhouse", token: "vercel" },
  { name: "Vox Media", source: "greenhouse", token: "voxmedia" },
  { name: "Wikimedia Foundation", source: "greenhouse", token: "wikimedia" },
  { name: "xAI", source: "greenhouse", token: "xai" },
  { name: "Zipline", source: "greenhouse", token: "flyzipline" },
  { name: "Zocdoc", source: "greenhouse", token: "zocdoc" },
  { name: "Zoox", source: "lever", token: "zoox" },
];
