// The job board's company allowlist. Every entry was LIVE-VERIFIED against
// the ATS's official public job-board API before shipping (200 + >0 postings,
// last sweep 2026-07-11, 146 companies). These endpoints are published by the vendors for exactly
// this consumption — no scraping, no auth, no ToS gray zone:
//   Greenhouse: https://boards-api.greenhouse.io/v1/boards/{token}/jobs
//   Lever:      https://api.lever.co/v0/postings/{token}?mode=json
//   Ashby:      https://api.ashbyhq.com/posting-api/job-board/{token}
// Tokens rot when companies migrate ATSs; the fetcher tolerates failures and
// reports failedSources so a dead token degrades, never breaks, the board.

export type JobSourceKind = "greenhouse" | "lever" | "ashby";

export interface JobSource {
  name: string; // display name
  source: JobSourceKind;
  token: string; // the company's board token on that ATS
}

export const JOB_SOURCES: JobSource[] = [
  { name: "10x Genomics", source: "greenhouse", token: "10xgenomics" },
  { name: "Affirm", source: "greenhouse", token: "affirm" },
  { name: "Airbnb", source: "greenhouse", token: "airbnb" },
  { name: "Airtable", source: "greenhouse", token: "airtable" },
  { name: "Alloy", source: "greenhouse", token: "alloy" },
  { name: "Amplitude", source: "greenhouse", token: "amplitude" },
  { name: "Anthropic", source: "greenhouse", token: "anthropic" },
  { name: "Archer Aviation", source: "greenhouse", token: "archer" },
  { name: "Asana", source: "greenhouse", token: "asana" },
  { name: "Ashby", source: "ashby", token: "ashby" },
  { name: "Astranis", source: "greenhouse", token: "astranis" },
  { name: "Astronomer", source: "ashby", token: "astronomer" },
  { name: "Aurora Innovation", source: "greenhouse", token: "aurorainnovation" },
  { name: "Axios", source: "greenhouse", token: "axios" },
  { name: "Baseten", source: "ashby", token: "baseten" },
  { name: "Betterment", source: "greenhouse", token: "betterment" },
  { name: "Bombora", source: "greenhouse", token: "bombora" },
  { name: "Braze", source: "greenhouse", token: "braze" },
  { name: "Brex", source: "greenhouse", token: "brex" },
  { name: "Brooklinen", source: "greenhouse", token: "brooklinen" },
  { name: "Browserbase", source: "ashby", token: "browserbase" },
  { name: "Calm", source: "greenhouse", token: "calm" },
  { name: "Carta", source: "greenhouse", token: "carta" },
  { name: "Chan Zuckerberg Initiative", source: "greenhouse", token: "chanzuckerberginitiative" },
  { name: "Checkr", source: "greenhouse", token: "checkr" },
  { name: "Chime", source: "greenhouse", token: "chime" },
  { name: "Cloudflare", source: "greenhouse", token: "cloudflare" },
  { name: "Cohere", source: "ashby", token: "cohere" },
  { name: "Coinbase", source: "greenhouse", token: "coinbase" },
  { name: "Compass", source: "greenhouse", token: "urbancompass" },
  { name: "Consensys", source: "greenhouse", token: "consensys" },
  { name: "CoreWeave", source: "greenhouse", token: "coreweave" },
  { name: "Current", source: "greenhouse", token: "current" },
  { name: "Cursor", source: "ashby", token: "cursor" },
  { name: "Databricks", source: "greenhouse", token: "databricks" },
  { name: "Datadog", source: "greenhouse", token: "datadog" },
  { name: "Dexterity", source: "lever", token: "dexterity" },
  { name: "Discord", source: "greenhouse", token: "discord" },
  { name: "Docker", source: "ashby", token: "docker" },
  { name: "DriveWealth", source: "greenhouse", token: "drivewealth" },
  { name: "Dropbox", source: "greenhouse", token: "dropbox" },
  { name: "Duolingo", source: "greenhouse", token: "duolingo" },
  { name: "Earnin", source: "greenhouse", token: "earnin" },
  { name: "ElevenLabs", source: "ashby", token: "elevenlabs" },
  { name: "Faire", source: "greenhouse", token: "faire" },
  { name: "Fal", source: "ashby", token: "fal-ai" },
  { name: "Fictiv", source: "greenhouse", token: "fictiv" },
  { name: "Figma", source: "greenhouse", token: "figma" },
  { name: "Fireblocks", source: "greenhouse", token: "fireblocks" },
  { name: "Flexport", source: "greenhouse", token: "flexport" },
  { name: "Galaxy", source: "greenhouse", token: "galaxydigitalservices" },
  { name: "GetYourGuide", source: "greenhouse", token: "getyourguide" },
  { name: "Ginkgo Bioworks", source: "greenhouse", token: "ginkgobioworks" },
  { name: "GitLab", source: "greenhouse", token: "gitlab" },
  { name: "Glossier", source: "greenhouse", token: "glossier" },
  { name: "GOAT Group", source: "greenhouse", token: "goatgroup" },
  { name: "Granola", source: "ashby", token: "granola" },
  { name: "Grove Collaborative", source: "greenhouse", token: "grovecollaborative" },
  { name: "Guild", source: "greenhouse", token: "guild" },
  { name: "Gusto", source: "greenhouse", token: "gusto" },
  { name: "Harry's", source: "greenhouse", token: "harrys" },
  { name: "Harvey", source: "ashby", token: "harvey" },
  { name: "HelloFresh", source: "greenhouse", token: "hellofresh" },
  { name: "Highspot", source: "lever", token: "highspot" },
  { name: "Human Interest", source: "greenhouse", token: "humaninterest" },
  { name: "iCapital", source: "greenhouse", token: "icapitalnetwork" },
  { name: "Instacart", source: "greenhouse", token: "instacart" },
  { name: "Intercom", source: "greenhouse", token: "intercom" },
  { name: "IXL Learning", source: "greenhouse", token: "ixllearning" },
  { name: "Jane Street", source: "greenhouse", token: "janestreet" },
  { name: "Justworks", source: "greenhouse", token: "justworks" },
  { name: "Khan Academy", source: "greenhouse", token: "khanacademy" },
  { name: "Kikoff", source: "greenhouse", token: "kikoff" },
  { name: "Klaviyo", source: "greenhouse", token: "klaviyo" },
  { name: "Komodo Health", source: "greenhouse", token: "komodohealth" },
  { name: "LangChain", source: "ashby", token: "langchain" },
  { name: "Lattice", source: "greenhouse", token: "lattice" },
  { name: "Linear", source: "ashby", token: "linear" },
  { name: "Marqeta", source: "greenhouse", token: "marqeta" },
  { name: "MasterClass", source: "greenhouse", token: "masterclass" },
  { name: "Maven Clinic", source: "greenhouse", token: "mavenclinic" },
  { name: "Mercury", source: "greenhouse", token: "mercury" },
  { name: "Metabase", source: "lever", token: "metabase" },
  { name: "Misfits Market", source: "greenhouse", token: "misfitsmarket" },
  { name: "Modal", source: "ashby", token: "modal" },
  { name: "MongoDB", source: "greenhouse", token: "mongodb" },
  { name: "Motive", source: "greenhouse", token: "gomotive" },
  { name: "Newsela", source: "greenhouse", token: "newsela" },
  { name: "Notion", source: "ashby", token: "notion" },
  { name: "Nuro", source: "greenhouse", token: "nuro" },
  { name: "Octopus Energy", source: "lever", token: "octoenergy" },
  { name: "Okta", source: "greenhouse", token: "okta" },
  { name: "Olipop", source: "greenhouse", token: "olipop" },
  { name: "Omada Health", source: "greenhouse", token: "omadahealth" },
  { name: "One Medical", source: "greenhouse", token: "onemedical" },
  { name: "Oscar Health", source: "greenhouse", token: "oscar" },
  { name: "Outreach", source: "lever", token: "outreach" },
  { name: "Outschool", source: "greenhouse", token: "outschool" },
  { name: "Palantir", source: "lever", token: "palantir" },
  { name: "Palmetto", source: "greenhouse", token: "palmetto" },
  { name: "Parachute Home", source: "greenhouse", token: "parachutehome" },
  { name: "Parsley Health", source: "greenhouse", token: "parsleyhealth" },
  { name: "Peloton", source: "greenhouse", token: "peloton" },
  { name: "Pinterest", source: "greenhouse", token: "pinterest" },
  { name: "Plusgrade", source: "lever", token: "plusgrade" },
  { name: "Point72", source: "greenhouse", token: "point72" },
  { name: "project44", source: "greenhouse", token: "project44" },
  { name: "Ramp", source: "ashby", token: "ramp" },
  { name: "Recursion", source: "greenhouse", token: "recursionpharmaceuticals" },
  { name: "Reddit", source: "greenhouse", token: "reddit" },
  { name: "Redwood Materials", source: "greenhouse", token: "redwoodmaterials" },
  { name: "Relativity Space", source: "greenhouse", token: "relativity" },
  { name: "Remote", source: "greenhouse", token: "remotecom" },
  { name: "Replit", source: "ashby", token: "replit" },
  { name: "Robinhood", source: "greenhouse", token: "robinhood" },
  { name: "Roofstock", source: "greenhouse", token: "roofstock" },
  { name: "Samsara", source: "greenhouse", token: "samsara" },
  { name: "Scale AI", source: "greenhouse", token: "scaleai" },
  { name: "Scopely", source: "greenhouse", token: "scopely" },
  { name: "Scout Motors", source: "greenhouse", token: "scoutmotors" },
  { name: "Sierra", source: "ashby", token: "sierra" },
  { name: "SoFi", source: "greenhouse", token: "sofi" },
  { name: "Spotify", source: "lever", token: "spotify" },
  { name: "Sprout Social", source: "greenhouse", token: "sproutsocial" },
  { name: "Squarespace", source: "greenhouse", token: "squarespace" },
  { name: "StockX", source: "greenhouse", token: "stockx" },
  { name: "Stripe", source: "greenhouse", token: "stripe" },
  { name: "Supabase", source: "ashby", token: "supabase" },
  { name: "Sweetgreen", source: "greenhouse", token: "sweetgreen" },
  { name: "Toast", source: "greenhouse", token: "toast" },
  { name: "Together AI", source: "greenhouse", token: "togetherai" },
  { name: "Tulip", source: "greenhouse", token: "tulip" },
  { name: "Twilio", source: "greenhouse", token: "twilio" },
  { name: "Udemy", source: "greenhouse", token: "udemy" },
  { name: "Upgrade", source: "greenhouse", token: "upgrade" },
  { name: "Vacasa", source: "greenhouse", token: "vacasa" },
  { name: "Vapi", source: "ashby", token: "vapi" },
  { name: "Varda Space", source: "greenhouse", token: "vardaspace" },
  { name: "Veeva", source: "lever", token: "veeva" },
  { name: "Vercel", source: "greenhouse", token: "vercel" },
  { name: "Vox Media", source: "greenhouse", token: "voxmedia" },
  { name: "Wikimedia Foundation", source: "greenhouse", token: "wikimedia" },
  { name: "xAI", source: "greenhouse", token: "xai" },
  { name: "Zipline", source: "greenhouse", token: "flyzipline" },
  { name: "Zocdoc", source: "greenhouse", token: "zocdoc" },
  { name: "Zoox", source: "lever", token: "zoox" },
];
