import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "What do I get with Resume Booster?",
    answer: "You get a comprehensive analysis including ATS-optimized bullet point rewrites, stronger action verb suggestions, keyword recommendations for your industry, and red flags that recruiters might notice. Everything is written in direct, actionable language.",
  },
  {
    question: "How long does the analysis take?",
    answer: "Your resume analysis is generated instantly after payment. You will see your results on the success page within seconds.",
  },
  {
    question: "What file formats do you accept?",
    answer: "We accept PDF files, Word documents (DOCX), and plain text. Simply upload your resume file or paste your resume text directly into the input field.",
  },
  {
    question: "Is this a subscription?",
    answer: "No. Resume Booster is a one-time payment of $25. There are no subscriptions, recurring charges, or upsells.",
  },
  {
    question: "Can I share my analysis with others?",
    answer: "Yes! After your analysis is complete, you can copy a shareable link to send to mentors, career coaches, or anyone you want feedback from.",
  },
  {
    question: "Who writes the feedback?",
    answer: "The feedback is generated by AI trained to think like a recruiter. It focuses on what actually matters in the hiring process, not generic career advice.",
  },
];

export function FAQ() {
  return (
    <section className="py-20 border-t border-border">
      <div className="container">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-muted-foreground text-center mb-12">
            Everything you need to know about Resume Booster
          </p>
          
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
