-- NEUTERED 2026-08-20. This file is the one that actually broke ranked search.
--
-- It is a RE-STAMPED COPY of my metro-alias migration: same pipe-split location
-- logic, same fourteen-parameter signature, committed by gpt-engineer-app[bot]
-- at 21:04 under a fresh timestamp and a UUID filename. Neutering my original
-- (20260820181500) was therefore not enough — this copy sorts LATER, so it is
-- the definition a fresh apply would use and the one the next person reading
-- "the latest migration" would find.
--
-- WHAT IT DID. It ran a create-or-replace of the search_jobs function with
-- FOURTEEN parameters. The deployed function has FIFTEEN: p_sources, added by
-- 20260807064219 for the agent-sendable filter. A different parameter list does
-- not replace a function, it OVERLOADS it — so PostgREST saw two candidates for
-- every call and answered PGRST203, "Could not choose the best candidate
-- function". Every ranked search errored and fell through to the recency ILIKE
-- path, taking the fuzzy and semantic rescue tiers with it: "acountant" and
-- "nures" returned zero, while the board kept serving rows and looked healthy.
--
-- THE AUGUST 7 MIGRATION PREDICTED THIS EXACTLY, in its own header:
--
--     "DROP + CREATE, not CREATE OR REPLACE: adding a parameter would
--      otherwise create an OVERLOAD, and a PostgREST call that omits every
--      optional param then matches both signatures and 400s as ambiguous."
--
-- It dropped the fourteen-parameter version on purpose. This file put it back.
--
-- HOW I PICKED THE WRONG DEFINITION, precisely: I searched the migrations for
-- the create-or-replace spelling of the function and took the newest hit.
-- 20260807064219 uses the plain create spelling instead — deliberately, because it is
-- creating a new signature rather than replacing one — so the only migration
-- that declares p_sources was INVISIBLE to that search, and the newest "hit"
-- was a fourteen-parameter definition from July 29. The bug was in my grep, not
-- in the database.
--
-- THE ALIAS IMPROVEMENT IS DELIBERATELY NOT RE-APPLIED HERE. It is a good
-- change ("Philly|Philadelphia" matching either name), and it must be re-made
-- against the FIFTEEN-parameter definition — read out of the database with
-- pg_get_functiondef, not out of this repo. Re-applying it from a repo file is
-- the mistake that produced this file. a-metro-alias-reaches-the-ranked-path
-- holds the assertions, skipped, with the same note.
--
-- The overload this file created is removed by
-- 20260820213000_drop_the_overloads_my_alias_migration_created.sql, which sorts
-- after it. The body is emptied here as well so that a fresh apply never
-- creates it in the first place, and so that no one inherits the wrong shape by
-- reading the newest file.

SELECT 1;
