-- Name overrides batch 5 + Explore hygiene.
--
-- METHOD (new, repeatable): 91% of Workday tenants display a name derived from
-- their slug. Most are correct ("Tyson Foods", "Barclays"); the broken subset is
-- ACRONYMS, which title-casing destroys ("Ntrs", "Jll", "Vfc"). Candidates were
-- generated by matching the slug against the SEC EDGAR ticker map (tickers are
-- globally unique), then EVERY candidate was corroborated against that tenant's
-- own live postings before acceptance.
--
-- The corroboration step is NOT optional — the ticker match alone produced these
-- false positives, all rejected here:
--   lego -> "Legato Merger Corp"      (it is LEGO the toy company)
--   nxp  -> "Nuveen Select Tax Free"  (it is NXP Semiconductors)
--   sky  -> "Champion Homes"          (it is Sky)
--   card -> "Bank of Montreal"        (generic word, collided)
--   hq   -> "Horizon Quantum"         (generic word, collided)
--   ms   -> "Morgan Stanley"          (could equally be Microsoft)
-- and these, caught only by reading the tenant's actual postings:
--   fhi  -> "Federated Hermes"  REJECTED: posts "Driver, Gaborone, Botswana" = FHI 360, the nonprofit
--   unf  -> "UniFirst"          REJECTED: posts "Assistant Director of Gift Processing" = University of North Florida
--   cnx  -> "CNX Resources"     REJECTED: posts work-at-home experience design = reads as Concentrix
--   pfg  -> "Principal Financial" REJECTED: posts "Nutrition Specialist, BC" = a food business
--   ccc, ntst, fmc, aes         REJECTED: postings did not corroborate the ticker's company
--
-- Accepted below only where the tenant's own postings confirm the identity
-- (e.g. vfc posts "The North Face: Assistant Store Manager" — VF Corp owns that
-- brand; seic posts "USA - PA - Oaks" — SEI's headquarters; wmg posts
-- "27 Wrights Lane" — Warner Music UK's address).

INSERT INTO public.company_name_overrides (slug, display_name) VALUES
  ('aig','AIG'),
  ('asml','ASML'),
  ('avav','AeroVironment'),
  ('bdx','Becton Dickinson'),
  ('cae','CAE'),
  ('cars','Cars.com'),
  ('cna','CNA Financial'),
  ('ebay','eBay'),
  ('fis','FIS'),
  ('gnw','Genworth'),
  ('jbtm','JBT Marel'),
  ('jll','JLL'),
  ('ntrs','Northern Trust'),
  ('oxy','Occidental Petroleum'),
  ('ptc','PTC'),
  ('rxo','RXO'),
  ('seic','SEI Investments'),
  ('spgi','S&P Global'),
  ('ufpi','UFP Industries'),
  ('vfc','VF Corporation'),
  ('vrtx','Vertex Pharmaceuticals'),
  ('wmg','Warner Music Group')
ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name;

-- Apply to stored rows (same three tables as batches 1-4).
UPDATE public.job_board_postings p SET company = o.display_name
  FROM public.company_name_overrides o
 WHERE p.company_token LIKE '%~wd%'
   AND split_part(p.company_token,'~',1) = o.slug AND p.company <> o.display_name;
UPDATE public.job_board_closures c SET company = o.display_name
  FROM public.company_name_overrides o
 WHERE c.company_token LIKE '%~wd%'
   AND split_part(c.company_token,'~',1) = o.slug AND c.company <> o.display_name;
UPDATE public.job_board_company_snapshots s SET company = o.display_name
  FROM public.company_name_overrides o
 WHERE s.company_token LIKE '%~wd%'
   AND split_part(s.company_token,'~',1) = o.slug AND s.company <> o.display_name;

-- Explore hygiene: entities that are not corporate employers.
--   mwamevents  — Greenhouse board whose derived company name is literally
--                 "Events"; it was ranking in Newest Companies.
--   okgov       — Oklahoma state government; the catalog is corporate-only.
INSERT INTO public.showcase_excluded (company_token, reason) VALUES
  ('mwamevents', 'derived company name is the non-name "Events"; not an identifiable employer'),
  ('okgov~wd1~okgovjobs', 'US state government (Oklahoma) — catalog is corporate-only')
ON CONFLICT (company_token) DO UPDATE SET reason = EXCLUDED.reason;

-- okgov may carry a different Workday site suffix than the one above; exclude
-- every token whose tenant slug is okgov so the rule cannot be sidestepped by a
-- site rename.
INSERT INTO public.showcase_excluded (company_token, reason)
SELECT DISTINCT company_token, 'US state government (Oklahoma) — catalog is corporate-only'
  FROM public.job_board_postings
 WHERE split_part(company_token,'~',1) = 'okgov'
ON CONFLICT (company_token) DO NOTHING;

DO $$
BEGIN
  SET LOCAL statement_timeout = '55s';
  PERFORM public.refresh_explore_cache();
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'explore cache refresh deferred to the next scheduled run: %', SQLERRM;
END $$;
