-- THE SAVED-SEARCH DIGEST AND THE CORRECTIONS DIGEST RUN ON A SCHEDULE (wave 2
-- email-ops, register L11-01; owner decision 2026-10-07: schedule it).
--
-- get_cron_health listed 48 jobs in production and neither send-search-digest
-- nor industry-corrections-digest was one of them; no migration unscheduled
-- either, so both were removed by hand or never created. Every "Email me
-- weekly when new jobs match" bell and every "We'll email you when they post
-- new roles" watch therefore sent nothing, with no error anywhere (a missing
-- job has no failed runs). 20261004100000 re-created the email crons with the
-- cron key and deliberately left an absent digest job absent; this file is the
-- decision to create them.
--
-- APPLY ORDER: after send-search-digest.2026-10-08.1 and job-board .91 serve
-- (docs/wave2/email-ops.md). Those builds window the digest on discovery time
-- (newSince) and give a claim back when the board cannot answer; the build
-- before them would mail a search's matches by the employer's date and lose a
-- window to any board hiccup.
--
-- Both jobs send x-email-cron from the vault (email_cron_key, generated by
-- 20261004100000) and fire nothing where that secret is absent. Safe to
-- re-run: each job is unscheduled by name and scheduled again.

DO $$
DECLARE
  r record;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'cron') THEN
    RAISE NOTICE 'pg_cron is not installed here; the digests were not scheduled';
    RETURN;
  END IF;
  FOR r IN
    SELECT * FROM (VALUES ('send-search-digest', '23 14 * * *'),
                          ('industry-corrections-digest', '15 9 * * 1')) v(job, sched)
  LOOP
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = r.job) THEN
      PERFORM cron.unschedule(r.job);
    END IF;
    PERFORM cron.schedule(r.job, r.sched, format($job$
    SELECT net.http_post(
      url := %L,
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-email-cron', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'email_cron_key' LIMIT 1)
      ),
      body := '{"action":"send"}'::jsonb
    )
    WHERE EXISTS (SELECT 1 FROM vault.decrypted_secrets WHERE name = 'email_cron_key');
    $job$, 'https://bwhdazbotpblihdxcmho.supabase.co/functions/v1/' || r.job));
  END LOOP;
END $$;

DO $$
DECLARE
  v_job text;
  v_sched text;
  v_cmd text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'cron') THEN
    RETURN;
  END IF;
  FOR v_job, v_sched IN SELECT * FROM (VALUES ('send-search-digest', '23 14 * * *'), ('industry-corrections-digest', '15 9 * * 1')) v(j, s)
  LOOP
    SELECT j.command INTO v_cmd FROM cron.job j WHERE j.jobname = v_job AND j.schedule = v_sched;
    IF v_cmd IS NULL THEN
      RAISE EXCEPTION 'self-check: the % cron job does not exist on schedule %', v_job, v_sched;
    END IF;
    IF position('x-email-cron' IN v_cmd) = 0 OR position('email_cron_key' IN v_cmd) = 0
       OR position('/functions/v1/' || v_job || '''' IN v_cmd) = 0 THEN
      RAISE EXCEPTION 'self-check: the % cron does not post to its function with the email cron key: %', v_job, v_cmd;
    END IF;
  END LOOP;
END $$;
