-- Superseded: the proactive/email closure-alert feature was removed in favor
-- of click-time verification (you're told a listing closed only when you
-- click it). The columns below were applied to production before the
-- reversal; they're harmless and left in place rather than dropped
-- (destructive). This migration is now a documented no-op — new environments
-- simply won't create the unused columns.
--
-- Original (kept for the historical record, not executed):
--   ALTER TABLE public.user_profiles ADD COLUMN closure_alerts_opt_in boolean NOT NULL DEFAULT false;
--   ALTER TABLE public.user_applications ADD COLUMN posting_closed_notified_at timestamptz;
--   CREATE INDEX ... ON public.user_applications (posting_closed_at) WHERE ...;
SELECT 1;
