-- Tier-1 company headcounts: sourced, labeled, never guessed. 867 companies
-- (940 board tokens) matched by STRICT normalized-name rules against two
-- public sources:
--   * 'yc_self_reported' — team_size from Y Combinator's public company
--     directory (the company's own profile; batch recorded alongside).
--   * 'public_records'   — employee counts from Wikidata (community-maintained
--     public records citing company reports/filings).
-- Matching guards (all verified on the audit trail): ambiguous names dropped
-- entirely; short/generic names require big-co scale (public records) or a
-- domain-matching ATS token (YC); a tiny YC team cannot claim a big board
-- (postings <= 3x team_size) — this correctly rejected YC's 7-person
-- "Benchmark" colliding with our 505-posting Benchmark PT, and a wrong
-- 215-employee "Roche" entity. Where no source qualifies, we store NOTHING.
--
-- The Explore scale segments now band by TRUE stated headcount where known
-- (Enterprise 1,000+, Mid-market 100-999, Startups & small teams <100) and
-- fall back to hiring footprint otherwise — both definitions stated in the UI.

CREATE TABLE IF NOT EXISTS public.company_profiles (
  company_token text PRIMARY KEY,
  employee_count integer NOT NULL,
  employee_basis text NOT NULL CHECK (employee_basis IN ('yc_self_reported','public_records')),
  yc_batch text
);
ALTER TABLE public.company_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "company_profiles_public_read" ON public.company_profiles;
CREATE POLICY "company_profiles_public_read" ON public.company_profiles FOR SELECT USING (true);

INSERT INTO public.company_profiles (company_token, employee_count, employee_basis, yc_batch) VALUES
  ('11bitstudios', 250, 'public_records', NULL),
  ('9-mothers', 19, 'yc_self_reported', 'Spring 2026'),
  ('ASICS', 9039, 'public_records', NULL),
  ('AbercrombieAndFitchCo', 6900, 'public_records', NULL),
  ('AirNewZealand', 8863, 'public_records', NULL),
  ('BDO4', 4048, 'public_records', NULL),
  ('BESIX', 15000, 'public_records', NULL),
  ('CDPROJEKTRED', 981, 'public_records', NULL),
  ('CERN', 2704, 'public_records', NULL),
  ('CliffordChance', 3400, 'public_records', NULL),
  ('CocuSocial', 10, 'yc_self_reported', 'Summer 2017'),
  ('Cofactr', 15, 'yc_self_reported', 'Winter 2022'),
  ('Continental', 202763, 'public_records', NULL),
  ('Dashlabsai', 30, 'yc_self_reported', 'Winter 2021'),
  ('DeliveryHero', 47981, 'public_records', NULL),
  ('EgisGroup', 13600, 'public_records', NULL),
  ('Experian', 17000, 'public_records', NULL),
  ('Hive.co', 65, 'yc_self_reported', 'Summer 2014'),
  ('Instrumentl', 60, 'yc_self_reported', 'Summer 2016'),
  ('Interbrand', 1250, 'public_records', NULL),
  ('KMSTechnology1', 1300, 'public_records', NULL),
  ('KPN', 18949, 'public_records', NULL),
  ('LGCGroup', 2457, 'public_records', NULL),
  ('LVMH2', 215000, 'public_records', NULL),
  ('Lely1', 2300, 'public_records', NULL),
  ('LinkedIn3', 11800, 'public_records', NULL),
  ('Lumi', 67, 'yc_self_reported', 'Winter 2015'),
  ('Meta1', 58604, 'public_records', NULL),
  ('NBCUniversal3', 16000, 'public_records', NULL),
  ('Netcompany1', 7353, 'public_records', NULL),
  ('Playtech', 7400, 'public_records', NULL),
  ('Redcare-Pharmacy', 2075, 'public_records', NULL),
  ('RenesasElectronics', 21204, 'public_records', NULL),
  ('ScribdInc', 300, 'yc_self_reported', 'Summer 2006'),
  ('Securitas', 2930, 'public_records', NULL),
  ('ServiceNow', 10371, 'public_records', NULL),
  ('SiloamCareers', 12700, 'public_records', NULL),
  ('SmithsGroup2', 23250, 'public_records', NULL),
  ('Sodexo', 420000, 'public_records', NULL),
  ('SopraSteria1', 50000, 'public_records', NULL),
  ('Sportradar', 1900, 'public_records', NULL),
  ('SyngentaGroup', 53000, 'public_records', NULL),
  ('The-Flex', 28, 'yc_self_reported', 'Summer 2016'),
  ('VectorLimited', 20, 'yc_self_reported', 'Winter 2023'),
  ('Vitol', 1800, 'public_records', NULL),
  ('VusionGroupSA', 1100, 'public_records', NULL),
  ('Wavestone1', 3453, 'public_records', NULL),
  ('WernerMertzGmbH', 920, 'public_records', NULL),
  ('WesternDigital', 76449, 'public_records', NULL),
  ('WesternSydneyUniversity', 2500, 'public_records', NULL),
  ('abacum', 125, 'yc_self_reported', 'Winter 2021'),
  ('abacus', 30, 'yc_self_reported', 'Winter 2014'),
  ('abb~wd3~external_career_page', 3003, 'public_records', NULL),
  ('able', 50, 'yc_self_reported', 'Winter 2020'),
  ('abstra', 18, 'yc_self_reported', 'Summer 2021'),
  ('abundant', 7, 'yc_self_reported', 'Fall 2024'),
  ('accenture~wd103~AccentureCareers', 779000, 'public_records', NULL),
  ('accenture~wd103~AvanadeCareers', 779000, 'public_records', NULL),
  ('access-bank', 28121, 'public_records', NULL),
  ('acciona~wd3~ACCIONA_Employment_Channel', 57843, 'public_records', NULL),
  ('accord', 20, 'yc_self_reported', 'Winter 2020'),
  ('acronis~wd502~acronis_careers', 2000, 'public_records', NULL),
  ('activate-group-limited', 300, 'public_records', NULL),
  ('acx', 4, 'yc_self_reported', 'Summer 2024'),
  ('adams~wd1~ASU', 1161, 'public_records', NULL),
  ('adaptyv', 25, 'yc_self_reported', 'Summer 2021'),
  ('adobe~wd5~external_experienced', 25988, 'public_records', NULL),
  ('adtran~wd3~ADTRAN', 2045, 'public_records', NULL),
  ('adtran~wd3~ANS', 2045, 'public_records', NULL),
  ('adtran~wd3~OSA', 2045, 'public_records', NULL),
  ('adventisthealthcare~wd1~AdventistHealthCareCareers', 6555, 'public_records', NULL),
  ('aegis', 3, 'yc_self_reported', 'Spring 2025'),
  ('aerones', 250, 'yc_self_reported', 'Winter 2018'),
  ('affinity', 2, 'yc_self_reported', 'Summer 2023'),
  ('afterquery', 30, 'yc_self_reported', 'Winter 2025'),
  ('agentmail', 10, 'yc_self_reported', 'Summer 2025'),
  ('agf~wd3~AGF_Careers', 11000, 'public_records', NULL),
  ('agf~wd3~Glassdoor_Careers', 11000, 'public_records', NULL),
  ('agf~wd3~Indeed_Careers', 11000, 'public_records', NULL),
  ('agrana~wd3~Careers', 9000, 'public_records', NULL),
  ('aios', 100, 'yc_self_reported', 'Winter 2020'),
  ('aiprise', 42, 'yc_self_reported', 'Summer 2022'),
  ('airbnb', 6132, 'yc_self_reported', 'Winter 2009'),
  ('airbyte', 90, 'yc_self_reported', 'Winter 2020'),
  ('airhelp', 350, 'yc_self_reported', 'Winter 2014'),
  ('ajaib', 300, 'yc_self_reported', 'Summer 2018'),
  ('akqa', 1600, 'public_records', NULL),
  ('aktion-mensch', 280, 'public_records', NULL),
  ('albedo', 55, 'yc_self_reported', 'Winter 2021'),
  ('alchemy', 25, 'yc_self_reported', 'Summer 2014'),
  ('alcoa~wd5~Careers', 61000, 'public_records', NULL),
  ('aleph', 30, 'yc_self_reported', 'Summer 2021'),
  ('alexander-dennis', 2300, 'public_records', NULL),
  ('algolia', 810, 'yc_self_reported', 'Winter 2014'),
  ('alloy', 5, 'yc_self_reported', 'Winter 2023'),
  ('alpaca', 150, 'yc_self_reported', 'Winter 2019'),
  ('altoslabs', 500, 'public_records', NULL),
  ('ambient.ai', 150, 'yc_self_reported', 'Winter 2017'),
  ('amplitude', 750, 'yc_self_reported', 'Winter 2012'),
  ('andersen~wd12~Andersen_External_Career_Site', 1004, 'public_records', NULL),
  ('anteagroup', 1800, 'public_records', NULL),
  ('anthrogen', 6, 'yc_self_reported', 'Summer 2024'),
  ('anthropic', 2500, 'public_records', NULL),
  ('apolloio', 800, 'yc_self_reported', 'Winter 2016'),
  ('april', 22000, 'public_records', NULL),
  ('arcesiumllc', 700, 'public_records', NULL),
  ('arenanet', 270, 'public_records', NULL),
  ('argo', 10, 'yc_self_reported', 'Winter 2022'),
  ('arianegroup~wd3~EXTERNALALL', 8000, 'public_records', NULL),
  ('arketa', 55, 'yc_self_reported', 'Summer 2020'),
  ('armilla-ai', 14, 'yc_self_reported', 'Winter 2022'),
  ('arq', 100, 'yc_self_reported', 'Summer 2021'),
  ('arriva~wd3~careers', 47499, 'public_records', NULL),
  ('asda~wd103~AsdaJobs', 143125, 'public_records', NULL),
  ('ashby', 110, 'yc_self_reported', 'Winter 2019'),
  ('ashesi', 385, 'public_records', NULL),
  ('asimov', 3, 'yc_self_reported', 'Winter 2026'),
  ('aspentech~wd5~AspenTech', 1466, 'public_records', NULL),
  ('aspora', 85, 'yc_self_reported', 'Winter 2022'),
  ('assemblyai', 65, 'yc_self_reported', 'Summer 2017'),
  ('astranis', 500, 'yc_self_reported', 'Winter 2016'),
  ('astrazeneca~wd3~Alexion', 70600, 'public_records', NULL),
  ('astrazeneca~wd3~Careers', 70600, 'public_records', NULL),
  ('astrazeneca~wd3~Emerging-Talent', 70600, 'public_records', NULL),
  ('astro-mechanica', 52, 'yc_self_reported', 'Winter 2024'),
  ('atomic', 25, 'yc_self_reported', 'Summer 2020'),
  ('attain', 5, 'yc_self_reported', 'Winter 2022'),
  ('attune', 3, 'yc_self_reported', 'Spring 2025'),
  ('att~wd1~ATTGeneral', 202600, 'public_records', NULL),
  ('auctor', 30, 'yc_self_reported', 'Spring 2025'),
  ('aurelian', 45, 'yc_self_reported', 'Summer 2022'),
  ('autostore~wd3~autostore', 370, 'public_records', NULL),
  ('avalanchestudios', 250, 'public_records', NULL),
  ('aviva~wd1~External', 27873, 'public_records', NULL),
  ('avoca', 85, 'yc_self_reported', 'Winter 2023'),
  ('axiom', 2, 'yc_self_reported', 'Winter 2025'),
  ('axle', 10, 'yc_self_reported', 'Summer 2022'),
  ('bacardi~wd3~Jobs_Bacardi', 6001, 'public_records', NULL),
  ('bankjoy', 60, 'yc_self_reported', 'Winter 2015'),
  ('barclays~wd3~External_Career_Site_Barclays', 79900, 'public_records', NULL),
  ('basalt', 6, 'yc_self_reported', 'Winter 2024'),
  ('belvo', 100, 'yc_self_reported', 'Winter 2020'),
  ('ben', 2, 'yc_self_reported', 'Winter 2018'),
  ('benchling', 750, 'yc_self_reported', 'Summer 2012'),
  ('benepass', 45, 'yc_self_reported', 'Winter 2020'),
  ('betatechnologiesinc', 650, 'public_records', NULL),
  ('beyondreachlabs', 5, 'yc_self_reported', 'Winter 2026'),
  ('bhvr', 200, 'public_records', NULL),
  ('bik', 55, 'yc_self_reported', 'Summer 2020'),
  ('billiontoone', 300, 'yc_self_reported', 'Summer 2017'),
  ('bird', 500, 'yc_self_reported', 'Summer 2016'),
  ('birdie', 2, 'yc_self_reported', 'Summer 2021'),
  ('bitmovin', 145, 'yc_self_reported', 'Summer 2015'),
  ('bitrise', 243, 'yc_self_reported', 'Winter 2017'),
  ('bitstack', 16, 'yc_self_reported', 'Summer 2022'),
  ('blacklane', 250, 'public_records', NULL),
  ('blackrock~wd1~BlackRock_Professional', 19800, 'public_records', NULL),
  ('blacksmith', 3, 'yc_self_reported', 'Winter 2024'),
  ('blackstone~wd1~Blackstone_Campus_Careers', 4735, 'public_records', NULL),
  ('blackstone~wd1~blackstone_careers', 4735, 'public_records', NULL),
  ('blissway', 22, 'yc_self_reported', 'Summer 2020'),
  ('blueorigin~wd5~BlueOrigin', 3501, 'public_records', NULL),
  ('boeing~wd1~EXTERNAL_CAREERS', 171000, 'public_records', NULL),
  ('boeing~wd1~INTERN', 171000, 'public_records', NULL),
  ('boeing~wd1~PRIDE', 171000, 'public_records', NULL),
  ('boeing~wd1~TAP2', 171000, 'public_records', NULL),
  ('boeing~wd1~external_subsidiary', 171000, 'public_records', NULL),
  ('borgwarner~wd5~BorgWarner_Careers', 49000, 'public_records', NULL),
  ('botbuilt', 8, 'yc_self_reported', 'Winter 2021'),
  ('braskem', 8126, 'public_records', NULL),
  ('breaker', 1, 'yc_self_reported', 'Winter 2017'),
  ('bree', 2, 'yc_self_reported', 'Summer 2021'),
  ('brenntag~wd3~brenntag_jobs', 17500, 'public_records', NULL),
  ('brex', 1000, 'yc_self_reported', 'Winter 2017'),
  ('bridgewater89', 1300, 'public_records', NULL),
  ('bright', 100, 'yc_self_reported', 'Winter 2015'),
  ('broadcom~wd1~External_Career', 20000, 'public_records', NULL),
  ('broccoli', 21, 'yc_self_reported', 'Winter 2022'),
  ('bronco-ai', 5, 'yc_self_reported', 'Summer 2023'),
  ('brunswickgroup', 1400, 'public_records', NULL),
  ('bud', 6, 'yc_self_reported', 'Winter 2025'),
  ('bupa~wd3~EXT_CAREER', 87000, 'public_records', NULL),
  ('cabify', 1300, 'public_records', NULL),
  ('caci~wd1~External', 20000, 'public_records', NULL),
  ('cambio', 60, 'yc_self_reported', 'Summer 2022'),
  ('cambly', 200, 'yc_self_reported', 'Winter 2014'),
  ('campfire', 105, 'yc_self_reported', 'Summer 2023'),
  ('canarytechnologies', 150, 'yc_self_reported', 'Summer 2018'),
  ('canonical', 1175, 'public_records', NULL),
  ('capitalontap', 225, 'public_records', NULL),
  ('capsule', 4, 'yc_self_reported', 'Summer 2022'),
  ('captivateiq', 280, 'yc_self_reported', 'Winter 2018'),
  ('carbonchain', 16, 'yc_self_reported', 'Summer 2020'),
  ('cardboard', 4, 'yc_self_reported', 'Winter 2026'),
  ('cardinal', 3, 'yc_self_reported', 'Winter 2023'),
  ('cardlytics~wd5~CardlyticsExternalCareerSite', 432, 'public_records', NULL),
  ('carvana', 21000, 'public_records', NULL),
  ('casa', 7000, 'public_records', NULL),
  ('casca', 40, 'yc_self_reported', 'Summer 2023'),
  ('cat~wd5~SolarTurbines', 104000, 'public_records', NULL),
  ('cat~wd5~caterpillarcareers', 104000, 'public_records', NULL),
  ('ccc~wd5~ccc_External', 8517, 'public_records', NULL),
  ('centerfield', 2300, 'public_records', NULL),
  ('centerforstrategicandinternationalstudiesinc', 354, 'public_records', NULL),
  ('centrica~wd3~Centrica', 40000, 'public_records', NULL),
  ('cfe', 3074, 'public_records', NULL),
  ('checkr', 800, 'yc_self_reported', 'Summer 2014'),
  ('chevron~wd5~ExternalCareerSite_Private', 48600, 'public_records', NULL),
  ('chowdeck', 14, 'yc_self_reported', 'Summer 2022'),
  ('ciandt', 2500, 'public_records', NULL),
  ('cinder', 30, 'yc_self_reported', 'Winter 2022'),
  ('circle-medical', 235, 'yc_self_reported', 'Summer 2015'),
  ('circleback', 8, 'yc_self_reported', 'Winter 2024'),
  ('circuithub', 58, 'yc_self_reported', 'Winter 2012'),
  ('claim-health', 6, 'yc_self_reported', 'Spring 2025'),
  ('claimsorted', 20, 'yc_self_reported', 'Summer 2024'),
  ('clara', 9, 'yc_self_reported', 'Spring 2026'),
  ('classdojo', 100, 'yc_self_reported', 'Summer 2012'),
  ('clearspace', 7, 'yc_self_reported', 'Winter 2023'),
  ('clever', 210, 'yc_self_reported', 'Summer 2012'),
  ('clintonfoundation', 2000, 'public_records', NULL),
  ('clipboard', 1000, 'yc_self_reported', 'Winter 2017'),
  ('close', 120, 'yc_self_reported', 'Winter 2011'),
  ('cloudflare', 2440, 'public_records', NULL),
  ('coast', 35, 'yc_self_reported', 'Summer 2021'),
  ('codes-health', 25, 'yc_self_reported', 'Summer 2024'),
  ('cohesity~wd5~cohesity_careers', 250, 'public_records', NULL),
  ('coinbase', 6112, 'yc_self_reported', 'Summer 2012'),
  ('cointracker', 70, 'yc_self_reported', 'Winter 2018'),
  ('comena', 8, 'yc_self_reported', 'Summer 2025'),
  ('confido', 65, 'yc_self_reported', 'Summer 2021'),
  ('constellationspace', 4, 'yc_self_reported', 'Winter 2026'),
  ('conveo', 75, 'yc_self_reported', 'Summer 2024'),
  ('copenhagenmalmoport', 375, 'public_records', NULL),
  ('copia', 20, 'yc_self_reported', 'Winter 2016'),
  ('corgi', 200, 'yc_self_reported', 'Summer 2024'),
  ('cortex', 100, 'yc_self_reported', 'Winter 2020'),
  ('cosine', 12, 'yc_self_reported', 'Winter 2023'),
  ('crowdstrike~wd5~crowdstrikecareers', 7925, 'public_records', NULL),
  ('ctgt', 10, 'yc_self_reported', 'Fall 2024'),
  ('cua', 3, 'yc_self_reported', 'Spring 2025'),
  ('culligan', 7500, 'public_records', NULL),
  ('culturebiosciences', 40, 'yc_self_reported', 'Winter 2018'),
  ('curri', 104, 'yc_self_reported', 'Summer 2019'),
  ('cvshealth~wd1~CVS_Health_Careers', 300000, 'public_records', NULL),
  ('dabble', 3, 'yc_self_reported', 'Winter 2015'),
  ('danskespil', 498, 'public_records', NULL),
  ('databricks', 4000, 'public_records', NULL),
  ('dataleap', 6, 'yc_self_reported', 'Summer 2024'),
  ('datev~wd3~Datev_Careers', 8013, 'public_records', NULL),
  ('david-ai', 10, 'yc_self_reported', 'Summer 2024'),
  ('daybreakhealth', 20, 'yc_self_reported', 'Summer 2020'),
  ('dedalus-labs', 10, 'yc_self_reported', 'Summer 2025'),
  ('deepgram', 115, 'yc_self_reported', 'Winter 2016'),
  ('despegar', 4500, 'public_records', NULL),
  ('deutscheextraktkaffeegmbh', 360, 'public_records', NULL),
  ('deutscher-tierschutzbund', 205, 'public_records', NULL),
  ('diageo~wd3~Diageo_Careers', 29860, 'public_records', NULL),
  ('dickssportinggoods~wd1~DSG', 37600, 'public_records', NULL),
  ('digimarc', 216, 'public_records', NULL),
  ('dispatch', 2, 'yc_self_reported', 'Spring 2026'),
  ('ditto', 14, 'yc_self_reported', 'Winter 2020'),
  ('djamo', 250, 'yc_self_reported', 'Winter 2021'),
  ('dnadesign', 1427, 'public_records', NULL),
  ('docker', 201, 'yc_self_reported', 'Summer 2010'),
  ('doctolib', 1800, 'public_records', NULL),
  ('dollartree~wd5~dollartreeus', 145000, 'public_records', NULL),
  ('doppler', 25, 'yc_self_reported', 'Winter 2019'),
  ('drivewhip', 6, 'yc_self_reported', 'Winter 2024'),
  ('dropbox', 4000, 'yc_self_reported', 'Summer 2007'),
  ('duffel', 55, 'yc_self_reported', 'Summer 2018'),
  ('duplo', 13, 'yc_self_reported', 'Winter 2022'),
  ('dupont~wd5~Jobs', 98000, 'public_records', NULL),
  ('dyson~wd3~dyson_careers', 7000, 'public_records', NULL),
  ('easypost-2', 51, 'yc_self_reported', 'Summer 2013'),
  ('echo', 3, 'yc_self_reported', 'Winter 2023'),
  ('ecokedu', 501, 'public_records', NULL),
  ('eleks', 1400, 'public_records', NULL),
  ('elementsolutions', 2000, 'public_records', NULL),
  ('elephantinsurance', 400, 'public_records', NULL),
  ('ello', 45, 'yc_self_reported', 'Winter 2020'),
  ('elringklinger~wd3~External', 6263, 'public_records', NULL),
  ('embark', 2, 'yc_self_reported', 'Summer 2011'),
  ('embarkstudios', 360, 'public_records', NULL),
  ('ember', 25, 'yc_self_reported', 'Fall 2024'),
  ('embraer', 19179, 'public_records', NULL),
  ('ems', 4500, 'public_records', NULL),
  ('enagas~wd3~Portal_Externo', 1344, 'public_records', NULL),
  ('encord', 150, 'yc_self_reported', 'Winter 2021'),
  ('enode', 70, 'yc_self_reported', 'Winter 2021'),
  ('enpal', 1383, 'public_records', NULL),
  ('entrust~wd1~EntrustCareers', 3000, 'public_records', NULL),
  ('enveritas', 60, 'yc_self_reported', 'Summer 2018'),
  ('epsilon3', 12, 'yc_self_reported', 'Summer 2021'),
  ('equifax~wd5~External', 9500, 'public_records', NULL),
  ('equinix~wd1~External', 8378, 'public_records', NULL),
  ('equipmentsharecom', 5400, 'yc_self_reported', 'Winter 2015'),
  ('escape', 29, 'yc_self_reported', 'Winter 2023'),
  ('eset~wd3~ESET_External', 1000, 'public_records', NULL),
  ('esri', 4000, 'public_records', NULL),
  ('euronet', 10800, 'public_records', NULL),
  ('eventual', 18, 'yc_self_reported', 'Winter 2022'),
  ('evry-health', 87, 'yc_self_reported', 'Winter 2018'),
  ('exa', 75, 'yc_self_reported', 'Summer 2021'),
  ('expo', 40, 'yc_self_reported', 'Summer 2016'),
  ('extend', 25, 'yc_self_reported', 'Winter 2023'),
  ('extremenetworks', 2713, 'public_records', NULL),
  ('fable', 2, 'yc_self_reported', 'Winter 2021'),
  ('faire', 900, 'yc_self_reported', 'Winter 2017'),
  ('fampay', 24, 'yc_self_reported', 'Summer 2019'),
  ('fanaticsinc', 22000, 'public_records', NULL),
  ('faradayfuture', 597, 'public_records', NULL),
  ('fashionnova', 6000, 'public_records', NULL),
  ('fathom.video', 95, 'yc_self_reported', 'Winter 2021'),
  ('fedex~wd1~FTN_APAC_External', 400000, 'public_records', NULL),
  ('fedex~wd1~FTN_EMEIA_External', 400000, 'public_records', NULL),
  ('fedex~wd1~FXE-LAC_External_Career_Site', 400000, 'public_records', NULL),
  ('fedex~wd1~FXE-MEISA-External', 400000, 'public_records', NULL),
  ('fedex~wd1~FXE_APAC_External', 400000, 'public_records', NULL),
  ('fedex~wd1~fxe-eu_external', 400000, 'public_records', NULL),
  ('ferrovial~wd3~Ferrovial_Career_Site', 95978, 'public_records', NULL),
  ('fetch', 24, 'yc_self_reported', 'Summer 2015'),
  ('fetchpackage', 24, 'yc_self_reported', 'Summer 2015'),
  ('fieldguide', 180, 'yc_self_reported', 'Summer 2020'),
  ('fielmann~wd3~External', 23412, 'public_records', NULL),
  ('figfinancial', 5, 'yc_self_reported', 'Summer 2020'),
  ('finnair~wd103~finnair', 5918, 'public_records', NULL),
  ('finni-health', 40, 'yc_self_reported', 'Winter 2023'),
  ('finto', 10, 'yc_self_reported', 'Summer 2025'),
  ('firecrawl', 25, 'yc_self_reported', 'Summer 2022'),
  ('fiserv~wd5~EXT', 21000, 'public_records', NULL),
  ('fiskars~wd3~FiskarsGroup', 6595, 'public_records', NULL),
  ('fivetran', 1200, 'yc_self_reported', 'Winter 2013'),
  ('flaschenpost~wd103~flaschenpost', 8000, 'public_records', NULL),
  ('fleek', 100, 'yc_self_reported', 'Winter 2022'),
  ('flex', 147979, 'public_records', NULL),
  ('flexport', 3000, 'yc_self_reported', 'Winter 2014'),
  ('flo', 50, 'yc_self_reported', 'Summer 2019'),
  ('float', 2, 'yc_self_reported', 'Summer 2021'),
  ('float-health', 3, 'yc_self_reported', 'Winter 2022'),
  ('florence', 675, 'public_records', NULL),
  ('flowserve~wd1~applied', 16000, 'public_records', NULL),
  ('flsmidth~wd3~FLS_Global', 7739, 'public_records', NULL),
  ('flutterwavego', 500, 'yc_self_reported', 'Summer 2016'),
  ('focalsystems', 170, 'yc_self_reported', 'Winter 2016'),
  ('formal', 10, 'yc_self_reported', 'Summer 2020'),
  ('formance', 30, 'yc_self_reported', 'Summer 2021'),
  ('fox~wd1~Domestic', 9000, 'public_records', NULL),
  ('fox~wd1~FOXTVST_Central', 9000, 'public_records', NULL),
  ('fox~wd1~FOXTVST_EAST', 9000, 'public_records', NULL),
  ('fox~wd1~FOXTVST_WEST', 9000, 'public_records', NULL),
  ('fresco', 2, 'yc_self_reported', 'Fall 2024'),
  ('freseniusmedicalcare~wd3~fme', 125364, 'public_records', NULL),
  ('frostsullivan', 1800, 'public_records', NULL),
  ('fujifilm~wd3~Regional_External_Career', 75845, 'public_records', NULL),
  ('fulcrum', 2, 'yc_self_reported', 'Summer 2025'),
  ('fullstackacademy', 220, 'yc_self_reported', 'Summer 2012'),
  ('furtherai', 36, 'yc_self_reported', 'Winter 2024'),
  ('future', 2395, 'public_records', NULL),
  ('futurestandard', 600, 'public_records', NULL),
  ('garage', 25, 'yc_self_reported', 'Winter 2024'),
  ('gecko-robotics', 230, 'yc_self_reported', 'Winter 2016'),
  ('gen-digital', 3659, 'public_records', NULL),
  ('generallegalllp', 25, 'yc_self_reported', 'Winter 2026'),
  ('genesys~wd1~Genesys', 3218, 'public_records', NULL),
  ('get-reliance-health', 384, 'yc_self_reported', 'Winter 2017'),
  ('getyourguide', 1000, 'public_records', NULL),
  ('gigs', 150, 'yc_self_reported', 'Winter 2021'),
  ('ginkgobioworks', 641, 'yc_self_reported', 'Summer 2014'),
  ('gitlab', 2000, 'yc_self_reported', 'Winter 2015'),
  ('givecampus', 130, 'yc_self_reported', 'Summer 2015'),
  ('glade', 3, 'yc_self_reported', 'Summer 2023'),
  ('globalfoundries~wd1~External', 14600, 'public_records', NULL),
  ('goatgroup', 1600, 'yc_self_reported', 'Winter 2011'),
  ('gocardless', 900, 'yc_self_reported', 'Summer 2011'),
  ('godaddy', 5990, 'public_records', NULL),
  ('govdash', 56, 'yc_self_reported', 'Winter 2022'),
  ('grai', 3, 'yc_self_reported', 'Summer 2022'),
  ('greptile', 35, 'yc_self_reported', 'Winter 2024'),
  ('grey', 15, 'yc_self_reported', 'Winter 2022'),
  ('gridware', 125, 'yc_self_reported', 'Winter 2021'),
  ('grouper', 11, 'yc_self_reported', 'Winter 2012'),
  ('groupon', 3675, 'public_records', NULL),
  ('gsknch~wd3~GSKCareers', 97921, 'public_records', NULL),
  ('gsk~wd5~GSKCareers', 97921, 'public_records', NULL),
  ('guild', 2, 'yc_self_reported', 'Summer 2026'),
  ('gumloop', 37, 'yc_self_reported', 'Winter 2024'),
  ('gusto', 2400, 'yc_self_reported', 'Winter 2012'),
  ('hackerrank', 300, 'yc_self_reported', 'Summer 2011'),
  ('haemonetics~wd5~HAE', 3300, 'public_records', NULL),
  ('handoff', 20, 'yc_self_reported', 'Winter 2020'),
  ('happyrobot.ai', 80, 'yc_self_reported', 'Summer 2023'),
  ('harnessinc', 1200, 'public_records', NULL),
  ('harrods~wd3~Harrods_External1', 5000, 'public_records', NULL),
  ('hasbro', 5000, 'public_records', NULL),
  ('hatch', 73, 'yc_self_reported', 'Winter 2019'),
  ('hatchcareers', 73, 'yc_self_reported', 'Winter 2019'),
  ('healthsherpa', 220, 'yc_self_reported', 'Summer 2012'),
  ('healthtech-1', 40, 'yc_self_reported', 'Summer 2023'),
  ('heartaerospace', 50, 'yc_self_reported', 'Winter 2019'),
  ('hereio', 9, 'yc_self_reported', 'Summer 2020'),
  ('hexa', 3, 'yc_self_reported', 'Spring 2026'),
  ('hightouch', 200, 'yc_self_reported', 'Summer 2019'),
  ('hive', 65, 'yc_self_reported', 'Summer 2014'),
  ('hntb~wd5~HNTB_Careers', 3500, 'public_records', NULL),
  ('hockeystack', 65, 'yc_self_reported', 'Summer 2023'),
  ('hokali', 12, 'yc_self_reported', 'Winter 2022'),
  ('holidaycheck', 325, 'public_records', NULL),
  ('holywater', 200, 'public_records', NULL),
  ('homebase', 20, 'yc_self_reported', 'Winter 2021'),
  ('hostinger', 1003, 'public_records', NULL),
  ('hputx', 255, 'public_records', NULL),
  ('huaweiaustria', 197000, 'public_records', NULL),
  ('hubspotjobs', 8246, 'public_records', NULL),
  ('hud', 15, 'yc_self_reported', 'Winter 2025'),
  ('hudu', 26, 'yc_self_reported', 'Winter 2021'),
  ('humaans', 48, 'yc_self_reported', 'Winter 2021'),
  ('humana~wd5~Humana_External_Career_Site', 51600, 'public_records', NULL),
  ('humaninterest', 765, 'yc_self_reported', 'Summer 2015'),
  ('humanly', 30, 'yc_self_reported', 'Winter 2020'),
  ('humanrightswatch', 450, 'public_records', NULL),
  ('hyperbound', 30, 'yc_self_reported', 'Summer 2023'),
  ('hypercore', 7, 'yc_self_reported', 'Summer 2021'),
  ('iberdrola~wd3~Iberdrola', 40721, 'public_records', NULL),
  ('icarus', 50, 'yc_self_reported', 'Fall 2025'),
  ('iherb', 3000, 'public_records', NULL),
  ('iliad~wd3~Iliad', 1, 'yc_self_reported', 'Winter 2023'),
  ('illumina~wd1~illumina-careers', 9250, 'public_records', NULL),
  ('ineos~wd503~INEOScareers', 7517, 'public_records', NULL),
  ('infera', 2, 'yc_self_reported', 'Spring 2026'),
  ('infinity-constellation', 15, 'yc_self_reported', 'Winter 2024'),
  ('infisical', 50, 'yc_self_reported', 'Winter 2023'),
  ('innate', 7, 'yc_self_reported', 'Fall 2024'),
  ('instacart', 3000, 'yc_self_reported', 'Summer 2012'),
  ('instadeep', 350, 'public_records', NULL),
  ('instawork', 500, 'yc_self_reported', 'Summer 2015'),
  ('integral', 5500, 'public_records', NULL),
  ('intellecthq', 200, 'yc_self_reported', 'Summer 2021'),
  ('intel~wd1~External', 121100, 'public_records', NULL),
  ('interface-1', 2, 'yc_self_reported', 'Summer 2025'),
  ('intetics-2', 1100, 'public_records', NULL),
  ('ion', 3, 'yc_self_reported', 'Winter 2024'),
  ('ipsen~wd103~Ipsen_Careers', 5300, 'public_records', NULL),
  ('ironcladhq', 700, 'yc_self_reported', 'Summer 2015'),
  ('ivalua', 1105, 'public_records', NULL),
  ('jitsu', 4, 'yc_self_reported', 'Summer 2020'),
  ('jj~wd5~JJ', 136400, 'public_records', NULL),
  ('jj~wd5~NonCompetetiveHiring', 136400, 'public_records', NULL),
  ('jj~wd5~displacedemployees', 136400, 'public_records', NULL),
  ('jobs-valence', 3, 'yc_self_reported', 'Winter 2026'),
  ('joinparadigm', 8, 'yc_self_reported', 'Winter 2024'),
  ('jotun~wd3~Jotun_careers', 10000, 'public_records', NULL),
  ('journey', 10, 'yc_self_reported', 'Winter 2021'),
  ('juicebox', 65, 'yc_self_reported', 'Summer 2022'),
  ('julius', 10, 'yc_self_reported', 'Summer 2022'),
  ('jumia', 4000, 'public_records', NULL),
  ('junction', 19, 'yc_self_reported', 'Winter 2020'),
  ('juno', 2, 'yc_self_reported', 'Spring 2026'),
  ('kaipod-learning', 27, 'yc_self_reported', 'Summer 2021'),
  ('kao', 5652, 'public_records', NULL),
  ('kapsch~wd3~onestepahead-Spain', 5484, 'public_records', NULL),
  ('kapsch~wd3~onestepahead_Austria', 5484, 'public_records', NULL),
  ('kapsch~wd3~onestepahead_NAM', 5484, 'public_records', NULL),
  ('kastle', 10, 'yc_self_reported', 'Summer 2024'),
  ('kbr~wd5~KBR_Careers', 27000, 'public_records', NULL),
  ('keolis', 65000, 'public_records', NULL),
  ('kernalbio', 20, 'yc_self_reported', 'Summer 2020'),
  ('keskosenukailatvia', 927, 'public_records', NULL),
  ('kiesertrainingag', 1600, 'public_records', NULL),
  ('kingdom', 18, 'yc_self_reported', 'Summer 2020'),
  ('kiwi-com', 877, 'public_records', NULL),
  ('klarity-ai', 128, 'yc_self_reported', 'Summer 2018'),
  ('kodex', 30, 'yc_self_reported', 'Summer 2021'),
  ('kombo', 20, 'yc_self_reported', 'Summer 2022'),
  ('kyivstar', 4000, 'public_records', NULL),
  ('lago', 45, 'yc_self_reported', 'Summer 2021'),
  ('laika', 500, 'yc_self_reported', 'Summer 2019'),
  ('lancedb', 35, 'yc_self_reported', 'Winter 2022'),
  ('langdock', 50, 'yc_self_reported', 'Summer 2023'),
  ('larian', 450, 'public_records', NULL),
  ('latent', 50, 'yc_self_reported', 'Winter 2023'),
  ('lattice', 540, 'yc_self_reported', 'Winter 2016'),
  ('layup', 3, 'yc_self_reported', 'Winter 2023'),
  ('legacy', 35, 'yc_self_reported', 'Summer 2019'),
  ('legalist', 40, 'yc_self_reported', 'Summer 2016'),
  ('legionhealth', 11, 'yc_self_reported', 'Summer 2021'),
  ('legora', 400, 'yc_self_reported', 'Winter 2024'),
  ('lemfi', 500, 'yc_self_reported', 'Summer 2021'),
  ('leroymerlinpoland', 10406, 'public_records', NULL),
  ('levitate', 200, 'public_records', NULL),
  ('lgelectronics', 90578, 'public_records', NULL),
  ('linc', 3, 'yc_self_reported', 'Summer 2023'),
  ('lio', 80, 'yc_self_reported', 'Summer 2023'),
  ('litellm', 10, 'yc_self_reported', 'Winter 2023'),
  ('litmus', 4, 'yc_self_reported', 'Summer 2026'),
  ('liveperson', 1231, 'public_records', NULL),
  ('lob', 150, 'yc_self_reported', 'Summer 2013'),
  ('logitech~wd5~Logitech', 7300, 'public_records', NULL),
  ('lokalise', 250, 'public_records', NULL),
  ('lucidmotors', 6500, 'public_records', NULL),
  ('luminai', 31, 'yc_self_reported', 'Summer 2020'),
  ('lunaroutpost', 200, 'public_records', NULL),
  ('mable', 7, 'yc_self_reported', 'Summer 2021'),
  ('mach9', 25, 'yc_self_reported', 'Summer 2021'),
  ('maersk~wd3~APMT_Careers', 80220, 'public_records', NULL),
  ('maersk~wd3~MCI_Careers', 80220, 'public_records', NULL),
  ('maersk~wd3~Maersk_Careers', 80220, 'public_records', NULL),
  ('maersk~wd3~Maersk_Manual', 80220, 'public_records', NULL),
  ('magicpatterns', 10, 'yc_self_reported', 'Winter 2023'),
  ('magnetic', 10, 'yc_self_reported', 'Summer 2025'),
  ('malwarebytes', 800, 'public_records', NULL),
  ('manara', 10, 'yc_self_reported', 'Winter 2021'),
  ('mango~wd3~Mango_Work_Your_Passion', 16000, 'public_records', NULL),
  ('marqvision', 200, 'yc_self_reported', 'Summer 2021'),
  ('marshmallow', 220, 'public_records', NULL),
  ('mars~wd3~External', 80000, 'public_records', NULL),
  ('mashgin', 150, 'yc_self_reported', 'Winter 2015'),
  ('mastercard~wd1~Campus', 33400, 'public_records', NULL),
  ('mastercard~wd1~CorporateCareers', 33400, 'public_records', NULL),
  ('mastra', 30, 'yc_self_reported', 'Winter 2025'),
  ('materion~wd5~Materion', 3100, 'public_records', NULL),
  ('mattermost', 120, 'yc_self_reported', 'Summer 2012'),
  ('mayflower', 2, 'yc_self_reported', 'Fall 2025'),
  ('maymobility', 260, 'yc_self_reported', 'Summer 2017'),
  ('mckesson~wd3~CoverMyMeds_External_Careers', 68000, 'public_records', NULL),
  ('mckesson~wd3~External_Careers', 68000, 'public_records', NULL),
  ('mckesson~wd3~scri_careers', 68000, 'public_records', NULL),
  ('mckesson~wd3~sourcer_on_req', 68000, 'public_records', NULL),
  ('mcmurry', 270, 'public_records', NULL),
  ('meadow', 14, 'yc_self_reported', 'Winter 2015'),
  ('medmehealth', 60, 'yc_self_reported', 'Winter 2021'),
  ('mednet', 35, 'yc_self_reported', 'Winter 2017'),
  ('medtronic~wd1~MedtronicCareers', 86000, 'public_records', NULL),
  ('medtronic~wd1~redeploymentmedtroniccareers', 86000, 'public_records', NULL),
  ('meesho', 1450, 'yc_self_reported', 'Summer 2016'),
  ('megaport', 349, 'public_records', NULL),
  ('mem0', 10, 'yc_self_reported', 'Summer 2024'),
  ('mercura', 20, 'yc_self_reported', 'Winter 2025'),
  ('mesta', 1584, 'public_records', NULL),
  ('metriport', 26, 'yc_self_reported', 'Summer 2022'),
  ('middesk', 130, 'yc_self_reported', 'Winter 2019'),
  ('middleburycollege', 1190, 'public_records', NULL),
  ('miele~wd3~miele-jobs', 20100, 'public_records', NULL),
  ('mindbody', 1337, 'public_records', NULL),
  ('mindvalley', 202, 'public_records', NULL),
  ('minerva', 5, 'yc_self_reported', 'Spring 2025'),
  ('mintlify', 55, 'yc_self_reported', 'Winter 2022'),
  ('mito', 3, 'yc_self_reported', 'Summer 2020'),
  ('mixpanel', 410, 'yc_self_reported', 'Summer 2009'),
  ('modal', 18, 'yc_self_reported', 'Winter 2016'),
  ('modernhealth', 375, 'yc_self_reported', 'Winter 2018'),
  ('moderntreasury', 160, 'yc_self_reported', 'Summer 2018'),
  ('moleskine', 420, 'public_records', NULL),
  ('mongodb', 5640, 'public_records', NULL),
  ('morningstar~wd5~Americas', 9556, 'public_records', NULL),
  ('morningstar~wd5~MorningstarDBRS', 9556, 'public_records', NULL),
  ('morningstar~wd5~Technology-and-Development', 9556, 'public_records', NULL),
  ('moss', 5, 'yc_self_reported', 'Fall 2025'),
  ('motor-coach-industries', 2300, 'public_records', NULL),
  ('mullerinc', 33635, 'public_records', NULL),
  ('multiverse', 9, 'yc_self_reported', 'Winter 2020'),
  ('mutiny', 20, 'yc_self_reported', 'Summer 2018'),
  ('myheritage', 430, 'public_records', NULL),
  ('myparadigm', 8, 'yc_self_reported', 'Winter 2024'),
  ('nabis', 300, 'yc_self_reported', 'Winter 2019'),
  ('nabla', 8, 'yc_self_reported', 'Summer 2020'),
  ('nalamoney', 168, 'yc_self_reported', 'Winter 2019'),
  ('nanonets', 102, 'yc_self_reported', 'Winter 2017'),
  ('nasdaq~wd1~Global_External_Site', 8809, 'public_records', NULL),
  ('ncr~wd1~ext_apac', 21500, 'public_records', NULL),
  ('ncr~wd1~ext_jp', 21500, 'public_records', NULL),
  ('ncr~wd1~ext_non_us', 21500, 'public_records', NULL),
  ('ncr~wd1~ext_us', 21500, 'public_records', NULL),
  ('nectar', 7, 'yc_self_reported', 'Summer 2023'),
  ('neo-gg', 207, 'public_records', NULL),
  ('netomi', 3, 'yc_self_reported', 'Winter 2016'),
  ('neuralink', 300, 'public_records', NULL),
  ('new-story', 20, 'yc_self_reported', 'Summer 2015'),
  ('nex', 5, 'yc_self_reported', 'Summer 2026'),
  ('nextdoor', 704, 'public_records', NULL),
  ('nexu', 63, 'yc_self_reported', 'Winter 2020'),
  ('ngc~wd1~Northrop_Grumman_External_Site', 65600, 'public_records', NULL),
  ('nike~wd1~nke', 76700, 'public_records', NULL),
  ('nintendo', 7317, 'public_records', NULL),
  ('noorahealth', 500, 'yc_self_reported', 'Winter 2014'),
  ('norgesgruppen~wd3~karriere', 28000, 'public_records', NULL),
  ('north-park-university', 752, 'public_records', NULL),
  ('notabene', 47, 'yc_self_reported', 'Summer 2020'),
  ('nourish', 250, 'yc_self_reported', 'Winter 2021'),
  ('novacredit', 100, 'yc_self_reported', 'Summer 2016'),
  ('novig', 55, 'yc_self_reported', 'Summer 2022'),
  ('novonordiskfoundation', 295, 'public_records', NULL),
  ('nox-metals', 27, 'yc_self_reported', 'Summer 2025'),
  ('numeral', 100, 'yc_self_reported', 'Winter 2023'),
  ('nursing-float-health', 3, 'yc_self_reported', 'Winter 2022'),
  ('nvidia~wd5~NVIDIAExternalCareerSite', 13775, 'public_records', NULL),
  ('observeai', 240, 'yc_self_reported', 'Winter 2018'),
  ('obsidiansecuritycareers', 11800, 'public_records', NULL),
  ('odeko', 371, 'yc_self_reported', 'Summer 2019'),
  ('odin', 4, 'yc_self_reported', 'Summer 2019'),
  ('odys-aviation', 11, 'yc_self_reported', 'Summer 2021'),
  ('offdeal', 15, 'yc_self_reported', 'Winter 2024'),
  ('ogilvy', 17500, 'public_records', NULL),
  ('oklo', 50, 'yc_self_reported', 'Summer 2014'),
  ('omni', 5, 'yc_self_reported', 'Summer 2020'),
  ('onebrief', 200, 'yc_self_reported', 'Summer 2021'),
  ('oneleet', 60, 'yc_self_reported', 'Summer 2022'),
  ('openai', 4500, 'public_records', NULL),
  ('opencall', 7, 'yc_self_reported', 'Winter 2024'),
  ('openwork', 4, 'yc_self_reported', 'Spring 2026'),
  ('ophelia', 130, 'yc_self_reported', 'Winter 2020'),
  ('orbital-operations', 2, 'yc_self_reported', 'Winter 2025'),
  ('ouryahoo~wd5~careers', 14000, 'public_records', NULL),
  ('output', 6, 'yc_self_reported', 'Summer 2021'),
  ('outschool', 107, 'yc_self_reported', 'Winter 2016'),
  ('outset', 30, 'yc_self_reported', 'Summer 2023'),
  ('overview', 40, 'yc_self_reported', 'Winter 2019'),
  ('pagerduty', 950, 'yc_self_reported', 'Summer 2010'),
  ('pairteam', 500, 'yc_self_reported', 'Summer 2019'),
  ('panorama-education', 350, 'yc_self_reported', 'Summer 2013'),
  ('papa', 500, 'yc_self_reported', 'Summer 2018'),
  ('paradox-interactive', 479, 'public_records', NULL),
  ('parallellearning', 15, 'yc_self_reported', 'Winter 2024'),
  ('pasha-holding', 9500, 'public_records', NULL),
  ('pathcrisis', 12, 'yc_self_reported', 'Summer 2019'),
  ('path~wd1~External', 12, 'yc_self_reported', 'Summer 2019'),
  ('pelago', 180, 'yc_self_reported', 'Winter 2018'),
  ('people-ai', 300, 'yc_self_reported', 'Summer 2016'),
  ('permitflow', 80, 'yc_self_reported', 'Winter 2022'),
  ('permutive', 205, 'yc_self_reported', 'Summer 2014'),
  ('pfizer~wd1~PfizerCareers', 88300, 'public_records', NULL),
  ('pfizer~wd1~internaljobs', 88300, 'public_records', NULL),
  ('phoenix', 70, 'yc_self_reported', 'Winter 2021'),
  ('phoenixcontact', 20300, 'public_records', NULL),
  ('phonely', 10, 'yc_self_reported', 'Summer 2024'),
  ('phonic', 8, 'yc_self_reported', 'Winter 2020'),
  ('photoroom', 100, 'yc_self_reported', 'Summer 2020'),
  ('pimco~wd1~pimco-careers', 2462, 'public_records', NULL),
  ('pinnacle', 2, 'yc_self_reported', 'Summer 2024'),
  ('pinterest', 3225, 'public_records', NULL),
  ('pirros', 44, 'yc_self_reported', 'Winter 2023'),
  ('pitchbookdata', 3000, 'public_records', NULL),
  ('plane', 30, 'yc_self_reported', 'Winter 2017'),
  ('platformsh', 291, 'public_records', NULL),
  ('playground', 3, 'yc_self_reported', 'Summer 2019'),
  ('plume', 4, 'yc_self_reported', 'Summer 2024'),
  ('pluxee~wd3~Pluxee_Career_Site', 5000, 'public_records', NULL),
  ('podium81', 1000, 'yc_self_reported', 'Winter 2016'),
  ('pointone', 15, 'yc_self_reported', 'Winter 2024'),
  ('polpharma~wd3~Polpharma', 6250, 'public_records', NULL),
  ('polpharma~wd3~Santo_Careers', 6250, 'public_records', NULL),
  ('popeyes', 2130, 'public_records', NULL),
  ('popl', 60, 'yc_self_reported', 'Winter 2021'),
  ('porter', 18, 'yc_self_reported', 'Summer 2020'),
  ('posh', 10, 'yc_self_reported', 'Winter 2022'),
  ('posthog', 150, 'yc_self_reported', 'Winter 2020'),
  ('postscript', 180, 'yc_self_reported', 'Winter 2019'),
  ('povio', 250, 'yc_self_reported', 'Winter 2014'),
  ('powerus', 80, 'yc_self_reported', 'Summer 2020'),
  ('powerx', 20, 'yc_self_reported', 'Winter 2020'),
  ('prelim', 49, 'yc_self_reported', 'Summer 2017'),
  ('primer', 2, 'yc_self_reported', 'Fall 2025'),
  ('probablygenetic', 17, 'yc_self_reported', 'Winter 2019'),
  ('prodigal', 65, 'yc_self_reported', 'Summer 2018'),
  ('prolific', 180, 'yc_self_reported', 'Summer 2019'),
  ('promise', 80, 'yc_self_reported', 'Winter 2018'),
  ('prompt', 1, 'yc_self_reported', 'Summer 2019'),
  ('pronto', 62, 'yc_self_reported', 'Winter 2019'),
  ('prose', 3, 'yc_self_reported', 'Spring 2026'),
  ('prospa', 70, 'yc_self_reported', 'Winter 2021'),
  ('prosper', 9, 'yc_self_reported', 'Summer 2023'),
  ('prox', 7, 'yc_self_reported', 'Fall 2025'),
  ('prudential~wd3~prudential', 22308, 'public_records', NULL),
  ('prudential~wd3~prudential_eastspring', 22308, 'public_records', NULL),
  ('puma~wd502~Jobs_at_Puma', 18668, 'public_records', NULL),
  ('puma~wd502~Work_at_stichd', 18668, 'public_records', NULL),
  ('pumpcareers', 75, 'yc_self_reported', 'Summer 2022'),
  ('pyka', 75, 'yc_self_reported', 'Summer 2017'),
  ('q-ctrl', 215, 'public_records', NULL),
  ('qonto', 1600, 'public_records', NULL),
  ('quicknode', 115, 'yc_self_reported', 'Winter 2021'),
  ('quindar', 57, 'yc_self_reported', 'Summer 2022'),
  ('qventus', 230, 'yc_self_reported', 'Winter 2015'),
  ('radar', 120, 'yc_self_reported', 'Winter 2013'),
  ('raindrop', 9, 'yc_self_reported', 'Winter 2024'),
  ('rainforest-pay', 40, 'yc_self_reported', 'Summer 2012'),
  ('rand~wd5~External_Career_Site', 1850, 'public_records', NULL),
  ('rappi~wd12~Rappi_jobs', 4800, 'yc_self_reported', 'Winter 2016'),
  ('raptor-maps-inc', 75, 'yc_self_reported', 'Summer 2016'),
  ('ratp~wd3~RATP_Externe', 55545, 'public_records', NULL),
  ('raven', 4, 'yc_self_reported', 'Summer 2022'),
  ('raya', 1700, 'public_records', NULL),
  ('readme', 52, 'yc_self_reported', 'Winter 2015'),
  ('ready', 60, 'yc_self_reported', 'Summer 2020'),
  ('realitydefender', 54, 'yc_self_reported', 'Winter 2022'),
  ('reddit', 2000, 'yc_self_reported', 'Summer 2005'),
  ('reducto', 30, 'yc_self_reported', 'Winter 2024'),
  ('reflex', 10, 'yc_self_reported', 'Winter 2023'),
  ('regent', 40, 'yc_self_reported', 'Winter 2021'),
  ('relativity', 2500, 'yc_self_reported', 'Winter 2016'),
  ('relaygraduateschoolofeducation', 409, 'public_records', NULL),
  ('remi', 170, 'yc_self_reported', 'Winter 2022'),
  ('remoracarbon', 45, 'yc_self_reported', 'Winter 2021'),
  ('replit', 65, 'yc_self_reported', 'Winter 2018'),
  ('repsol~wd3~Repsol', 23810, 'public_records', NULL),
  ('repsol~wd3~ref_ext', 23810, 'public_records', NULL),
  ('rescale', 250, 'yc_self_reported', 'Winter 2012'),
  ('resend', 45, 'yc_self_reported', 'Winter 2023'),
  ('resolve', 10, 'yc_self_reported', 'Winter 2015'),
  ('retell-ai', 50, 'yc_self_reported', 'Winter 2024'),
  ('revel', 16, 'yc_self_reported', 'Summer 2019'),
  ('revenuecat', 150, 'yc_self_reported', 'Summer 2018'),
  ('rex', 2, 'yc_self_reported', 'Summer 2026'),
  ('rigetti', 51, 'yc_self_reported', 'Summer 2014'),
  ('riotgames', 2500, 'public_records', NULL),
  ('rivet', 5, 'yc_self_reported', 'Winter 2023'),
  ('roboflow', 100, 'yc_self_reported', 'Summer 2020'),
  ('rollsroyce~wd3~Intern_Graduate', 54500, 'public_records', NULL),
  ('rollsroyce~wd3~professional', 54500, 'public_records', NULL),
  ('rollsroyce~wd3~rrpowersystems', 54500, 'public_records', NULL),
  ('rollsroyce~wd3~rrpowersystemsearlycareer', 54500, 'public_records', NULL),
  ('roofr', 40, 'yc_self_reported', 'Summer 2017'),
  ('rovi~wd3~ROVI_Careers', 1419, 'public_records', NULL),
  ('sable', 12, 'yc_self_reported', 'Summer 2019'),
  ('sacyr', 15529, 'public_records', NULL),
  ('sagecare', 3, 'yc_self_reported', 'Summer 2024'),
  ('salesforce~wd12~External_Career_Site', 35000, 'public_records', NULL),
  ('salesforce~wd12~Mulesoft_Careersite', 35000, 'public_records', NULL),
  ('salesforce~wd12~Slack', 35000, 'public_records', NULL),
  ('salient', 40, 'yc_self_reported', 'Winter 2023'),
  ('saltsecurity', 200, 'yc_self_reported', 'Winter 2016'),
  ('sandoz~wd103~Sandoz_Careers', 5724, 'public_records', NULL),
  ('sanofi~wd3~SanofiCareers', 106566, 'public_records', NULL),
  ('sanoma~wd3~Sanoma_Learning', 15405, 'public_records', NULL),
  ('santander~wd3~SantanderCareers', 902, 'public_records', NULL),
  ('scaleai', 500, 'yc_self_reported', 'Summer 2016'),
  ('scentbird', 165, 'yc_self_reported', 'Summer 2015'),
  ('schuberth', 300, 'public_records', NULL),
  ('scribe', 15, 'yc_self_reported', 'Winter 2017'),
  ('sdworxnv', 1900, 'public_records', NULL),
  ('seed', 11, 'yc_self_reported', 'Winter 2015'),
  ('sendbird', 300, 'yc_self_reported', 'Winter 2016'),
  ('sfaf', 261, 'public_records', NULL),
  ('shadeform', 11, 'yc_self_reported', 'Summer 2023'),
  ('sharp~wd1~External', 50253, 'public_records', NULL),
  ('shell~wd3~shellcareers', 90000, 'public_records', NULL),
  ('sherpa', 2, 'yc_self_reported', 'Spring 2026'),
  ('shipbobinc', 1, 'yc_self_reported', 'Summer 2014'),
  ('signoz', 38, 'yc_self_reported', 'Winter 2021'),
  ('sila', 2, 'yc_self_reported', 'Winter 2026'),
  ('silananotechnologies', 2, 'yc_self_reported', 'Winter 2026'),
  ('simetrik', 350, 'yc_self_reported', 'Winter 2018'),
  ('similarweb', 1017, 'public_records', NULL),
  ('simon~wd1~Simon', 4000, 'public_records', NULL),
  ('simple-ai', 11, 'yc_self_reported', 'Summer 2024'),
  ('singlestore', 150, 'yc_self_reported', 'Winter 2011'),
  ('sirius', 8300, 'public_records', NULL),
  ('skechers~wd5~One-career-site', 9800, 'public_records', NULL),
  ('sketchdeck', 20, 'yc_self_reported', 'Winter 2014'),
  ('skillsoft', 2400, 'public_records', NULL),
  ('skip', 2, 'yc_self_reported', 'Winter 2018'),
  ('skydropx', 320, 'yc_self_reported', 'Summer 2018'),
  ('skylink', 22, 'yc_self_reported', 'Winter 2022'),
  ('skyways', 33, 'yc_self_reported', 'Summer 2017'),
  ('slite', 40, 'yc_self_reported', 'Winter 2018'),
  ('smartasset', 210, 'yc_self_reported', 'Summer 2012'),
  ('snapmagic', 23, 'yc_self_reported', 'Summer 2015'),
  ('snappr', 250, 'yc_self_reported', 'Winter 2017'),
  ('snowflake', 1400, 'public_records', NULL),
  ('sola', 5, 'yc_self_reported', 'Summer 2023'),
  ('solva', 15, 'yc_self_reported', 'Summer 2025'),
  ('solveintelligence', 50, 'yc_self_reported', 'Summer 2023'),
  ('sonaca~wd103~Sonaca_Careers', 6900, 'public_records', NULL),
  ('sonia', 7, 'yc_self_reported', 'Winter 2024'),
  ('soundboks', 50, 'yc_self_reported', 'Winter 2016'),
  ('sourcefit', 2000, 'public_records', NULL),
  ('spacex', 22000, 'public_records', NULL),
  ('spade', 30, 'yc_self_reported', 'Winter 2022'),
  ('spark', 5, 'yc_self_reported', 'Winter 2024'),
  ('speak', 40, 'yc_self_reported', 'Winter 2017'),
  ('sphere', 7, 'yc_self_reported', 'Winter 2022'),
  ('sphinx', 14, 'yc_self_reported', 'Fall 2024'),
  ('spotlight', 4, 'yc_self_reported', 'Summer 2025'),
  ('sproutsocial', 1421, 'public_records', NULL),
  ('squad', 10, 'yc_self_reported', 'Winter 2018'),
  ('square-enix', 5077, 'public_records', NULL),
  ('stable', 30, 'yc_self_reported', 'Winter 2020'),
  ('starcloud', 12, 'yc_self_reported', 'Summer 2024'),
  ('starling-bank', 5, 'yc_self_reported', 'Winter 2022'),
  ('stelco~wd3~Stelco', 2285, 'public_records', NULL),
  ('stellar', 3, 'yc_self_reported', 'Summer 2022'),
  ('stepful', 100, 'yc_self_reported', 'Summer 2021'),
  ('stokespacetechnologies', 305, 'yc_self_reported', 'Winter 2021'),
  ('storebrand~wd3~Storebrand_Careers', 2541, 'public_records', NULL),
  ('stream', 15, 'yc_self_reported', 'Summer 2022'),
  ('stripe', 7000, 'yc_self_reported', 'Summer 2009'),
  ('stryker~wd1~StrykerCareers', 22000, 'public_records', NULL),
  ('subsets', 7, 'yc_self_reported', 'Summer 2023'),
  ('substack', 90, 'yc_self_reported', 'Winter 2018'),
  ('suger', 50, 'yc_self_reported', 'Winter 2023'),
  ('supabase', 120, 'yc_self_reported', 'Summer 2020'),
  ('supermetricsoy', 400, 'public_records', NULL),
  ('superside', 850, 'yc_self_reported', 'Winter 2016'),
  ('suse~wd3~Jobsatsuse', 2000, 'public_records', NULL),
  ('swarovski~wd3~swarovski', 32000, 'public_records', NULL),
  ('swift~wd3~Join-Swift', 3240, 'public_records', NULL),
  ('swisscom~wd103~SwisscomExternalCareers', 21125, 'public_records', NULL),
  ('swisscom~wd103~cablexExternalCareers', 21125, 'public_records', NULL),
  ('switchboard', 24, 'yc_self_reported', 'Winter 2019'),
  ('syncro', 1, 'yc_self_reported', 'Winter 2020'),
  ('sysco~wd5~syscocareers', 67001, 'public_records', NULL),
  ('tailor', 40, 'yc_self_reported', 'Summer 2022'),
  ('tajir', 50, 'yc_self_reported', 'Winter 2020'),
  ('taktile', 150, 'yc_self_reported', 'Summer 2020'),
  ('target~wd5~targetcareers', 400000, 'public_records', NULL),
  ('tavus', 40, 'yc_self_reported', 'Summer 2021'),
  ('techem~wd3~TechemGermanyExternalCareerSiteAllJobs', 3420, 'public_records', NULL),
  ('tegnainc', 6200, 'public_records', NULL),
  ('telenorsharedservices', 20000, 'public_records', NULL),
  ('telenorsweden', 1782, 'public_records', NULL),
  ('teleo', 30, 'yc_self_reported', 'Winter 2020'),
  ('teleperformance~wd1~allianceone', 300000, 'public_records', NULL),
  ('teleport-careers', 255, 'yc_self_reported', 'Summer 2015'),
  ('telli', 16, 'yc_self_reported', 'Fall 2024'),
  ('tencent~wd1~Lightspeed', 62885, 'public_records', NULL),
  ('tencent~wd1~OA_Huoshui_Platform', 62885, 'public_records', NULL),
  ('tencent~wd1~Tencent_Careers', 62885, 'public_records', NULL),
  ('tennr', 205, 'yc_self_reported', 'Winter 2023'),
  ('tetrascience', 100, 'yc_self_reported', 'Summer 2015'),
  ('thales', 261, 'public_records', NULL),
  ('the-exploration-company', 500, 'public_records', NULL),
  ('theathletic', 600, 'yc_self_reported', 'Summer 2016'),
  ('themosaiccompany', 8400, 'public_records', NULL),
  ('thenewyorktimes', 1700, 'public_records', NULL),
  ('thequalitygroupgmbh1', 900, 'public_records', NULL),
  ('thequalitygroupgmbh2', 900, 'public_records', NULL),
  ('thesignalgroup', 1900, 'public_records', NULL),
  ('thndr', 235, 'yc_self_reported', 'Summer 2020'),
  ('tiaa~wd1~Search', 12950, 'public_records', NULL),
  ('toku', 150, 'yc_self_reported', 'Summer 2021'),
  ('topline-pro', 28, 'yc_self_reported', 'Winter 2021'),
  ('torus', 5, 'yc_self_reported', 'Summer 2026'),
  ('tovala', 375, 'yc_self_reported', 'Winter 2016'),
  ('toyota~wd503~TLAC', 359542, 'public_records', NULL),
  ('trafigura~wd3~ImpalaCareerSite', 4316, 'public_records', NULL),
  ('trafigura~wd3~Puma_Energy_Careers', 4316, 'public_records', NULL),
  ('trafigura~wd3~TrafiguraCareerSite', 4316, 'public_records', NULL),
  ('transfergo', 235, 'public_records', NULL),
  ('treehouse~wd1~TreeHouseCareers', 101, 'yc_self_reported', 'Summer 2008'),
  ('trellis', 5, 'yc_self_reported', 'Spring 2026'),
  ('tremendous', 150, 'yc_self_reported', 'Winter 2011'),
  ('trimble~wd1~TrimbleCareers', 4400, 'public_records', NULL),
  ('triomics', 50, 'yc_self_reported', 'Winter 2021'),
  ('trm-labs', 400, 'yc_self_reported', 'Summer 2019'),
  ('turion-space', 15, 'yc_self_reported', 'Summer 2021'),
  ('twenty', 11, 'yc_self_reported', 'Summer 2023'),
  ('twitch', 2000, 'yc_self_reported', 'Winter 2007'),
  ('uipath', 4000, 'public_records', NULL),
  ('understoodcare', 7, 'yc_self_reported', 'Summer 2024'),
  ('unilever~wd3~TMICC', 148000, 'public_records', NULL),
  ('unilever~wd3~UK_TemporaryWorkersite', 148000, 'public_records', NULL),
  ('unilever~wd3~Unilever_Early_Careers', 148000, 'public_records', NULL),
  ('unilever~wd3~Unilever_Experienced_Professionals', 148000, 'public_records', NULL),
  ('united-talent-agency', 900, 'public_records', NULL),
  ('universe', 25, 'yc_self_reported', 'Winter 2018'),
  ('unusual', 4, 'yc_self_reported', 'Fall 2024'),
  ('upcodes', 35, 'yc_self_reported', 'Summer 2017'),
  ('upequity', 90, 'yc_self_reported', 'Summer 2019'),
  ('upkeep', 150, 'yc_self_reported', 'Winter 2017'),
  ('uplane', 19, 'yc_self_reported', 'Fall 2025'),
  ('upstream', 7, 'yc_self_reported', 'Summer 2023'),
  ('usekernel', 6, 'yc_self_reported', 'Summer 2025'),
  ('usenourish', 250, 'yc_self_reported', 'Winter 2021'),
  ('usgnorthamerica', 14414, 'public_records', NULL),
  ('usul', 15, 'yc_self_reported', 'Summer 2024'),
  ('va-q-tec-ag', 340, 'public_records', NULL),
  ('value-virtual-assistants', 100, 'yc_self_reported', 'Winter 2015'),
  ('vanta', 700, 'yc_self_reported', 'Winter 2018'),
  ('vapi', 50, 'yc_self_reported', 'Winter 2021'),
  ('vaynermedia', 600, 'public_records', NULL),
  ('vector', 20, 'yc_self_reported', 'Winter 2023'),
  ('veidekke', 8200, 'public_records', NULL),
  ('velcro~wd5~Velcro', 3500, 'public_records', NULL),
  ('velux~wd3~Velux_Commercial', 12000, 'public_records', NULL),
  ('velux~wd3~Velux_Residential', 12000, 'public_records', NULL),
  ('veriff', 5, 'yc_self_reported', 'Winter 2018'),
  ('verisign', 1019, 'public_records', NULL),
  ('versemedical', 200, 'yc_self_reported', 'Summer 2018'),
  ('verto', 170, 'yc_self_reported', 'Winter 2019'),
  ('vetcove', 83, 'yc_self_reported', 'Summer 2016'),
  ('vibe', 2, 'yc_self_reported', 'Summer 2024'),
  ('vicpd', 349, 'public_records', NULL),
  ('visa', 31600, 'public_records', NULL),
  ('voize', 140, 'yc_self_reported', 'Winter 2022'),
  ('vooma', 30, 'yc_self_reported', 'Winter 2023'),
  ('vori', 29, 'yc_self_reported', 'Winter 2020'),
  ('vouch-inc', 190, 'yc_self_reported', 'Summer 2019'),
  ('voxmedia', 800, 'public_records', NULL),
  ('wafer', 6, 'yc_self_reported', 'Summer 2025'),
  ('wallbit', 17, 'yc_self_reported', 'Winter 2023'),
  ('wallbox', 1400, 'public_records', NULL),
  ('wargamingen', 4500, 'public_records', NULL),
  ('warhorsestudios', 220, 'public_records', NULL),
  ('warp', 80, 'yc_self_reported', 'Winter 2023'),
  ('wavemm1', 1600, 'yc_self_reported', 'Winter 2012'),
  ('waymo', 2500, 'public_records', NULL),
  ('webflow', 600, 'yc_self_reported', 'Summer 2013'),
  ('weleda~wd3~weleda_jobs', 2512, 'public_records', NULL),
  ('westlake~wd1~westlake', 2200, 'public_records', NULL),
  ('westlibertyuniversity', 416, 'public_records', NULL),
  ('wf~wd1~wellsfargojobs', 150500, 'public_records', NULL),
  ('wf~wd1~wellsfargojobstargeted', 150500, 'public_records', NULL),
  ('wikimedia', 700, 'public_records', NULL),
  ('wildbrain', 1000, 'public_records', NULL),
  ('willamalanedistrict', 327, 'public_records', NULL),
  ('withclutch', 2, 'yc_self_reported', 'Summer 2011'),
  ('withpulley', 68, 'yc_self_reported', 'Winter 2020'),
  ('workday~wd5~Workday', 20000, 'public_records', NULL),
  ('worldpay~wd5~worldpay_external_careers_site', 4500, 'public_records', NULL),
  ('wpp', 109000, 'public_records', NULL),
  ('writesonic', 35, 'yc_self_reported', 'Summer 2021'),
  ('xendit', 700, 'yc_self_reported', 'Summer 2015'),
  ('xpengmotors', 13550, 'public_records', NULL),
  ('xylem~wd5~xylem-careers', 17800, 'public_records', NULL),
  ('ycombinator', 21, 'yc_self_reported', 'Winter 2021'),
  ('yotta', 8, 'yc_self_reported', 'Summer 2020'),
  ('ysoftcorporation', 211, 'public_records', NULL),
  ('zapier', 700, 'yc_self_reported', 'Summer 2012'),
  ('zeit-ai', 9, 'yc_self_reported', 'Summer 2024'),
  ('zencoder', 11, 'yc_self_reported', 'Winter 2010'),
  ('zentiva~wd3~Zentiva', 1198, 'public_records', NULL),
  ('zeppelin~wd3~careers', 8502, 'public_records', NULL),
  ('zeppelin~wd3~sitech-careers', 8502, 'public_records', NULL),
  ('zerocater', 140, 'yc_self_reported', 'Winter 2011'),
  ('ziina', 57, 'yc_self_reported', 'Winter 2021'),
  ('zip', 500, 'yc_self_reported', 'Summer 2020'),
  ('zipcolimited', 500, 'yc_self_reported', 'Summer 2020'),
  ('zippi', 60, 'yc_self_reported', 'Summer 2019'),
  ('ziprecruiter', 1000, 'public_records', NULL),
  ('zyngacareers', 1200, 'public_records', NULL)
ON CONFLICT (company_token) DO UPDATE
  SET employee_count = EXCLUDED.employee_count,
      employee_basis = EXCLUDED.employee_basis,
      yc_batch = EXCLUDED.yc_batch;

-- Segments v3: band by stated headcount when known, hiring footprint otherwise.
CREATE OR REPLACE FUNCTION public.get_size_segments()
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
SET statement_timeout = '25s'
AS $$
  WITH co AS (
    SELECT p.company_token,
           max(p.company) AS company,
           count(*)::int AS on_board,
           count(*) FILTER (WHERE p.remote)::int AS remote_n,
           count(*) FILTER (WHERE p.experience_band = 'entry')::int AS entry_n,
           COALESCE(v.feed_total, 0) AS feed_total,
           pr.employee_count, pr.employee_basis, pr.yc_batch
    FROM public.job_board_postings p
    LEFT JOIN public.job_board_verifications v ON v.company_token = p.company_token
    LEFT JOIN public.company_profiles pr ON pr.company_token = p.company_token
    WHERE p.company <> ''
      AND p.company_token NOT IN (SELECT company_token FROM public.showcase_excluded)
    GROUP BY p.company_token, v.feed_total, pr.employee_count, pr.employee_basis, pr.yc_batch
    HAVING count(*) >= 3
  ),
  named AS (
    SELECT company,
           (array_agg(company_token ORDER BY GREATEST(on_board, feed_total) DESC))[1] AS company_token,
           sum(on_board)::int AS on_board,
           sum(remote_n)::int AS remote_n,
           sum(entry_n)::int AS entry_n,
           NULLIF(sum(feed_total), 0)::int AS company_total,
           GREATEST(sum(on_board), sum(feed_total))::int AS effective,
           max(employee_count) AS employees,
           (array_agg(employee_basis ORDER BY employee_count DESC NULLS LAST))[1] AS employee_basis,
           (array_agg(yc_batch ORDER BY employee_count DESC NULLS LAST))[1] AS yc_batch
    FROM co GROUP BY company
  ),
  banded AS (
    SELECT *,
           CASE
             WHEN employees IS NOT NULL THEN
               CASE WHEN employees >= 1000 THEN 'enterprise'
                    WHEN employees >= 100 THEN 'mid'
                    ELSE 'small' END
             WHEN effective >= 500 THEN 'enterprise'
             WHEN effective >= 50 THEN 'mid'
             ELSE 'small' END AS band
    FROM named
  ),
  sal AS (
    SELECT b.band,
           round((percentile_cont(0.5) WITHIN GROUP (ORDER BY p.salary_min_annual))::numeric, 0) AS median_usd_floor,
           count(*)::int AS usd_n
    FROM public.job_board_postings p
    JOIN co ON co.company_token = p.company_token
    JOIN banded b ON b.company = co.company
    WHERE p.salary_currency = 'USD' AND p.salary_min_annual IS NOT NULL AND p.salary_min_annual > 0
    GROUP BY b.band
  ),
  agg AS (
    SELECT band,
           count(*)::int AS companies,
           count(*) FILTER (WHERE employees IS NOT NULL)::int AS with_headcount,
           sum(on_board)::int AS open_roles,
           round(100.0 * sum(remote_n) / GREATEST(sum(on_board), 1), 0) AS remote_pct,
           round(100.0 * sum(entry_n) / GREATEST(sum(on_board), 1), 0) AS entry_pct
    FROM banded GROUP BY band
  ),
  top AS (
    SELECT band, jsonb_agg(jsonb_build_object(
             'company', company, 'company_token', company_token,
             'on_board', on_board, 'company_total', company_total,
             'employees', employees, 'employee_basis', employee_basis,
             'yc_batch', yc_batch)
             ORDER BY (employees IS NOT NULL) DESC, COALESCE(employees, 0) DESC, effective DESC) AS top
    FROM (
      SELECT *, row_number() OVER (PARTITION BY band
               ORDER BY (employees IS NOT NULL) DESC, COALESCE(employees, 0) DESC, effective DESC) AS rn
      FROM banded
    ) r WHERE rn <= 12
    GROUP BY band
  )
  SELECT jsonb_object_agg(a.band, jsonb_build_object(
           'companies', a.companies, 'with_headcount', a.with_headcount,
           'open_roles', a.open_roles,
           'remote_pct', a.remote_pct, 'entry_pct', a.entry_pct,
           'median_usd_floor', s.median_usd_floor, 'usd_n', s.usd_n,
           'top', COALESCE(t.top, '[]'::jsonb)))
  FROM agg a
  LEFT JOIN sal s ON s.band = a.band
  LEFT JOIN top t ON t.band = a.band;
$$;
GRANT EXECUTE ON FUNCTION public.get_size_segments() TO anon, authenticated;

DO $$
BEGIN
  SET LOCAL statement_timeout = '55s';
  PERFORM public.refresh_explore_cache();
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;
