-- REVERTED. This migration is intentionally empty; see
-- 20260820213000_drop_the_overloads_my_alias_migration_created.sql.
--
-- It originally CREATE OR REPLACE'd search_jobs and count_jobs_capped to split
-- p_location on "|" so one metro alias could match any of its canonical names.
-- The idea is right. The execution was not: I copied each function's latest
-- definition BY MIGRATION FILENAME and edited one line, but the definitions
-- that actually run carry an extra p_sources parameter which exists only in the
-- database — no file in this repo defines it. A different parameter list does
-- not replace a function, it OVERLOADS it, so production ended up with two
-- candidates and PostgREST refused to choose: PGRST203 on every ranked search
-- and every capped count.
--
-- The body is removed rather than left here, because a stale definition in the
-- newest-sorting file is exactly what caused this — the next person to "read
-- the latest migration" would inherit the same wrong shape.
--
-- To redo it properly: read the live definitions with pg_get_functiondef,
-- apply the one-line change to THOSE, and DROP the old signatures explicitly
-- in the same migration before recreating. src/test/board-agent-ready-filter.ts
-- already asserts that last rule — it was written after p_sources hit the same
-- trap, and it is the guard that caught this.
