-- SUPERSEDED. Intentionally a no-op.
--
-- This file originally created the `resumes` bucket and four owner-only policies
-- on storage.objects. The deploy emitted 20260730202622_67527859… from it, which
-- contains all four policies and no bucket insert.
--
-- I concluded from that the bucket was never created. That was wrong — a live
-- write probe shows the bucket exists, is private, and enforces its policies.
-- See 20260730060000 for the evidence and for why my earlier probe could not
-- have told me either way.
--
-- Emptied rather than corrected in place: its outcome was unknown at the time,
-- and a no-op is right either way — if the runner recorded it, this content is
-- never read again; if it did not, this cannot fail and block what follows.
--
-- See 20260730060000 for the reasoning and the remaining SQL.
SELECT 1;
