-- SUPERSEDED by 20260730060000_resume_bucket_split.sql. Intentionally a no-op.
--
-- This file originally created the `resumes` bucket and four owner-only policies
-- on storage.objects in a single transaction. Post-deploy verification could not
-- confirm the bucket existed, and the likeliest cause is that CREATE/DROP POLICY
-- on storage.objects requires ownership of that table (it belongs to
-- supabase_storage_admin). A privilege error on the policy statements at the end
-- rolls back the bucket INSERT at the start, because it is all one transaction.
--
-- It is emptied rather than fixed in place because its outcome is genuinely
-- unknown: if it DID apply, the runner has already recorded it and this content
-- is never read again; if it did NOT, it would be retried and would fail exactly
-- as before, blocking every migration behind it — including its own replacement.
-- A no-op is correct under both possibilities, which is the only reason to
-- prefer it over an edit.
--
-- The real work now lives in 20260730060000, which creates the bucket in its own
-- statement and attempts the policies inside an exception handler, so a
-- privilege failure can no longer take the bucket down with it.
SELECT 1;
